import { promises as fs } from "node:fs";
import path from "node:path";

import * as z from "zod/v4";

import { blueprintConfigGet } from "./config.js";

export const BLUEPRINT_DIR = ".blueprint";
export const BLUEPRINT_STATE_PATH = `${BLUEPRINT_DIR}/STATE.md`;
export const BLUEPRINT_CONFIG_PATH = `${BLUEPRINT_DIR}/config.json`;
export const BLUEPRINT_PHASES_PATH = `${BLUEPRINT_DIR}/phases`;
export const BLUEPRINT_REPORTS_PATH = `${BLUEPRINT_DIR}/reports`;
export const BLUEPRINT_CODEBASE_PATH = `${BLUEPRINT_DIR}/codebase`;
export const SUPPORTED_BOOTSTRAP_ARTIFACTS = [
  `${BLUEPRINT_DIR}/PROJECT.md`,
  `${BLUEPRINT_DIR}/REQUIREMENTS.md`,
  `${BLUEPRINT_DIR}/ROADMAP.md`,
  `${BLUEPRINT_DIR}/phases/`
] as const;
export const CORE_PROJECT_ARTIFACTS = [
  `${BLUEPRINT_DIR}/PROJECT.md`,
  `${BLUEPRINT_DIR}/REQUIREMENTS.md`,
  `${BLUEPRINT_DIR}/ROADMAP.md`,
  BLUEPRINT_STATE_PATH,
  BLUEPRINT_CONFIG_PATH,
  `${BLUEPRINT_DIR}/phases/`
] as const;
export const CODEBASE_ARTIFACTS = [
  `${BLUEPRINT_CODEBASE_PATH}/STACK.md`,
  `${BLUEPRINT_CODEBASE_PATH}/ARCHITECTURE.md`,
  `${BLUEPRINT_CODEBASE_PATH}/STRUCTURE.md`,
  `${BLUEPRINT_CODEBASE_PATH}/CONVENTIONS.md`,
  `${BLUEPRINT_CODEBASE_PATH}/TESTING.md`,
  `${BLUEPRINT_CODEBASE_PATH}/INTEGRATIONS.md`,
  `${BLUEPRINT_CODEBASE_PATH}/CONCERNS.md`
] as const;
export const SUPPORTED_SCAFFOLD_ARTIFACTS = [
  ...SUPPORTED_BOOTSTRAP_ARTIFACTS,
  ...CODEBASE_ARTIFACTS
] as const;

export type SupportedScaffoldArtifact =
  (typeof SUPPORTED_SCAFFOLD_ARTIFACTS)[number];
export type BlueprintReadiness = "uninitialized" | "partial" | "initialized";

type ArtifactScaffoldArgs = {
  cwd?: string;
  artifacts?: string[];
  overwrite?: boolean;
  projectName?: string;
};

type ArtifactListArgs = {
  cwd?: string;
};

type ArtifactScaffoldResult = {
  createdFiles: string[];
  reusedFiles: string[];
  warnings: string[];
};

type ArtifactListResult = {
  artifacts: {
    core: string[];
    phases: string[];
    codebase: string[];
  };
  reports: string[];
  missing: string[];
  warnings: string[];
};

type ArtifactValidateArgs = {
  cwd?: string;
};

type ArtifactValidateResult = {
  valid: boolean;
  issues: string[];
  suggestedRepairs: string[];
  warnings: string[];
};

type ArtifactSummaryDigestArgs = {
  cwd?: string;
  focusArea?: string;
  packageJsonPath?: string;
  readmePath?: string;
  sourceFiles?: string[];
  testFiles?: string[];
  docFiles?: string[];
  trackedFiles?: string[];
};

type ArtifactSummaryDigestSection = {
  artifact: string;
  title: string;
  summary: string;
  evidence: string[];
};

type ArtifactSummaryDigestResult = {
  digest: ArtifactSummaryDigestSection[];
  inputsUsed: string[];
};

type ArtifactRenderer = (projectName: string) => string;
type PhaseArtifactRequest = {
  artifact: string;
  phaseDir: string;
  phaseName: string;
  phasePrefix: string;
  kind: "CONTEXT" | "DISCUSSION-LOG" | "RESEARCH" | "UI-SPEC";
};

const REQUIRED_RESEARCH_SECTIONS = [
  "Phase Requirements",
  "Summary",
  "User Constraints",
  "Standard Stack",
  "Architecture Patterns",
  "Don't Hand-Roll",
  "Common Pitfalls",
  "Code Examples",
  "Recommendations",
  "Sources"
] as const;
const RESEARCH_CONFIDENCE_VALUES = ["LOW", "MEDIUM", "HIGH"] as const;

const ARTIFACT_RENDERERS: Record<SupportedScaffoldArtifact, ArtifactRenderer> = {
  ".blueprint/PROJECT.md": (projectName) => `# ${projectName}

## Vision

Describe the product outcome Blueprint should help this repository reach.

## Audience

- Primary users:
- Secondary users:

## Constraints

- Installed as a Gemini CLI extension
- Project state lives in \`.blueprint/\`
- Persistent mutations must flow through Blueprint MCP tools

## Current Milestone

Define the smallest useful milestone that should land first.

## Non-Goals

- Hidden runtime conventions
- Undocumented aliases
- Prompt-only persistence
`,
  ".blueprint/REQUIREMENTS.md": (projectName) => `# Requirements: ${projectName}

## Requirements Table

| ID | Requirement | Status | Notes |
|----|-------------|--------|-------|
| RQ-01 | Replace this placeholder with the first real requirement. | Pending | Seeded by \`/blu:new-project\` |

## Acceptance Notes

- Convert placeholders into explicit requirements before planning.

## Deferred Items

- Add future work after the initial milestone is defined.
`,
  ".blueprint/ROADMAP.md": (projectName) => `# Roadmap: ${projectName}

## Milestone

- Active milestone: v1

## Phases

- [ ] Phase 1: Discovery and definition

## Notes

- Replace this starter roadmap with real phase goals before execution.
`,
  ".blueprint/phases/": () => "",
  ".blueprint/codebase/STACK.md": () => `# Stack

Generated by \`/blu:map-codebase\`.

- Record the runtime, languages, packages, and build tooling confirmed by repo evidence.
- Refresh only after explicit replace confirmation when the codebase changes materially.
`,
  ".blueprint/codebase/ARCHITECTURE.md": () => `# Architecture

Generated by \`/blu:map-codebase\`.

- Record the primary source layout, boundaries, and execution flow confirmed by repo evidence.
- Refresh only after explicit replace confirmation when the codebase changes materially.
`,
  ".blueprint/codebase/STRUCTURE.md": () => `# Structure

Generated by \`/blu:map-codebase\`.

- Record the directory layout, key file locations, and structural seams confirmed by repo evidence.
- Refresh only after explicit replace confirmation when the codebase changes materially.
`,
  ".blueprint/codebase/CONVENTIONS.md": () => `# Conventions

Generated by \`/blu:map-codebase\`.

- Record coding, naming, module, and documentation conventions confirmed by repo evidence.
- Refresh only after explicit replace confirmation when the codebase changes materially.
`,
  ".blueprint/codebase/TESTING.md": () => `# Testing

Generated by \`/blu:map-codebase\`.

- Record the test framework, commands, and coverage signals confirmed by repo evidence.
- Refresh only after explicit replace confirmation when the codebase changes materially.
`,
  ".blueprint/codebase/INTEGRATIONS.md": () => `# Integrations

Generated by \`/blu:map-codebase\`.

- Record external services, SDKs, and integration points confirmed by repo evidence.
- Refresh only after explicit replace confirmation when the codebase changes materially.
`,
  ".blueprint/codebase/CONCERNS.md": () => `# Concerns

Generated by \`/blu:map-codebase\`.

- Record current risks, thin areas, and follow-up questions confirmed by repo evidence.
- Refresh only after explicit replace confirmation when the codebase changes materially.
`
};

const artifactScaffoldInputSchema = {
  cwd: z.string().optional(),
  projectName: z.string().optional(),
  overwrite: z.boolean().optional(),
  artifacts: z.array(z.string()).optional()
};
const artifactListInputSchema = {
  cwd: z.string().optional()
};
const artifactValidateInputSchema = {
  cwd: z.string().optional()
};
const artifactSummaryDigestInputSchema = {
  cwd: z.string().optional(),
  focusArea: z.string().optional(),
  packageJsonPath: z.string().optional(),
  readmePath: z.string().optional(),
  sourceFiles: z.array(z.string()).optional(),
  testFiles: z.array(z.string()).optional(),
  docFiles: z.array(z.string()).optional(),
  trackedFiles: z.array(z.string()).optional()
};

const CODEBASE_SECTION_TITLES: Record<(typeof CODEBASE_ARTIFACTS)[number], string> = {
  ".blueprint/codebase/STACK.md": "Stack",
  ".blueprint/codebase/ARCHITECTURE.md": "Architecture",
  ".blueprint/codebase/STRUCTURE.md": "Structure",
  ".blueprint/codebase/CONVENTIONS.md": "Conventions",
  ".blueprint/codebase/TESTING.md": "Testing",
  ".blueprint/codebase/INTEGRATIONS.md": "Integrations",
  ".blueprint/codebase/CONCERNS.md": "Concerns"
};

function normalizePhaseNumber(value: string): string {
  return value
    .split(".")
    .map((segment) => {
      const trimmed = segment.trim().replace(/^0+(?=\d)/, "");
      return trimmed.length > 0 ? trimmed : "0";
    })
    .join(".");
}

function formatPhasePrefix(value: string): string {
  const normalized = normalizePhaseNumber(value);
  const [head, ...rest] = normalized.split(".");

  return [head.padStart(2, "0"), ...rest].join(".");
}

function slugToTitle(value: string): string {
  return value
    .split("-")
    .filter((segment) => segment.length > 0)
    .map((segment) => `${segment[0]?.toUpperCase() ?? ""}${segment.slice(1)}`)
    .join(" ");
}

function parsePhaseArtifactRequest(artifact: string): PhaseArtifactRequest | null {
  const match = artifact.match(
    /^\.blueprint\/phases\/([^/]+)\/((\d+(?:\.\d+)?)-(CONTEXT|DISCUSSION-LOG|RESEARCH|UI-SPEC)\.md)$/
  );

  if (!match) {
    return null;
  }

  const [, phaseDir, , rawPrefix, kind] = match;
  const directoryPrefix = phaseDir.match(/^(\d+(?:\.\d+)?)(?:-|$)/)?.[1];

  if (!directoryPrefix) {
    throw new Error(`Phase artifact path must use a numbered phase directory: ${artifact}`);
  }

  const normalizedDirectoryPrefix = normalizePhaseNumber(directoryPrefix);
  const normalizedFilePrefix = normalizePhaseNumber(rawPrefix);

  if (normalizedDirectoryPrefix !== normalizedFilePrefix) {
    throw new Error(`Phase artifact prefix must match its phase directory: ${artifact}`);
  }

  const canonicalPrefix = formatPhasePrefix(normalizedDirectoryPrefix);

  if (rawPrefix !== canonicalPrefix) {
    throw new Error(
      `Phase artifact prefix must use the canonical form ${canonicalPrefix}: ${artifact}`
    );
  }

  return {
    artifact,
    phaseDir,
    phaseName: slugToTitle(phaseDir.replace(/^\d+(?:\.\d+)?-?/, "")),
    phasePrefix: canonicalPrefix,
    kind: kind as PhaseArtifactRequest["kind"]
  };
}

function renderPhaseArtifact(request: PhaseArtifactRequest): string {
  const title = request.phaseName.length > 0 ? request.phaseName : "Phase";
  const phaseLabel = `Phase ${request.phasePrefix}: ${title}`;

  switch (request.kind) {
    case "CONTEXT":
      return `# ${phaseLabel} - Context

## Phase Boundary

- Goal:
- In scope:
- Out of scope:

## Decisions

- Capture the confirmed choices for this phase here.

## Dependencies

- Prior phase artifacts:
- External constraints:

## Open Questions

- Question 1:

---
*Generated by \`blueprint_artifact_scaffold\`*
`;
    case "DISCUSSION-LOG":
      return `# ${phaseLabel} - Discussion Log

## Summary

- Record the major discussion outcomes and unresolved questions here.

## Notes

- Timestamped notes:

## Follow-Ups

- Follow-up 1:

---
*Generated by \`blueprint_artifact_scaffold\`*
`;
    case "RESEARCH":
      return `# ${phaseLabel} - Research

**Researched:** YYYY-MM-DD
**Domain:** ${title} implementation research
**Confidence:** MEDIUM

## Phase Requirements

| ID | Description | Research Support |
|----|-------------|------------------|
| RQ-01 | Replace with the phase requirement this research supports. | Record the evidence-backed implementation guidance that helps later planning. |

## Summary

- Summarize the key conclusion in 2-4 bullets.

## User Constraints

- List repo, product, and workflow constraints that must remain true.

## Standard Stack

- Record the preferred runtime, libraries, and shared patterns already established in the repo.

## Architecture Patterns

- Capture the durable implementation patterns this phase should reuse.

## Don't Hand-Roll

- Name existing tools, helpers, or platform features that should be reused instead of reinvented.

## Common Pitfalls

- Call out likely failure modes, regressions, or drift risks.

## Code Examples

\`\`\`text
Add short code or pseudocode examples here when they materially reduce implementation risk.
\`\`\`

## Recommendations

- Use imperative, prescriptive guidance with clear tradeoffs.

## Sources

- [Source title](https://example.com) - why it matters

---
*Generated by \`blueprint_artifact_scaffold\`*
`;
    case "UI-SPEC":
      return `# ${phaseLabel} - UI Spec

## Outcome Mode

- Choose one: UI contract or explicit skip rationale.

## User Experience Goals

- Goal 1:

## Screens And States

- Screen/state 1:

## Components And Constraints

- Component 1:

## Accessibility And Content

- Accessibility note 1:

---
*Generated by \`blueprint_artifact_scaffold\`*
`;
  }
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}

export function toPosixPath(relativePath: string): string {
  return relativePath.split(path.sep).join("/");
}

export function getProjectRoot(cwd?: string): string {
  return path.resolve(cwd ?? process.cwd());
}

export function getBlueprintRoot(cwd?: string): string {
  return path.join(getProjectRoot(cwd), BLUEPRINT_DIR);
}

export async function blueprintPathExists(targetPath: string): Promise<boolean> {
  return pathExists(targetPath);
}

export async function ensureRepoRoot(cwd?: string): Promise<string> {
  const projectRoot = getProjectRoot(cwd);
  const gitPath = path.join(projectRoot, ".git");

  if (!(await pathExists(gitPath))) {
    throw new Error(
      "Blueprint commands must run from the repository root; no .git entry was found in the current directory."
    );
  }

  return projectRoot;
}

export function toRepoRelativePath(projectRoot: string, absolutePath: string): string {
  return toPosixPath(path.relative(projectRoot, absolutePath));
}

export function resolveRepoRelativePath(
  projectRoot: string,
  relativePath: string
): string {
  const absolutePath = path.resolve(projectRoot, relativePath);
  const relativeToRoot = path.relative(projectRoot, absolutePath);

  if (
    relativeToRoot.startsWith("..") ||
    path.isAbsolute(relativeToRoot)
  ) {
    throw new Error(`Path traversal is not allowed: ${relativePath}`);
  }

  return absolutePath;
}

export function resolveBlueprintPath(
  projectRoot: string,
  relativePath: string
): string {
  if (!relativePath.startsWith(`${BLUEPRINT_DIR}/`)) {
    throw new Error(
      `Blueprint artifacts must stay inside ${BLUEPRINT_DIR}/: ${relativePath}`
    );
  }

  const absolutePath = resolveRepoRelativePath(projectRoot, relativePath);
  const relativeToBlueprintRoot = path.relative(getBlueprintRoot(projectRoot), absolutePath);

  if (
    relativeToBlueprintRoot.startsWith("..") ||
    path.isAbsolute(relativeToBlueprintRoot)
  ) {
    throw new Error(`Path traversal is not allowed: ${relativePath}`);
  }

  return absolutePath;
}

export async function ensureParentDirectory(targetPath: string): Promise<void> {
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
}

export async function readJsonIfPresent(
  filePath: string
): Promise<Record<string, unknown> | null> {
  if (!(await pathExists(filePath))) {
    return null;
  }

  const raw = await fs.readFile(filePath, "utf8");
  const parsed = JSON.parse(raw) as unknown;

  if (!isPlainObject(parsed)) {
    throw new Error(`${filePath} must contain a JSON object.`);
  }

  return parsed;
}

export async function writeJsonFile(
  filePath: string,
  value: Record<string, unknown>
): Promise<void> {
  await ensureParentDirectory(filePath);
  await fs.writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

export async function writeTextFile(
  filePath: string,
  value: string
): Promise<void> {
  await ensureParentDirectory(filePath);
  await fs.writeFile(filePath, value, "utf8");
}

function extractMarkdownSection(markdown: string, heading: string): string {
  const escapedHeading = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = markdown.match(
    new RegExp(`(?:^|\\n)## ${escapedHeading}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`)
  );

  return match?.[1]?.trim() ?? "";
}

function containsSourceEvidence(section: string): boolean {
  return /https?:\/\/|`[^`]+`|\.blueprint\/|docs\/|src\/|tests\//.test(section);
}

export function validateResearchArtifactContent(content: string): {
  valid: boolean;
  issues: string[];
  warnings: string[];
} {
  const issues: string[] = [];
  const warnings: string[] = [];
  const placeholderSignals = [
    "YYYY-MM-DD",
    "https://example.com",
    "Replace with the phase requirement",
    "*Generated by `blueprint_artifact_scaffold`*"
  ];

  if (!/^# .+ - Research\s*$/m.test(content)) {
    issues.push("Research artifact must start with a '# ... - Research' heading.");
  }

  if (placeholderSignals.some((signal) => content.includes(signal))) {
    issues.push(
      "Research artifact still contains scaffold placeholder text and must be replaced with real research content."
    );
  }

  const confidenceMatch = content.match(
    /^\*\*Confidence:\*\*\s*(LOW|MEDIUM|HIGH)\s*$/m
  );

  if (!confidenceMatch) {
    issues.push(
      `Research artifact must declare **Confidence:** using one of ${RESEARCH_CONFIDENCE_VALUES.join(", ")}.`
    );
  }

  for (const heading of REQUIRED_RESEARCH_SECTIONS) {
    if (!new RegExp(`(?:^|\\n)## ${heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*$`, "m").test(content)) {
      issues.push(`Research artifact is missing required section: ${heading}.`);
    }
  }

  const recommendations = extractMarkdownSection(content, "Recommendations");

  if (!/^- /m.test(recommendations)) {
    issues.push("Research artifact must include at least one bullet under Recommendations.");
  }

  const sources = extractMarkdownSection(content, "Sources");

  if (!/^- /m.test(sources) || !containsSourceEvidence(sources)) {
    issues.push(
      "Research artifact must include at least one source bullet with a URL, repo path, or cited file."
    );
  }

  const codeExamples = extractMarkdownSection(content, "Code Examples");

  if (!/```/.test(codeExamples)) {
    warnings.push("Research artifact should include a fenced code or pseudocode example when examples add value.");
  }

  return {
    valid: issues.length === 0,
    issues,
    warnings
  };
}

async function listRelativeFiles(rootPath: string, projectRoot: string): Promise<string[]> {
  if (!(await pathExists(rootPath))) {
    return [];
  }

  const entries = await fs.readdir(rootPath, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const absolutePath = path.join(rootPath, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await listRelativeFiles(absolutePath, projectRoot)));
      continue;
    }

    files.push(toRepoRelativePath(projectRoot, absolutePath));
  }

  return files.sort();
}

async function listImmediateDirectories(rootPath: string): Promise<string[]> {
  if (!(await pathExists(rootPath))) {
    return [];
  }

  const entries = await fs.readdir(rootPath, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

export async function inspectBlueprintArtifacts(projectRoot: string): Promise<{
  readiness: BlueprintReadiness;
  blueprintRootExists: boolean;
  core: { present: string[]; missing: string[] };
  phases: string[];
  reports: string[];
  codebase: { present: string[]; missing: string[] };
}> {
  const blueprintRoot = getBlueprintRoot(projectRoot);
  const blueprintRootExists = await pathExists(blueprintRoot);
  const corePresent: string[] = [];
  const coreMissing: string[] = [];

  for (const artifact of CORE_PROJECT_ARTIFACTS) {
    const artifactPath = resolveBlueprintPath(projectRoot, artifact);

    if (await pathExists(artifactPath)) {
      corePresent.push(artifact);
    } else {
      coreMissing.push(artifact);
    }
  }

  const phases = await listRelativeFiles(
    resolveBlueprintPath(projectRoot, BLUEPRINT_PHASES_PATH),
    projectRoot
  );
  const reports = await listRelativeFiles(
    resolveBlueprintPath(projectRoot, BLUEPRINT_REPORTS_PATH),
    projectRoot
  );
  const codebasePresent: string[] = [];
  const codebaseMissing: string[] = [];

  for (const artifact of CODEBASE_ARTIFACTS) {
    const artifactPath = resolveBlueprintPath(projectRoot, artifact);

    if (await pathExists(artifactPath)) {
      codebasePresent.push(artifact);
    } else {
      codebaseMissing.push(artifact);
    }
  }

  const readiness: BlueprintReadiness = !blueprintRootExists
    ? "uninitialized"
    : coreMissing.length === 0
      ? "initialized"
      : "partial";

  return {
    readiness,
    blueprintRootExists,
    core: {
      present: corePresent,
      missing: coreMissing
    },
    phases,
    reports,
    codebase: {
      present: codebasePresent,
      missing: codebaseMissing
    }
  };
}

function normalizeRequestedArtifacts(
  requestedArtifacts?: string[]
): string[] {
  if (!requestedArtifacts || requestedArtifacts.length === 0) {
    return [...SUPPORTED_BOOTSTRAP_ARTIFACTS];
  }

  const normalized = requestedArtifacts.map((artifact) => {
    const value = artifact.trim();

    if (
      !SUPPORTED_SCAFFOLD_ARTIFACTS.includes(value as SupportedScaffoldArtifact) &&
      !parsePhaseArtifactRequest(value)
    ) {
      throw new Error(`Unsupported Blueprint artifact requested: ${artifact}`);
    }

    return value;
  });

  return [...new Set(normalized)];
}

function isCodebaseArtifact(
  artifact: SupportedScaffoldArtifact
): artifact is (typeof CODEBASE_ARTIFACTS)[number] {
  return CODEBASE_ARTIFACTS.includes(artifact as (typeof CODEBASE_ARTIFACTS)[number]);
}

function inferProjectName(projectRoot: string, requestedName?: string): string {
  const trimmed = requestedName?.trim();

  if (trimmed) {
    return trimmed;
  }

  return path.basename(projectRoot);
}

export async function blueprintArtifactScaffold(
  args: ArtifactScaffoldArgs = {}
): Promise<ArtifactScaffoldResult> {
  const projectRoot = await ensureRepoRoot(args.cwd);
  const projectName = inferProjectName(projectRoot, args.projectName);
  const overwrite = args.overwrite ?? false;
  const artifacts = normalizeRequestedArtifacts(args.artifacts);
  const createdFiles: string[] = [];
  const reusedFiles: string[] = [];
  const warnings: string[] = [];

  await fs.mkdir(getBlueprintRoot(projectRoot), { recursive: true });

  for (const artifact of artifacts) {
    const absolutePath = resolveBlueprintPath(projectRoot, artifact);
    const exists = await pathExists(absolutePath);
    const phaseArtifactRequest = parsePhaseArtifactRequest(artifact);

    if (artifact.endsWith("/")) {
      if (exists) {
        reusedFiles.push(artifact);
      } else {
        await fs.mkdir(absolutePath, { recursive: true });
        createdFiles.push(artifact);
      }
      continue;
    }

    if (exists && !overwrite) {
      reusedFiles.push(artifact);
      if (
        SUPPORTED_SCAFFOLD_ARTIFACTS.includes(artifact as SupportedScaffoldArtifact) &&
        isCodebaseArtifact(artifact as SupportedScaffoldArtifact)
      ) {
        warnings.push(
          `Preserved existing codebase artifact: ${artifact}. Reuse it unless an explicit replace path is confirmed.`
        );
      }
      continue;
    }

    const renderArtifact =
      phaseArtifactRequest
        ? () => renderPhaseArtifact(phaseArtifactRequest)
        : ARTIFACT_RENDERERS[artifact as SupportedScaffoldArtifact];

    if (!renderArtifact) {
      warnings.push(`No renderer registered for ${artifact}; skipped.`);
      continue;
    }

    await writeTextFile(absolutePath, renderArtifact(projectName));

    if (exists) {
      warnings.push(
        SUPPORTED_SCAFFOLD_ARTIFACTS.includes(artifact as SupportedScaffoldArtifact) &&
        isCodebaseArtifact(artifact as SupportedScaffoldArtifact)
          ? `Replaced existing codebase artifact: ${artifact}`
          : `Replaced existing artifact: ${artifact}`
      );
    } else {
      createdFiles.push(artifact);
    }
  }

  return {
    createdFiles,
    reusedFiles,
    warnings
  };
}

export async function blueprintArtifactList(
  args: ArtifactListArgs = {}
): Promise<ArtifactListResult> {
  const projectRoot = await ensureRepoRoot(args.cwd);
  const inspection = await inspectBlueprintArtifacts(projectRoot);
  const missing = [...inspection.core.missing];
  const warnings: string[] = [];

  if (inspection.codebase.present.length > 0 && inspection.codebase.missing.length > 0) {
    missing.push(...inspection.codebase.missing);
  }

  if (inspection.codebase.present.length > 0) {
    warnings.push(
      `Existing codebase artifacts will be reused unless replace is explicitly confirmed: ${inspection.codebase.present.join(", ")}`
    );
  }

  return {
    artifacts: {
      core: inspection.core.present,
      phases: inspection.phases,
      codebase: inspection.codebase.present
    },
    reports: inspection.reports,
    missing,
    warnings
  };
}

function collectPhaseBundleIssues(
  phaseArtifacts: string[],
  phaseDirectories: string[]
): string[] {
  const issues: string[] = [];

  for (const directoryName of phaseDirectories) {
    const phasePrefix = directoryName.match(/^(\d+(?:\.\d+)?)/)?.[1];

    if (!phasePrefix) {
      continue;
    }

    const expectedPrefix = `${BLUEPRINT_PHASES_PATH}/${directoryName}/${phasePrefix}`;
    const hasContext = phaseArtifacts.some((artifact) =>
      artifact.endsWith(`${expectedPrefix}-CONTEXT.md`)
    );
    const hasResearch = phaseArtifacts.some((artifact) =>
      artifact.endsWith(`${expectedPrefix}-RESEARCH.md`)
    );
    const hasPlan = phaseArtifacts.some((artifact) =>
      artifact.includes(`${expectedPrefix}-`) && artifact.endsWith("-PLAN.md")
    );

    if (!hasContext || !hasResearch || !hasPlan) {
      const missingParts = [
        !hasContext ? "CONTEXT" : null,
        !hasResearch ? "RESEARCH" : null,
        !hasPlan ? "PLAN" : null
      ].filter((value): value is string => value !== null);

      issues.push(
        `Phase artifact bundle is incomplete for ${directoryName}: missing ${missingParts.join(", ")}`
      );
    }
  }

  return issues;
}

export async function blueprintArtifactValidate(
  args: ArtifactValidateArgs = {}
): Promise<ArtifactValidateResult> {
  const projectRoot = await ensureRepoRoot(args.cwd);
  const inspection = await inspectBlueprintArtifacts(projectRoot);
  const issues: string[] = [];
  const suggestedRepairs = new Set<string>();
  const warnings: string[] = [];

  if (!inspection.blueprintRootExists) {
    issues.push(`Missing ${BLUEPRINT_DIR}/ directory.`);
    suggestedRepairs.add("Run /blu:new-project to initialize Blueprint artifacts.");
  }

  for (const artifact of inspection.core.missing) {
    issues.push(`Missing core artifact: ${artifact}`);
  }

  if (inspection.core.missing.length > 0) {
    suggestedRepairs.add("Run /blu:health to inspect partial Blueprint state.");
    suggestedRepairs.add("Use /blu:health --repair only after reviewing the proposed writes.");
  }

  const configPath = resolveBlueprintPath(projectRoot, BLUEPRINT_CONFIG_PATH);
  const configExists = await pathExists(configPath);

  if (configExists) {
    try {
      const config = await blueprintConfigGet({
        scope: "project",
        cwd: projectRoot
      });

      for (const warning of config.warnings) {
        issues.push(`Config warning: ${warning}`);
      }

      if (config.warnings.length > 0) {
        suggestedRepairs.add(
          "Run /blu:health --repair to normalize malformed or legacy Blueprint config."
        );
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      issues.push(`Malformed config: ${message}`);
      suggestedRepairs.add(
        "Run /blu:health --repair to rewrite .blueprint/config.json in normalized form."
      );
    }
  }

  const phaseDirectories = await listImmediateDirectories(
    resolveBlueprintPath(projectRoot, BLUEPRINT_PHASES_PATH)
  );

  for (const issue of collectPhaseBundleIssues(inspection.phases, phaseDirectories)) {
    issues.push(issue);
    suggestedRepairs.add("Restore or regenerate the missing phase artifacts before execution.");
  }

  if (inspection.codebase.present.length > 0 && inspection.codebase.missing.length > 0) {
    issues.push(
      `Codebase artifact bundle is incomplete: missing ${inspection.codebase.missing.join(", ")}`
    );
    suggestedRepairs.add("Re-run /blu:map-codebase to recreate the missing codebase artifacts.");
  }

  if (inspection.codebase.present.length > 0) {
    warnings.push(
      "Existing codebase artifacts are present and should be reused unless replace is explicitly confirmed."
    );
  }

  for (const artifact of inspection.phases.filter((value) => value.endsWith("-RESEARCH.md"))) {
    const absolutePath = resolveBlueprintPath(projectRoot, artifact);
    const raw = await fs.readFile(absolutePath, "utf8");
    const validation = validateResearchArtifactContent(raw);

    for (const issue of validation.issues) {
      issues.push(`${artifact}: ${issue}`);
    }

    for (const warning of validation.warnings) {
      warnings.push(`${artifact}: ${warning}`);
    }

    if (!validation.valid) {
      suggestedRepairs.add(
        "Regenerate or update malformed phase research through /blu:research-phase before planning."
      );
    }
  }

  return {
    valid: issues.length === 0,
    issues,
    suggestedRepairs: [...suggestedRepairs],
    warnings
  };
}

type PackageManifest = {
  name?: unknown;
  type?: unknown;
  scripts?: unknown;
  dependencies?: unknown;
  devDependencies?: unknown;
};

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right));
}

function normalizeInputPaths(projectRoot: string, values?: string[]): string[] {
  if (!values || values.length === 0) {
    return [];
  }

  return uniqueSorted(
    values
      .map((value) => value.trim())
      .filter((value) => value.length > 0)
      .map((value) => toRepoRelativePath(projectRoot, resolveRepoRelativePath(projectRoot, value)))
  );
}

async function normalizeOptionalRepoPath(
  projectRoot: string,
  value: string | undefined,
  fallback: string
): Promise<string | null> {
  const candidate = value?.trim() || fallback;
  const absolutePath = resolveRepoRelativePath(projectRoot, candidate);

  if (!(await pathExists(absolutePath))) {
    return null;
  }

  return toRepoRelativePath(projectRoot, absolutePath);
}

function asRecord(value: unknown): Record<string, unknown> {
  return isPlainObject(value) ? value : {};
}

function collectDependencyNames(manifest: PackageManifest): string[] {
  return uniqueSorted([
    ...Object.keys(asRecord(manifest.dependencies)),
    ...Object.keys(asRecord(manifest.devDependencies))
  ]);
}

function detectTestFramework(manifest: PackageManifest, testFiles: string[]): string {
  const scripts = asRecord(manifest.scripts);
  const testScript = typeof scripts.test === "string" ? scripts.test : "";
  const dependencies = collectDependencyNames(manifest);

  if (testScript.includes("--test") || testFiles.some((file) => file.endsWith(".test.ts"))) {
    return testScript.includes("tsx")
      ? "node:test via tsx --test"
      : "node:test";
  }

  if (dependencies.includes("vitest")) {
    return "Vitest";
  }

  if (dependencies.includes("jest")) {
    return "Jest";
  }

  return testFiles.length > 0 ? "custom test harness" : "no test framework detected";
}

function summarizeTopDirectories(files: string[]): string[] {
  return uniqueSorted(
    files
      .map((file) => file.split("/")[0] ?? file)
      .filter((segment) => segment.length > 0)
  );
}

function summarizeIntegrations(
  dependencies: string[],
  sourceFiles: string[],
  trackedFiles: string[]
): string[] {
  const integrationPackages = dependencies.filter((dependency) =>
    /^@modelcontextprotocol\/sdk$|^@octokit\/rest$|^axios$|^zod$/.test(dependency)
  );
  const integrationPaths = uniqueSorted(
    [...sourceFiles, ...trackedFiles].filter((file) => file.includes("/integrations/"))
  );

  return uniqueSorted([...integrationPackages, ...integrationPaths]).slice(0, 5);
}

function buildCodebaseDigestSections(args: {
  focusArea?: string;
  packageManifest: PackageManifest;
  packageJsonPath: string | null;
  readmePath: string | null;
  sourceFiles: string[];
  testFiles: string[];
  docFiles: string[];
  trackedFiles: string[];
}): ArtifactSummaryDigestSection[] {
  const dependencies = collectDependencyNames(args.packageManifest);
  const testFramework = detectTestFramework(args.packageManifest, args.testFiles);
  const sourceRoots = summarizeTopDirectories(args.sourceFiles);
  const docRoots = summarizeTopDirectories(args.docFiles);
  const runtime =
    args.sourceFiles.some((file) => file.endsWith(".ts") || file.endsWith(".tsx")) ||
    dependencies.includes("typescript")
      ? "TypeScript"
      : "JavaScript";
  const moduleType =
    typeof args.packageManifest.type === "string" && args.packageManifest.type.length > 0
      ? args.packageManifest.type
      : "commonjs";
  const integrations = summarizeIntegrations(
    dependencies,
    args.sourceFiles,
    args.trackedFiles
  );
  const focusSuffix =
    args.focusArea && args.focusArea.trim().length > 0
      ? ` Focus area requested: ${args.focusArea.trim()}.`
      : "";

  return [
    {
      artifact: `${BLUEPRINT_CODEBASE_PATH}/STACK.md`,
      title: CODEBASE_SECTION_TITLES[`${BLUEPRINT_CODEBASE_PATH}/STACK.md`],
      summary: `${runtime} ${moduleType} project with ${testFramework}. Key package evidence comes from ${args.packageJsonPath ?? "package.json"} and tracked source files.${focusSuffix}`,
      evidence: uniqueSorted(
        [args.packageJsonPath, ...args.sourceFiles.slice(0, 2), ...args.testFiles.slice(0, 1)].filter(
          (value): value is string => Boolean(value)
        )
      )
    },
    {
      artifact: `${BLUEPRINT_CODEBASE_PATH}/ARCHITECTURE.md`,
      title: CODEBASE_SECTION_TITLES[`${BLUEPRINT_CODEBASE_PATH}/ARCHITECTURE.md`],
      summary: `Primary layout centers on ${sourceRoots.join(", ") || "the repo root"}, with ${args.trackedFiles.length} tracked files informing the initial architecture map.${focusSuffix}`,
      evidence: uniqueSorted([...args.sourceFiles.slice(0, 3), ...args.trackedFiles.slice(0, 2)])
    },
    {
      artifact: `${BLUEPRINT_CODEBASE_PATH}/STRUCTURE.md`,
      title: CODEBASE_SECTION_TITLES[`${BLUEPRINT_CODEBASE_PATH}/STRUCTURE.md`],
      summary: `Repository structure is anchored around ${sourceRoots.join(", ") || "the repo root"} with document roots in ${docRoots.join(", ") || "README-only docs"}. Use this map to find implementation seams quickly.${focusSuffix}`,
      evidence: uniqueSorted([
        ...args.sourceFiles.slice(0, 4),
        ...args.docFiles.slice(0, 2),
        ...args.trackedFiles.slice(0, 2)
      ])
    },
    {
      artifact: `${BLUEPRINT_CODEBASE_PATH}/CONVENTIONS.md`,
      title: CODEBASE_SECTION_TITLES[`${BLUEPRINT_CODEBASE_PATH}/CONVENTIONS.md`],
      summary: `The repo signals ${runtime} conventions, ${moduleType} modules, and documented guidance via ${docRoots.join(", ") || "README-only docs"}.`,
      evidence: uniqueSorted(
        [args.readmePath, ...args.docFiles.slice(0, 2), ...args.sourceFiles.slice(0, 2)].filter(
          (value): value is string => Boolean(value)
        )
      )
    },
    {
      artifact: `${BLUEPRINT_CODEBASE_PATH}/TESTING.md`,
      title: CODEBASE_SECTION_TITLES[`${BLUEPRINT_CODEBASE_PATH}/TESTING.md`],
      summary: `Testing evidence points to ${testFramework} with ${args.testFiles.length} test file(s) and documentation coverage in ${docRoots.includes("docs") ? "docs/" : "README.md"}.`,
      evidence: uniqueSorted(
        [...args.testFiles.slice(0, 3), ...args.docFiles.filter((file) => file.startsWith("docs/")).slice(0, 1)]
      )
    },
    {
      artifact: `${BLUEPRINT_CODEBASE_PATH}/INTEGRATIONS.md`,
      title: CODEBASE_SECTION_TITLES[`${BLUEPRINT_CODEBASE_PATH}/INTEGRATIONS.md`],
      summary:
        integrations.length > 0
          ? `Detected integration signals include ${integrations.join(", ")}.`
          : "No explicit third-party integration surface was detected from the supplied repo evidence.",
      evidence: uniqueSorted(
        [...integrations, ...args.sourceFiles.filter((file) => file.includes("/integrations/")).slice(0, 2)]
      )
    },
    {
      artifact: `${BLUEPRINT_CODEBASE_PATH}/CONCERNS.md`,
      title: CODEBASE_SECTION_TITLES[`${BLUEPRINT_CODEBASE_PATH}/CONCERNS.md`],
      summary:
        args.docFiles.length > 0
          ? `Docs exist under ${docRoots.join(", ")}, but reruns should preserve edited codebase docs unless replace is explicitly confirmed.`
          : "Documentation signals are thin, so generated codebase docs should be reviewed before deeper discovery or planning.",
      evidence: uniqueSorted(
        [...args.docFiles.slice(0, 2), ...args.trackedFiles.slice(0, 2), ...args.testFiles.slice(0, 1)]
      )
    }
  ];
}

export async function blueprintArtifactSummaryDigest(
  args: ArtifactSummaryDigestArgs = {}
): Promise<ArtifactSummaryDigestResult> {
  const projectRoot = await ensureRepoRoot(args.cwd);
  const packageJsonPath = await normalizeOptionalRepoPath(
    projectRoot,
    args.packageJsonPath,
    "package.json"
  );
  const readmePath = await normalizeOptionalRepoPath(projectRoot, args.readmePath, "README.md");
  const sourceFiles = normalizeInputPaths(projectRoot, args.sourceFiles);
  const testFiles = normalizeInputPaths(projectRoot, args.testFiles);
  const docFiles = normalizeInputPaths(projectRoot, args.docFiles);
  const trackedFiles = normalizeInputPaths(projectRoot, args.trackedFiles);

  let packageManifest: PackageManifest = {};

  if (packageJsonPath) {
    try {
      const packageJson = await readJsonIfPresent(
        resolveRepoRelativePath(projectRoot, packageJsonPath)
      );
      packageManifest = packageJson ?? {};
    } catch {
      packageManifest = {};
    }
  }

  const digest = buildCodebaseDigestSections({
    focusArea: args.focusArea,
    packageManifest,
    packageJsonPath,
    readmePath,
    sourceFiles,
    testFiles,
    docFiles,
    trackedFiles
  });
  const inputsUsed = uniqueSorted([
    packageJsonPath ?? "",
    readmePath ?? "",
    ...sourceFiles,
    ...testFiles,
    ...docFiles,
    ...trackedFiles
  ]).filter((value) => value.length > 0);

  return {
    digest,
    inputsUsed
  };
}

export const artifactToolDefinitions = [
  {
    name: "blueprint_artifact_scaffold",
    description:
      "Create or reuse Blueprint bootstrap, codebase, and phase artifacts inside .blueprint/.",
    inputSchema: artifactScaffoldInputSchema,
    handler: async (args: Record<string, unknown>) =>
      blueprintArtifactScaffold(args as ArtifactScaffoldArgs)
  },
  {
    name: "blueprint_artifact_list",
    description:
      "List Blueprint core, phase, codebase, and report artifacts without mutating the repo.",
    inputSchema: artifactListInputSchema,
    handler: async (args: Record<string, unknown>) =>
      blueprintArtifactList(args as ArtifactListArgs)
  },
  {
    name: "blueprint_artifact_validate",
    description:
      "Validate Blueprint artifact structure, config health, and bundle completeness.",
    inputSchema: artifactValidateInputSchema,
    handler: async (args: Record<string, unknown>) =>
      blueprintArtifactValidate(args as ArtifactValidateArgs)
  },
  {
    name: "blueprint_artifact_summary_digest",
    description:
      "Build deterministic codebase mapping digests from repo evidence without mutating Blueprint artifacts.",
    inputSchema: artifactSummaryDigestInputSchema,
    handler: async (args: Record<string, unknown>) =>
      blueprintArtifactSummaryDigest(args as ArtifactSummaryDigestArgs)
  }
];
