import { promises as fs } from "node:fs";

import {
  extractSummaryMarkerValue,
  extractSummaryPlanReference,
  extractSummaryStatus,
  resolveBlueprintPath,
  validateStrictSummaryArtifactContent
} from "./artifacts.js";
import {
  filterImplementedBlueprintActions,
  getPhasePlanImplementedCommandNames
} from "./phase-command-actions.js";
import {
  normalizeDependencyPlanIds,
  parseSummaryArtifactPath,
  summaryPathFor,
  type PhaseSummaryCompletedRouteValidation
} from "./phase-summary-routing.js";
import {
  planPathFor
} from "./phase-plan-identifiers.js";
import type {
  LoadedPhaseSummaryInventoryRecord,
  PhaseLocateResult,
  PhasePlanIndexResult,
  PhasePlanRecord,
  PhaseSummaryInventory,
  PhaseSummaryReadResult,
  PhaseSummaryRecord,
  ResolvedPhaseLocation
} from "./phase-tool-types.js";

export function summarizeMarkdownContent(content: string): {
  title: string | null;
  summary: string | null;
} {
  const title = content.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? null;
  const summary =
    content
      .split("\n")
      .map((line) => line.trim())
      .find(
        (line) =>
          line.length > 0 &&
          !line.startsWith("#") &&
          line !== "---" &&
          !line.startsWith("*Generated by")
      ) ?? null;

  return {
    title,
    summary
  };
}

export function toPhaseSummaryRecord(
  planId: string,
  pathValue: string,
  content: string,
  linkedPlanPath: string | null
): PhaseSummaryRecord {
  const metadata = summarizeMarkdownContent(content);
  const status = extractSummaryStatus(content);

  return {
    planId,
    path: pathValue,
    linkedPlanPath,
    status,
    title: metadata.title,
    summary: metadata.summary
  };
}

export type ValidateSummaryAgainstLivePlanInventory = (
  content: string,
  args: {
    resolved: Pick<ResolvedPhaseLocation, "phaseNumber" | "phaseDir" | "phasePrefix">;
    planId: string;
    plan: PhasePlanRecord | null;
    knownPlanIds: ReadonlySet<string>;
    completedDependencyPlanIds?: ReadonlySet<string>;
    completedRouteValidation?: PhaseSummaryCompletedRouteValidation;
  }
) => {
  valid: boolean;
  issues: string[];
  warnings: string[];
};

export async function loadPhaseSummaryInventory(args: {
  projectRoot: string;
  located: PhaseLocateResult;
  resolved: ResolvedPhaseLocation;
  planIndex: PhasePlanIndexResult;
  validateSummaryAgainstLivePlanInventory: ValidateSummaryAgainstLivePlanInventory;
}): Promise<PhaseSummaryInventory> {
  const {
    projectRoot,
    located,
    resolved,
    planIndex,
    validateSummaryAgainstLivePlanInventory
  } = args;
  const summaryPaths = located.artifacts
    .filter((artifact) => artifact.endsWith("-SUMMARY.md"))
    .sort((left, right) => left.localeCompare(right));
  const summaries: PhaseSummaryRecord[] = [];
  let completedPlans = new Set<string>();
  const warnings = [...planIndex.warnings];
  const knownPlanIds = new Set(planIndex.plans.map((plan) => plan.planId));
  const knownPlanPaths = new Map(planIndex.plans.map((plan) => [plan.planId, plan.path]));
  const planRecordsById = new Map(planIndex.plans.map((plan) => [plan.planId, plan]));
  const loadedSummaries: LoadedPhaseSummaryInventoryRecord[] = [];

  for (const summaryPath of summaryPaths) {
    const planId = parseSummaryArtifactPath(summaryPath, resolved.phasePrefix);

    if (!planId) {
      warnings.push(`Ignoring non-canonical summary artifact name: ${summaryPath}`);
      continue;
    }

    const content = await fs.readFile(resolveBlueprintPath(projectRoot, summaryPath), "utf8");
    const linkedPlanPath = extractSummaryPlanReference(content);
    const strictValidation = validateStrictSummaryArtifactContent(content, {
      linkedPlanPath: knownPlanPaths.get(planId) ?? null
    });
    const linkedPlan = planRecordsById.get(planId) ?? null;
    const livePlanValidation = validateSummaryAgainstLivePlanInventory(content, {
      resolved,
      planId,
      plan: linkedPlan,
      knownPlanIds,
      completedRouteValidation: { mode: "skip" }
    });
    const validation = {
      valid: strictValidation.valid && livePlanValidation.valid,
      issues: [...strictValidation.issues, ...livePlanValidation.issues],
      warnings: [...strictValidation.warnings, ...livePlanValidation.warnings]
    };
    const record = toPhaseSummaryRecord(planId, summaryPath, content, linkedPlanPath);
    const summaryStatus = extractSummaryStatus(content);
    const completedEvidence = summaryCountsAsCompleted(summaryStatus, content);
    const legacyCompletedEvidence = completedEvidence && summaryStatus === null;

    summaries.push(record);
    loadedSummaries.push({
      planId,
      path: summaryPath,
      content,
      record,
      status: summaryStatus,
      completedEvidence,
      legacyCompletedEvidence,
      strictValidation,
      validation,
      linkedPlan,
      dependencyPlanIds: linkedPlan ? normalizeDependencyPlanIds(linkedPlan.dependsOn) : []
    });
  }

  const authoritativeSummariesByPlanId = new Map<string, LoadedPhaseSummaryInventoryRecord>();

  for (const loaded of loadedSummaries) {
    const canonicalSummaryPath = summaryPathFor(resolved, loaded.planId);

    if (loaded.path !== canonicalSummaryPath) {
      warnings.push(
        `${loaded.path}: ignoring non-canonical duplicate summary for plan ${loaded.planId}; canonical summary path is ${canonicalSummaryPath}.`
      );
      continue;
    }

    authoritativeSummariesByPlanId.set(loaded.planId, loaded);
  }

  const authoritativeLoadedSummaries = [...authoritativeSummariesByPlanId.values()];

  const deriveCompletedPlans = (): Set<string> => {
    const derivedCompletedPlans = new Set<string>();
    let changed = true;

    while (changed) {
      changed = false;

      for (const loaded of authoritativeLoadedSummaries) {
        if (
          derivedCompletedPlans.has(loaded.planId) ||
          !loaded.completedEvidence ||
          !loaded.validation.valid ||
          !loaded.linkedPlan
        ) {
          continue;
        }

        if (
          loaded.dependencyPlanIds.every((dependencyPlanId) =>
            derivedCompletedPlans.has(dependencyPlanId)
          )
        ) {
          derivedCompletedPlans.add(loaded.planId);
          changed = true;
        }
      }
    }

    return derivedCompletedPlans;
  };

  completedPlans = deriveCompletedPlans();

  for (let attempt = 0; attempt < authoritativeLoadedSummaries.length + 1; attempt += 1) {
    for (const loaded of authoritativeLoadedSummaries) {
      const livePlanValidation = validateSummaryAgainstLivePlanInventory(loaded.content, {
        resolved,
        planId: loaded.planId,
        plan: loaded.linkedPlan,
        knownPlanIds,
        completedDependencyPlanIds: completedPlans,
        completedRouteValidation: { mode: "indexed" }
      });

      loaded.validation = {
        valid: loaded.strictValidation.valid && livePlanValidation.valid,
        issues: [...loaded.strictValidation.issues, ...livePlanValidation.issues],
        warnings: [...loaded.strictValidation.warnings, ...livePlanValidation.warnings]
      };
    }

    const nextCompletedPlans = deriveCompletedPlans();

    if (
      nextCompletedPlans.size === completedPlans.size &&
      [...nextCompletedPlans].every((planId) => completedPlans.has(planId))
    ) {
      completedPlans = nextCompletedPlans;
      break;
    }

    completedPlans = nextCompletedPlans;
  }

  for (const loaded of authoritativeLoadedSummaries) {
    if (loaded.validation.valid && loaded.completedEvidence) {
      if (!completedPlans.has(loaded.planId)) {
        warnings.push(
          `${loaded.path}: linked plan ${loaded.linkedPlan?.path ?? loaded.planId} depends on incomplete execution plan(s): ${loaded.dependencyPlanIds
            .filter((dependencyPlanId) => !completedPlans.has(dependencyPlanId))
            .join(", ")}, so this summary does not close execution coverage.`
        );
      } else if (loaded.legacyCompletedEvidence) {
        warnings.push(
          `${loaded.path}: legacy summary has no Status marker; treating it as completed execution evidence because the canonical plan link and semantic checks passed.`
        );
      }
    } else if (loaded.validation.valid && loaded.status) {
      warnings.push(
        `${loaded.path}: summary status is ${loaded.status}, so it remains pending execution debt.`
      );
    } else {
      warnings.push(
        `${loaded.path}: summary artifact is invalid and does not count as completed execution evidence.`
      );
      warnings.push(...loaded.validation.issues.map((issue) => `${loaded.path}: ${issue}`));
      warnings.push(...loaded.validation.warnings.map((warning) => `${loaded.path}: ${warning}`));
    }
  }

  const pendingPlans = planIndex.plans
    .map((plan) => plan.planId)
    .filter((planId) => !completedPlans.has(planId));

  return {
    summaryIndex: {
      phaseFound: true,
      phaseNumber: resolved.phaseNumber,
      phasePrefix: resolved.phasePrefix,
      phaseName: resolved.phaseName,
      phaseDir: resolved.phaseDir,
      summaries,
      completedPlans: [...completedPlans].sort(),
      pendingPlans,
      warnings
    },
    summariesByPlanId: authoritativeSummariesByPlanId
  };
}

export function phaseSummaryReadFromInventory(args: {
  resolved: ResolvedPhaseLocation;
  planId: string;
  inventory: PhaseSummaryInventory;
  validateSummaryAgainstLivePlanInventory: ValidateSummaryAgainstLivePlanInventory;
}): PhaseSummaryReadResult {
  const { resolved, planId, inventory, validateSummaryAgainstLivePlanInventory } = args;
  const pathValue = summaryPathFor(resolved, planId);
  const loaded = inventory.summariesByPlanId.get(planId);

  if (!loaded) {
    return {
      phaseFound: true,
      found: false,
      phaseNumber: resolved.phaseNumber,
      phasePrefix: resolved.phasePrefix,
      phaseName: resolved.phaseName,
      phaseDir: resolved.phaseDir,
      planId,
      path: pathValue,
      content: null,
      metadata: null,
      validation: null,
      reason: `${pathValue} does not exist yet.`
    };
  }

  const strictValidation = validateStrictSummaryArtifactContent(loaded.content, {
    linkedPlanPath: planPathFor(resolved, planId),
    requirePlanMarker: true
  });
  const knownPlanIds = new Set(
    [
      ...inventory.summaryIndex.completedPlans,
      ...inventory.summaryIndex.pendingPlans
    ].sort()
  );
  const livePlanValidation = validateSummaryAgainstLivePlanInventory(loaded.content, {
    resolved,
    planId,
    plan: loaded.linkedPlan,
    knownPlanIds,
    completedDependencyPlanIds: new Set(inventory.summaryIndex.completedPlans),
    completedRouteValidation: { mode: "indexed" }
  });
  const validation = {
    valid: strictValidation.valid && livePlanValidation.valid,
    issues: [...strictValidation.issues, ...livePlanValidation.issues],
    warnings: [...strictValidation.warnings, ...livePlanValidation.warnings]
  };

  return {
    phaseFound: true,
    found: true,
    phaseNumber: resolved.phaseNumber,
    phasePrefix: resolved.phasePrefix,
    phaseName: resolved.phaseName,
    phaseDir: resolved.phaseDir,
    planId,
    path: pathValue,
    content: loaded.content,
    metadata: {
      linkedPlanPath: loaded.record.linkedPlanPath,
      status: loaded.record.status,
      title: loaded.record.title,
      summary: loaded.record.summary
    },
    validation,
    reason: null
  };
}

export async function loadResolvedPhaseSummaryContext(args: {
  projectRoot: string;
  located: PhaseLocateResult;
  resolved: ResolvedPhaseLocation;
  buildPhasePlanIndexFromLocated: (args: {
    projectRoot: string;
    located: PhaseLocateResult;
    resolved: ResolvedPhaseLocation;
  }) => Promise<PhasePlanIndexResult>;
  validateSummaryAgainstLivePlanInventory: ValidateSummaryAgainstLivePlanInventory;
}): Promise<{
  planIndex: PhasePlanIndexResult;
  summaryInventory: PhaseSummaryInventory;
}> {
  const planIndex = await args.buildPhasePlanIndexFromLocated(args);
  const summaryInventory = await loadPhaseSummaryInventory({
    ...args,
    planIndex
  });

  return {
    planIndex,
    summaryInventory
  };
}

export function isLegacySummaryWithoutStatus(content: string): boolean {
  return extractSummaryMarkerValue(content, "Status") === null;
}

export function summaryCountsAsCompleted(
  status: PhaseSummaryRecord["status"],
  content: string
): boolean {
  return status === "COMPLETED" || (status === null && isLegacySummaryWithoutStatus(content));
}

export async function collectValidatedSummaryPaths(
  projectRoot: string,
  summaries: PhaseSummaryRecord[]
): Promise<{
  summaryPaths: string[];
  warnings: string[];
}> {
  const summaryPaths: string[] = [];
  const warnings: string[] = [];

  for (const summary of summaries) {
    const content = await fs.readFile(resolveBlueprintPath(projectRoot, summary.path), "utf8");
    const validation = validateStrictSummaryArtifactContent(content, {
      linkedPlanPath: summary.linkedPlanPath
    });

    if (validation.valid) {
      summaryPaths.push(summary.path);
      continue;
    }

    warnings.push(
      `${summary.path}: summary artifact is invalid and does not count as completed execution evidence.`
    );
    warnings.push(...validation.issues.map((issue) => `${summary.path}: ${issue}`));
    warnings.push(...validation.warnings.map((warning) => `${summary.path}: ${warning}`));
  }

  return { summaryPaths, warnings };
}

export function completedSummaryRecords(
  summaries: PhaseSummaryRecord[],
  completedPlanIds?: ReadonlySet<string>
): PhaseSummaryRecord[] {
  return summaries.filter(
    (summary) =>
      (completedPlanIds === undefined || completedPlanIds.has(summary.planId))
  );
}

export function collectReferencedValidatedSummaryPaths(
  content: string,
  summaries: PhaseSummaryRecord[],
  completedPlans: ReadonlySet<string>
): string[] {
  const references = new Map<string, number>();

  for (const summary of summaries) {
    if (!completedPlans.has(summary.planId)) {
      continue;
    }

    const fileName = summary.path.split("/").pop() ?? summary.path;
    const firstMatch = [summary.path, fileName]
      .map((candidate) => content.indexOf(candidate))
      .filter((index) => index >= 0)
      .sort((left, right) => left - right)[0];

    if (firstMatch === undefined) {
      continue;
    }

    references.set(summary.path, firstMatch);
  }

  return [...references.entries()]
    .sort((left, right) => left[1] - right[1] || left[0].localeCompare(right[0]))
    .map(([summaryPath]) => summaryPath);
}

export async function buildPhaseSummaryAllowedNextActions(phaseNumber: string): Promise<{
  readyAction: string;
  partialAction: string;
  blockedAction: string;
  allowedActions: string[];
}> {
  const readyAction = `/blu-validate-phase ${phaseNumber}`;
  const partialAction = `/blu-execute-phase ${phaseNumber}`;
  const blockedAction = "/blu-progress";
  const fallback = [readyAction, partialAction, blockedAction];
  const implementedCommands = await getPhasePlanImplementedCommandNames();

  if (implementedCommands === null || implementedCommands.size === 0) {
    return {
      readyAction,
      partialAction,
      blockedAction,
      allowedActions: fallback
    };
  }

  const implemented = filterImplementedBlueprintActions(fallback, implementedCommands);

  return {
    readyAction: implemented.includes(readyAction) ? readyAction : readyAction,
    partialAction: implemented.includes(partialAction) ? partialAction : partialAction,
    blockedAction: implemented.includes(blockedAction) ? blockedAction : blockedAction,
    allowedActions: implemented.length > 0 ? implemented : fallback
  };
}
