export function summarizeSavedArtifact(raw: string): { title: string; summary: string } {
  const normalizedLines = raw
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.trim());
  const withoutFrontmatter = [...normalizedLines];

  if (withoutFrontmatter[0] === "---") {
    withoutFrontmatter.shift();

    while (withoutFrontmatter.length > 0 && withoutFrontmatter[0] !== "---") {
      withoutFrontmatter.shift();
    }

    if (withoutFrontmatter[0] === "---") {
      withoutFrontmatter.shift();
    }
  }

  const meaningfulLines = withoutFrontmatter.filter(
    (line) => line.length > 0 && !line.startsWith("*Generated by")
  );
  const heading = meaningfulLines.find((line) => line.startsWith("#"));
  const bodyLine = meaningfulLines.find((line) => !line.startsWith("#"));

  return {
    title: heading?.replace(/^#+\s*/, "").trim() ?? "Artifact Summary",
    summary: bodyLine ?? "Artifact content is present and available for review."
  };
}

export function extractMarkdownSection(markdown: string, heading: string): string {
  const escapedHeading = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = markdown.match(
    new RegExp(`(?:^|\\n)## ${escapedHeading}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`)
  );

  return match?.[1]?.trim() ?? "";
}

export function extractMarkdownHeading(markdown: string): string | null {
  return markdown.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? null;
}

export function normalizeMarkdownListItems(section: string): string[] {
  return section
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => line.replace(/^[-*+]\s+/, "").trim())
    .filter((line) => line.length > 0);
}

export function sectionToList(section: string): string[] {
  const lines = normalizeMarkdownListItems(section);
  const bulletLines = lines.filter((line) => !/^[A-Za-z0-9_.-]+\s*:\s*/.test(line));

  return bulletLines.length > 0 ? bulletLines : lines;
}

export function summarizeContextPieces(pieces: string[], emptyMessage: string): string {
  const meaningfulPieces = pieces
    .map((piece) => piece.trim())
    .filter((piece) => piece.length > 0);

  return meaningfulPieces.length > 0 ? meaningfulPieces.join(" | ") : emptyMessage;
}

export function markdownCell(value: unknown): string {
  return markdownTableCell(String(value ?? ""));
}

export function markdownTableCell(value: string): string {
  return value.replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();
}
