import test from "node:test";
import assert from "node:assert/strict";

import {
  artifactContractIds,
  listArtifactContracts,
  readArtifactContract
} from "../src/mcp/artifact-contracts/index.js";
import { blueprintToolNames } from "../src/mcp/server.js";
import {
  blueprintArtifactContractRead,
  validateReportArtifactContent,
  validateResearchArtifactContent,
  validateReviewArtifactContent,
  validateUatArtifactContent,
  validateVerificationArtifactContent
} from "../src/mcp/tools/artifacts.js";

function canonicalResearchContent(summary: string, requirementRows: string): string {
  return `# Phase 03: Discovery - Research

**Researched:** 2026-04-18
**Domain:** blueprint contracts
**Confidence:** HIGH

## Phase Requirements

| ID | Description | Research Support |
|----|-------------|------------------|
${requirementRows}

## Summary

- ${summary}

## Locked Decisions From Context

- Keep the phase research contract MCP-owned and planner-facing.

## User Constraints

- Keep commands thin and MCP-owned.

## Standard Stack

- TypeScript, MCP tools, markdown artifacts.

## Installation And Setup

- Build the repo and validate fixtures through the standard test harness.

## Alternatives Considered

- Prompt-local templates were rejected because they drift from the MCP contract.

## Architecture Patterns

- Runtime-owned contract registry with read-only access.

## Don't Hand-Roll

- Avoid copying templates into command prompts.

## Anti-Patterns

- Treating scaffold-shaped output as sufficient research evidence.

## State Of The Art

- Template-driven drafting keeps the agent aligned with the live runtime contract.

## Common Pitfalls

- Drift between docs, skills, and validators.

## Open Questions

- Should critical external claims eventually require multi-source support?

## Confidence Breakdown

| Topic | Confidence | Why |
|-------|------------|-----|
| Contract parity | HIGH | The canonical contract is enforced by runtime code and test fixtures. |

## Code Examples

\`\`\`text
Read the contract, then normalize before writing.
\`\`\`

## Recommendations

- Fetch the canonical contract before persistence.

## Sources

- \`src/mcp/artifact-contracts/index.ts\` - canonical registry implementation.

## Additional Context

- Extra top-level notes stay allowed when the contract policy says so.
`;
}

test("artifact contract registry exposes canonical contract ids and templates", async () => {
  assert.ok(blueprintToolNames.includes("blueprint_artifact_contract_read"));
  assert.ok(artifactContractIds.includes("phase.research"));
  assert.ok(artifactContractIds.includes("phase.verification"));
  assert.ok(artifactContractIds.includes("review.code-review"));
  assert.ok(artifactContractIds.includes("report.pause-work"));

  const single = await blueprintArtifactContractRead({ artifactId: "phase.research" });
  const listed = await blueprintArtifactContractRead({});
  const researchContract = readArtifactContract("phase.research");
  const uiContract = readArtifactContract("phase.ui-spec");
  const pauseContract = readArtifactContract("report.pause-work");
  const reviewContract = readArtifactContract("review.code-review");
  const securityContract = readArtifactContract("review.security");
  const verificationContract = readArtifactContract("phase.verification");
  const uatContract = readArtifactContract("phase.uat");

  assert.equal(single.artifactId, "phase.research");
  assert.match(single.contract.authoringTemplate, /^# Phase XX: <Phase Name> - Research$/m);
  assert.match(single.contract.scaffoldTemplate, /\*Generated by `blueprint_artifact_scaffold`\*/);
  assert.deepEqual(researchContract.requiredHeadings, [
    "Phase Requirements",
    "Summary",
    "Locked Decisions From Context",
    "User Constraints",
    "Standard Stack",
    "Installation And Setup",
    "Alternatives Considered",
    "Architecture Patterns",
    "Don't Hand-Roll",
    "Anti-Patterns",
    "State Of The Art",
    "Common Pitfalls",
    "Open Questions",
    "Confidence Breakdown",
    "Code Examples",
    "Recommendations",
    "Sources"
  ]);
  assert.ok(Array.isArray(listed.contracts));
  assert.ok(listed.contracts.length >= 10);
  assert.deepEqual(uiContract.requiredHeadings, [
    "Outcome Mode",
    "User Experience Goals",
    "Visual Design Decisions",
    "Screens And States",
    "Components And Constraints",
    "Accessibility And Content",
    "Registry And Design-System Safety",
    "Next Safe Action"
  ]);
  assert.match(uiContract.authoringTemplate, /Spacing and layout:/);
  assert.match(uiContract.authoringTemplate, /Typography:/);
  assert.match(uiContract.authoringTemplate, /Color and contrast:/);
  assert.match(uiContract.authoringTemplate, /Copy and content:/);
  assert.match(uiContract.authoringTemplate, /## Rationale/);
  assert.match(uiContract.authoringTemplate, /Registry and design-system safety:/);
  assert.match(uiContract.notes.join("\n"), /spacing, typography, color, copy\/content/i);
  assert.match(uiContract.notes.join("\n"), /optional `## Rationale` branch/i);
  assert.ok(
    uiContract.placeholderSignals.includes(
      "Spacing and layout: <grid, rhythm, or layout constraints>"
    )
  );
  assert.ok(
    uiContract.placeholderSignals.includes(
      "Typography: <type scale, emphasis, or readability decisions>"
    )
  );
  assert.ok(
    uiContract.placeholderSignals.includes(
      "Registry and design-system safety: <how the draft avoids forking the registry or design system>"
    )
  );
  assert.deepEqual(verificationContract.requiredHeadings, [
    "Validation Summary",
    "Requirement / Task Coverage",
    "Evidence Reviewed",
    "Test Infrastructure / Evidence Metadata",
    "Manual-Only or Deferred Coverage",
    "Gate State",
    "Gap Classification",
    "Gaps Found",
    "Suggested Repairs",
    "Next Safe Action"
  ]);
  assert.match(
    verificationContract.authoringTemplate,
    /## Requirement \/ Task Coverage/
  );
  assert.match(
    verificationContract.authoringTemplate,
    /## Test Infrastructure \/ Evidence Metadata/
  );
  assert.match(
    verificationContract.authoringTemplate,
    /## Manual-Only or Deferred Coverage/
  );
  assert.match(verificationContract.authoringTemplate, /## Gate State/);
  assert.match(
    verificationContract.authoringTemplate,
    /## Gap Classification/
  );
  assert.match(verificationContract.authoringTemplate, /\*\*Gate State:\*\*/);
  assert.match(verificationContract.authoringTemplate, /\*\*Sign-off:\*\*/);
  assert.deepEqual(verificationContract.lockedMarkers, [
    "**Coverage:**",
    "**Gate State:**",
    "**Sign-off:**"
  ]);
  assert.deepEqual(uatContract.requiredHeadings, [
    "UAT Summary",
    "Session State",
    "Questions Asked",
    "Observed Behavior",
    "Unresolved Gaps",
    "Follow-Up Fixes",
    "Next Safe Action"
  ]);
  assert.deepEqual(uatContract.lockedMarkers, [
    "**Status:**",
    "**Resume State:**",
    "**Checkpoint:**"
  ]);
  assert.match(uatContract.authoringTemplate, /\*\*Resume State:\*\* RESUMED\|NEW\|CONTINUED/);
  assert.match(uatContract.authoringTemplate, /\*\*Checkpoint:\*\* <saved checkpoint path or none>/);
  assert.match(uatContract.authoringTemplate, /## Session State/);
  assert.match(
    uatContract.authoringTemplate,
    /Resume source: <saved summary path, checkpoint, or none>/
  );
  assert.match(
    uatContract.authoringTemplate,
    /Continuity notes: <what must remain stable between sessions>/
  );
  assert.match(uatContract.notes.join("\n"), /resumable across sessions/i);
  assert.match(
    uatContract.notes.join("\n"),
    /saved summaries inside UAT Summary, Session State, or Observed Behavior/i
  );
  assert.deepEqual(reviewContract.requiredHeadings, [
    "Review Summary",
    "Scope Reviewed",
    "Evidence Reviewed",
    "Positive Signals",
    "Severity Summary",
    "Findings",
    "Follow-Ups",
    "Next Safe Action"
  ]);
  assert.deepEqual(securityContract.requiredHeadings, [
    "Security Summary",
    "Evidence Reviewed",
    "Threat Register",
    "Accepted Risks",
    "Findings",
    "Follow-Ups",
    "Security Audit Trail",
    "Next Safe Action"
  ]);
  assert.match(reviewContract.authoringTemplate, /\*\*Verdict:\*\* PASS\|FOLLOW_UP\|BLOCKED/);
  assert.match(reviewContract.authoringTemplate, /## Review Summary/);
  assert.match(reviewContract.authoringTemplate, /## Evidence Reviewed/);
  assert.match(reviewContract.authoringTemplate, /## Positive Signals/);
  assert.match(reviewContract.authoringTemplate, /## Severity Summary/);
  assert.match(securityContract.authoringTemplate, /\*\*Posture:\*\* PASS\|FOLLOW_UP\|BLOCKED/);
  assert.match(securityContract.authoringTemplate, /## Threat Register/);
  assert.match(securityContract.authoringTemplate, /## Accepted Risks/);
  assert.match(securityContract.authoringTemplate, /## Security Audit Trail/);
  assert.deepEqual(
    pauseContract.requiredHeadings,
    [
      "Current State",
      "Completed Work",
      "Remaining Work",
      "Decisions",
      "Blockers",
      "Human Actions Pending",
      "Modified Files",
      "Blueprint Snapshot",
      "Next Action",
      "Context Notes"
    ]
  );
});

test("canonical lifecycle contracts allow additional top-level headings without breaking validation", () => {
  const research = canonicalResearchContent(
    "One registry reduces retry loops.",
    "| R-1 | Centralize templates | Use one MCP-owned registry for authoring and validation. |\n"
  );
  const verification = `# Phase 03: Discovery - Verification

**Coverage:** Reviewed \`03-01-SUMMARY.md\` and related saved summaries.
**Gate State:** PASS
**Sign-off:** validation lead

## Validation Summary

- Validation coverage is sufficient for UAT.

## Requirement / Task Coverage

| Requirement | Task or Check | Evidence | Coverage State | Notes |
|-------------|---------------|----------|----------------|-------|
| VALID-01 | Confirm saved execution summaries exist | .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md | PASS | Summary-backed coverage is present. |

## Evidence Reviewed

- .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md

## Test Infrastructure / Evidence Metadata

- Harness: node:test
- Commands: npm test
- Evidence type: saved execution summary
- Test infrastructure status: available

## Manual-Only or Deferred Coverage

| Item | Why manual or deferred | Follow-Up | Status |
|------|------------------------|-----------|--------|
| none | none | none | NONE |

## Gate State

- Gate: PASS
- Sign-off: validation lead
- Readiness: ready for UAT

## Gap Classification

| Gap class | Scope | Evidence | Repair |
|-----------|-------|----------|--------|
| none | none | .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md | none |

## Gaps Found

- none

## Suggested Repairs

- none

## Next Safe Action

- /blu-verify-work 3

## Additional Context

- Extra validator notes are allowed here.
`;
  const uat = `# Phase 03: Discovery - UAT

**Status:** PASS
**Resume State:** RESUMED
**Checkpoint:** none

## UAT Summary

- The saved behavior matched the accepted summary evidence.

## Session State

- Resume source: saved summary evidence
- Current session step: Confirm the accepted behavior still holds after a pause.
- Continuity notes: Keep the same summary-backed outcome when the session resumes.

## Questions Asked

- none

## Observed Behavior

- The observed behavior matched .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md.

## Unresolved Gaps

- none

## Follow-Up Fixes

- none

## Next Safe Action

- /blu-progress

## Additional Context

- Extra UAT notes remain valid.
`;

  const researchValidation = validateResearchArtifactContent(research);
  const verificationValidation = validateVerificationArtifactContent(verification, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);
  const uatValidation = validateUatArtifactContent(uat, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);
  const invalidCheckpointUat = uat.replace("**Checkpoint:** none", "**Checkpoint:** pending");
  const invalidCheckpointValidation = validateUatArtifactContent(invalidCheckpointUat, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);

  assert.equal(researchValidation.valid, true, researchValidation.issues.join("\n"));
  assert.equal(verificationValidation.valid, true, verificationValidation.issues.join("\n"));
  assert.equal(uatValidation.valid, true, uatValidation.issues.join("\n"));
  assert.equal(invalidCheckpointValidation.valid, false, invalidCheckpointValidation.issues.join("\n"));
  assert.match(
    invalidCheckpointValidation.issues.join("\n"),
    /saved checkpoint path ending in `-DISCUSS-CHECKPOINT\.json` or `none`|`none` or a saved checkpoint path ending in `-DISCUSS-CHECKPOINT\.json`/
  );
});

test("research contract rejects skeleton content that lacks substantive section detail", () => {
  const skeletalResearch = canonicalResearchContent("Keep registry updates aligned with MCP.", "");

  const validation = validateResearchArtifactContent(skeletalResearch);

  assert.equal(validation.valid, false, validation.issues.join("\n"));
  assert.match(
    validation.issues.join("\n"),
    /Phase Requirements must include at least one populated requirement row|substantive content/i
  );
});

test("review and report contracts validate canonical sections while keeping extra headings compatible", () => {
  const review = `# Phase 05: Security - Code Review

**Verdict:** FOLLOW_UP

## Review Summary

- Severity summary: critical 0, high 1, medium 0, low 0, unknown 0.

## Scope Reviewed

- src/mcp/tools/review.ts

## Evidence Reviewed

- .blueprint/phases/05-review-scope/05-01-PLAN.md
- .blueprint/phases/05-review-scope/05-01-SUMMARY.md

## Positive Signals

- Review scope stayed bounded to the saved plan outputs.

## Severity Summary

- critical: 0
- high: 1
- medium: 0
- low: 0
- unknown: 0

## Findings

- [high] Missing contract validation would let malformed review artifacts persist.

## Follow-Ups

- Add canonical review validation before persistence.

## Next Safe Action

- /blu-progress

## Additional Context

- Extra reviewer notes are allowed.
`;
  const thinReview = `# Phase 05: Security - Code Review

**Verdict:** FOLLOW_UP

## Scope Reviewed

- src/mcp/tools/review.ts

## Findings

- [high] Missing contract validation would let malformed review artifacts persist.

## Follow-Ups

- Add canonical review validation before persistence.

## Next Safe Action

- /blu-progress
`;
  const securityContract = readArtifactContract("review.security");
  const securityScaffoldValidation = validateReviewArtifactContent(
    securityContract.authoringTemplate,
    "security"
  );
  const thinSecurityReview = `# Phase 05: Security - Security Review

**Posture:** PASS

## Security Summary

- Saved evidence looks stable.

## Evidence Reviewed

- .blueprint/phases/05-review-scope/05-01-SUMMARY.md

## Findings

- none

## Follow-Ups

- none

## Next Safe Action

- /blu-progress
`;
  const thinSecurityValidation = validateReviewArtifactContent(thinSecurityReview, "security");
  const report = `# Debug Report

## Problem Statement

- Validation drift caused repeated MCP write retries.

## Evidence Collected

- Saved artifacts and repeated invalid write outcomes.

## Hypotheses

- Commands were drafting against stale inline templates.

## Actions Taken

- Introduced a canonical contract registry.

## Next Safe Action

- /blu-progress

## Additional Context

- Extra operational notes are allowed.
`;
  const thinAuditFixReport = `# Audit Fix Report: Phase 04

## Evidence Used

- .blueprint/phases/04-release-readiness/04-01-SUMMARY.md
`;
  const customReport = `# Team Notes

- Non-contract report payloads stay permissive.
`;
  const reviewValidation = validateReviewArtifactContent(review, "code-review");
  const thinReviewValidation = validateReviewArtifactContent(thinReview, "code-review");
  assert.match(
    securityContract.authoringTemplate,
    /\*\*Posture:\*\* PASS\|FOLLOW_UP\|BLOCKED/
  );
  assert.equal(securityScaffoldValidation.valid, false);
  assert.match(securityScaffoldValidation.issues.join("\n"), /placeholder scaffold text/i);
  assert.equal(thinSecurityValidation.valid, false);
  assert.match(thinSecurityValidation.issues.join("\n"), /Threat Register/);
  assert.match(thinSecurityValidation.issues.join("\n"), /Accepted Risks/);
  assert.match(thinSecurityValidation.issues.join("\n"), /Security Audit Trail/);
  const reportValidation = validateReportArtifactContent(report, "debug-latest");
  const thinAuditFixValidation = validateReportArtifactContent(thinAuditFixReport, "audit-fix-04");
  const customReportValidation = validateReportArtifactContent(customReport, "custom-team-notes");

  assert.equal(reviewValidation.valid, true, reviewValidation.issues.join("\n"));
  assert.equal(thinReviewValidation.valid, false);
  assert.match(thinReviewValidation.issues.join("\n"), /Review Summary/);
  assert.match(thinReviewValidation.issues.join("\n"), /Evidence Reviewed/);
  assert.match(thinReviewValidation.issues.join("\n"), /Positive Signals/);
  assert.match(thinReviewValidation.issues.join("\n"), /Severity Summary/);
  assert.equal(reportValidation.valid, true, reportValidation.issues.join("\n"));
  assert.equal(thinAuditFixValidation.valid, false);
  assert.match(thinAuditFixValidation.issues.join("\n"), /Fix Scope/);
  assert.match(thinAuditFixValidation.issues.join("\n"), /Changes Applied/);
  assert.match(thinAuditFixValidation.issues.join("\n"), /Remaining Gaps/);
  assert.match(thinAuditFixValidation.issues.join("\n"), /Next Safe Action/);
  assert.equal(customReportValidation.valid, true, customReportValidation.issues.join("\n"));
});

test("contract registry remains listable through the direct helper", () => {
  const contracts = listArtifactContracts();

  assert.ok(contracts.some((contract) => contract.id === "phase.research"));
  assert.ok(contracts.some((contract) => contract.id === "review.security"));
  assert.ok(contracts.some((contract) => contract.id === "report.debug"));
});
