import test from "node:test";
import assert from "node:assert/strict";

import {
  artifactContractIds,
  listArtifactContracts,
  readArtifactContract
} from "../src/mcp/artifact-contracts/index.js";
import { blueprintToolNames } from "../src/mcp/server.js";
import {
  blueprintArtifactContractRead,
  validateReportArtifactContent,
  validateResearchArtifactContent,
  validateReviewArtifactContent,
  validateUatArtifactContent,
  validateVerificationArtifactContent
} from "../src/mcp/tools/artifacts.js";

test("artifact contract registry exposes canonical contract ids and templates", async () => {
  assert.ok(blueprintToolNames.includes("blueprint_artifact_contract_read"));
  assert.ok(artifactContractIds.includes("phase.research"));
  assert.ok(artifactContractIds.includes("phase.verification"));
  assert.ok(artifactContractIds.includes("review.code-review"));
  assert.ok(artifactContractIds.includes("report.pause-work"));

  const single = await blueprintArtifactContractRead({ artifactId: "phase.research" });
  const listed = await blueprintArtifactContractRead({});
  const pauseContract = readArtifactContract("report.pause-work");

  assert.equal(single.artifactId, "phase.research");
  assert.match(single.contract.authoringTemplate, /^# Phase XX: <Phase Name> - Research$/m);
  assert.match(single.contract.scaffoldTemplate, /\*Generated by `blueprint_artifact_scaffold`\*/);
  assert.ok(Array.isArray(listed.contracts));
  assert.ok(listed.contracts.length >= 10);
  assert.deepEqual(
    pauseContract.requiredHeadings,
    [
      "Current State",
      "Completed Work",
      "Remaining Work",
      "Decisions",
      "Blockers",
      "Human Actions Pending",
      "Modified Files",
      "Blueprint Snapshot",
      "Next Action",
      "Context Notes"
    ]
  );
});

test("canonical lifecycle contracts allow additional top-level headings without breaking validation", () => {
  const research = `# Phase 03: Discovery - Research

**Researched:** 2026-04-18
**Domain:** blueprint contracts
**Confidence:** HIGH

## Phase Requirements

| ID | Description | Research Support |
|----|-------------|------------------|
| R-1 | Centralize templates | Use one MCP-owned registry for authoring and validation. |

## Summary

- One registry reduces retry loops.

## User Constraints

- Keep commands thin and MCP-owned.

## Standard Stack

- TypeScript, MCP tools, markdown artifacts.

## Architecture Patterns

- Runtime-owned contract registry with read-only access.

## Don't Hand-Roll

- Avoid copying templates into command prompts.

## Common Pitfalls

- Drift between docs, skills, and validators.

## Code Examples

\`\`\`text
Read the contract, then normalize before writing.
\`\`\`

## Recommendations

- Fetch the canonical contract before persistence.

## Sources

- \`src/mcp/artifact-contracts/index.ts\` - canonical registry implementation.

## Additional Context

- Extra top-level notes stay allowed when the contract policy says so.
`;
  const verification = `# Phase 03: Discovery - Verification

**Coverage:** Reviewed \`03-01-SUMMARY.md\` and related saved summaries.

## Validation Summary

- Validation coverage is sufficient for UAT.

## Evidence Reviewed

- .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md

## Gaps Found

- none

## Suggested Repairs

- none

## Next Safe Action

- /blu-verify-work 3

## Additional Context

- Extra validator notes are allowed here.
`;
  const uat = `# Phase 03: Discovery - UAT

**Status:** PASS

## UAT Summary

- The saved behavior matched \`03-01-SUMMARY.md\`.

## Questions Asked

- none

## Observed Behavior

- The observed behavior matched .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md.

## Unresolved Gaps

- none

## Follow-Up Fixes

- none

## Next Safe Action

- /blu-progress

## Additional Context

- Extra UAT notes remain valid.
`;

  const researchValidation = validateResearchArtifactContent(research);
  const verificationValidation = validateVerificationArtifactContent(verification, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);
  const uatValidation = validateUatArtifactContent(uat, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);

  assert.equal(researchValidation.valid, true, researchValidation.issues.join("\n"));
  assert.equal(verificationValidation.valid, true, verificationValidation.issues.join("\n"));
  assert.equal(uatValidation.valid, true, uatValidation.issues.join("\n"));
});

test("review and report contracts validate canonical sections while keeping extra headings compatible", () => {
  const review = `# Phase 05: Security - Code Review

**Verdict:** FOLLOW_UP

## Scope Reviewed

- src/mcp/tools/review.ts

## Findings

- [high] Missing contract validation would let malformed review artifacts persist.

## Follow-Ups

- Add canonical review validation before persistence.

## Next Safe Action

- /blu-progress

## Additional Context

- Extra reviewer notes are allowed.
`;
  const report = `# Debug Report

## Problem Statement

- Validation drift caused repeated MCP write retries.

## Evidence Collected

- Saved artifacts and repeated invalid write outcomes.

## Hypotheses

- Commands were drafting against stale inline templates.

## Actions Taken

- Introduced a canonical contract registry.

## Next Safe Action

- /blu-progress

## Additional Context

- Extra operational notes are allowed.
`;

  const reviewValidation = validateReviewArtifactContent(review, "code-review");
  const reportValidation = validateReportArtifactContent(report, "debug-latest");

  assert.equal(reviewValidation.valid, true, reviewValidation.issues.join("\n"));
  assert.equal(reportValidation.valid, true, reportValidation.issues.join("\n"));
});

test("contract registry remains listable through the direct helper", () => {
  const contracts = listArtifactContracts();

  assert.ok(contracts.some((contract) => contract.id === "phase.research"));
  assert.ok(contracts.some((contract) => contract.id === "review.security"));
  assert.ok(contracts.some((contract) => contract.id === "report.debug"));
});
