import test from "node:test";
import assert from "node:assert/strict";

import {
  artifactContractIds,
  listArtifactContracts,
  readArtifactContract
} from "../src/mcp/artifact-contracts/index.js";
import { blueprintToolNames } from "../src/mcp/server.js";
import {
  blueprintArtifactContractRead,
  validateReportArtifactContent,
  validateResearchArtifactContent,
  validateReviewArtifactContent,
  validateUatArtifactContent,
  validateVerificationArtifactContent
} from "../src/mcp/tools/artifacts.js";

function canonicalResearchContent(summary: string, requirementRows: string): string {
  return `# Phase 03: Discovery - Research

**Researched:** 2026-04-18
**Domain:** blueprint contracts
**Confidence:** HIGH

## Phase Requirements

| ID | Description | Research Support |
|----|-------------|------------------|
${requirementRows}

## Summary

- ${summary}

## Locked Decisions From Context

- Keep the phase research contract MCP-owned and planner-facing.

## User Constraints

- Keep commands thin and MCP-owned.

## Standard Stack

- TypeScript, MCP tools, markdown artifacts.

## Installation And Setup

- Build the repo and validate fixtures through the standard test harness.

## Alternatives Considered

- Prompt-local templates were rejected because they drift from the MCP contract.

## Architecture Patterns

- Runtime-owned contract registry with read-only access.

## Don't Hand-Roll

- Avoid copying templates into command prompts.

## Anti-Patterns

- Treating scaffold-shaped output as sufficient research evidence.

## State Of The Art

- Template-driven drafting keeps the agent aligned with the live runtime contract.

## Common Pitfalls

- Drift between docs, skills, and validators.

## Open Questions

- Should critical external claims eventually require multi-source support?

## Confidence Breakdown

| Topic | Confidence | Why |
|-------|------------|-----|
| Contract parity | HIGH | The canonical contract is enforced by runtime code and test fixtures. |

## Code Examples

\`\`\`text
Read the contract, then normalize before writing.
\`\`\`

## Recommendations

- Fetch the canonical contract before persistence.

## Sources

- \`src/mcp/artifact-contracts/index.ts\` - canonical registry implementation.

## Additional Context

- Extra top-level notes stay allowed when the contract policy says so.
`;
}

test("artifact contract registry exposes canonical contract ids and templates", async () => {
  assert.ok(blueprintToolNames.includes("blueprint_artifact_contract_read"));
  assert.ok(artifactContractIds.includes("bootstrap.project"));
  assert.ok(artifactContractIds.includes("bootstrap.requirements"));
  assert.ok(artifactContractIds.includes("bootstrap.roadmap"));
  assert.ok(artifactContractIds.includes("phase.research"));
  assert.ok(artifactContractIds.includes("phase.verification"));
  assert.ok(artifactContractIds.includes("review.code-review"));
  assert.ok(artifactContractIds.includes("report.pause-work"));

  const single = await blueprintArtifactContractRead({ artifactId: "phase.research" });
  const listed = await blueprintArtifactContractRead({});
  const projectContract = readArtifactContract("bootstrap.project");
  const requirementsContract = readArtifactContract("bootstrap.requirements");
  const roadmapContract = readArtifactContract("bootstrap.roadmap");
  const researchContract = readArtifactContract("phase.research");
  const contextContract = readArtifactContract("phase.context");
  const uiContract = readArtifactContract("phase.ui-spec");
  const pauseContract = readArtifactContract("report.pause-work");
  const reviewContract = readArtifactContract("review.code-review");
  const securityContract = readArtifactContract("review.security");
  const verificationContract = readArtifactContract("phase.verification");
  const uatContract = readArtifactContract("phase.uat");
  const milestoneAuditContract = readArtifactContract("report.milestone-audit");
  const milestoneCompleteContract = readArtifactContract("report.milestone-complete");
  const milestoneSummaryContract = readArtifactContract("report.milestone-summary");

  assert.equal(single.artifactId, "phase.research");
  assert.match(single.contract.authoringTemplate, /^# Phase XX: <Phase Name> - Research$/m);
  assert.match(single.contract.scaffoldTemplate, /\*Generated by `blueprint_artifact_scaffold`\*/);
  assert.deepEqual(projectContract.requiredHeadings, [
    "Vision",
    "Audience",
    "Constraints",
    "Current Milestone",
    "Bootstrap Shape",
    "Scope Posture",
    "Non-Goals",
    "Assumptions"
  ]);
  assert.match(projectContract.authoringTemplate, /# <project name>/);
  assert.match(projectContract.authoringTemplate, /## Bootstrap Shape/);
  assert.deepEqual(requirementsContract.requiredHeadings, [
    "Requirements Table",
    "Scope Summary",
    "Committed V1 Scope",
    "Deferred Scope",
    "Out-of-Scope Cuts",
    "Traceability Notes",
    "Open Questions"
  ]);
  assert.match(requirementsContract.authoringTemplate, /## Requirements Table/);
  assert.match(requirementsContract.authoringTemplate, /## Traceability Notes/);
  assert.deepEqual(roadmapContract.requiredHeadings, [
    "Milestone",
    "Bootstrap Status",
    "Requirement Coverage",
    "Phases",
    "Notes"
  ]);
  assert.match(roadmapContract.authoringTemplate, /## Bootstrap Status/);
  assert.match(roadmapContract.authoringTemplate, /## Phases/);
  assert.deepEqual(researchContract.requiredHeadings, [
    "Phase Requirements",
    "Summary",
    "Locked Decisions From Context",
    "User Constraints",
    "Standard Stack",
    "Installation And Setup",
    "Alternatives Considered",
    "Architecture Patterns",
    "Don't Hand-Roll",
    "Anti-Patterns",
    "State Of The Art",
    "Common Pitfalls",
    "Open Questions",
    "Confidence Breakdown",
    "Code Examples",
    "Recommendations",
    "Sources"
  ]);
  assert.deepEqual(contextContract.requiredHeadings, [
    "Phase Boundary",
    "Discovery Grounding",
    "Implementation Decisions",
    "Specific Ideas",
    "Existing Code Insights",
    "Dependencies",
    "Open Questions",
    "Deferred Ideas",
    "Canonical References"
  ]);
  assert.match(contextContract.authoringTemplate, /## Discovery Grounding/);
  assert.match(contextContract.authoringTemplate, /Project brief:/);
  assert.match(contextContract.authoringTemplate, /Requirements grounding:/);
  assert.match(contextContract.authoringTemplate, /Workflow posture:/);
  assert.match(contextContract.authoringTemplate, /Confirmed decisions:/);
  assert.match(contextContract.authoringTemplate, /## Implementation Decisions/);
  assert.match(contextContract.authoringTemplate, /<implementation decision 1>/);
  assert.match(contextContract.authoringTemplate, /## Specific Ideas/);
  assert.match(contextContract.authoringTemplate, /<specific idea 1>/);
  assert.match(contextContract.authoringTemplate, /## Existing Code Insights/);
  assert.match(contextContract.authoringTemplate, /<existing code insight 1>/);
  assert.match(contextContract.authoringTemplate, /<prior phase artifacts>/);
  assert.match(contextContract.authoringTemplate, /<open question 1>/);
  assert.match(contextContract.authoringTemplate, /## Deferred Ideas/);
  assert.match(contextContract.authoringTemplate, /## Canonical References/);
  assert.ok(contextContract.placeholderSignals.includes("<implementation decision 1>"));
  assert.ok(contextContract.placeholderSignals.includes("<specific idea 1>"));
  assert.ok(contextContract.placeholderSignals.includes("<existing code insight 1>"));
  assert.ok(contextContract.placeholderSignals.includes("<prior phase artifacts>"));
  assert.ok(contextContract.placeholderSignals.includes("<open question 1>"));
  assert.ok(contextContract.placeholderSignals.includes("<deferred idea>"));
  assert.ok(contextContract.placeholderSignals.includes("<source 1>"));
  assert.match(contextContract.notes.join("\n"), /downstream planning/i);
  assert.ok(Array.isArray(listed.contracts));
  assert.ok(listed.contracts.length >= 10);
  assert.deepEqual(uiContract.requiredHeadings, [
    "Outcome Mode",
    "User Experience Goals",
    "Visual Design Decisions",
    "Screens And States",
    "Components And Constraints",
    "Accessibility And Content",
    "Registry And Design-System Safety",
    "Next Safe Action"
  ]);
  assert.match(uiContract.authoringTemplate, /Spacing and layout:/);
  assert.match(uiContract.authoringTemplate, /Typography:/);
  assert.match(uiContract.authoringTemplate, /Color and contrast:/);
  assert.match(uiContract.authoringTemplate, /Copy and content:/);
  assert.match(uiContract.authoringTemplate, /## Rationale/);
  assert.match(uiContract.authoringTemplate, /Registry and design-system safety:/);
  assert.match(uiContract.notes.join("\n"), /spacing, typography, color, copy\/content/i);
  assert.match(uiContract.notes.join("\n"), /optional `## Rationale` branch/i);
  assert.ok(
    uiContract.placeholderSignals.includes(
      "Spacing and layout: <grid, rhythm, or layout constraints>"
    )
  );
  assert.ok(
    uiContract.placeholderSignals.includes(
      "Typography: <type scale, emphasis, or readability decisions>"
    )
  );
  assert.ok(
    uiContract.placeholderSignals.includes(
      "Registry and design-system safety: <how the draft avoids forking the registry or design system>"
    )
  );
  assert.deepEqual(verificationContract.requiredHeadings, [
    "Validation Summary",
    "Requirement / Task Coverage",
    "Evidence Reviewed",
    "Test Infrastructure / Evidence Metadata",
    "Manual-Only or Deferred Coverage",
    "Gate State",
    "Gap Classification",
    "Gaps Found",
    "Suggested Repairs",
    "Next Safe Action"
  ]);
  assert.match(
    verificationContract.authoringTemplate,
    /## Requirement \/ Task Coverage/
  );
  assert.match(
    verificationContract.authoringTemplate,
    /## Test Infrastructure \/ Evidence Metadata/
  );
  assert.match(
    verificationContract.authoringTemplate,
    /## Manual-Only or Deferred Coverage/
  );
  assert.match(verificationContract.authoringTemplate, /## Gate State/);
  assert.match(
    verificationContract.authoringTemplate,
    /## Gap Classification/
  );
  assert.match(verificationContract.authoringTemplate, /\*\*Gate State:\*\*/);
  assert.match(verificationContract.authoringTemplate, /\*\*Sign-off:\*\*/);
  assert.deepEqual(verificationContract.lockedMarkers, [
    "**Coverage:**",
    "**Gate State:**",
    "**Sign-off:**"
  ]);
  assert.deepEqual(uatContract.requiredHeadings, [
    "UAT Summary",
    "Session State",
    "Questions Asked",
    "Observed Behavior",
    "Unresolved Gaps",
    "Follow-Up Fixes",
    "Next Safe Action"
  ]);
  assert.deepEqual(uatContract.lockedMarkers, [
    "**Status:**",
    "**Resume State:**",
    "**Checkpoint:**"
  ]);
  assert.deepEqual(milestoneAuditContract.requiredHeadings, [
    "Audit Verdict",
    "Milestone Evidence Dimensions",
    "Original Intent Snapshot",
    "Roadmap And Phase Evidence",
    "Requirement Gaps",
    "Integration Gaps",
    "Flow Gaps",
    "Optional Gaps",
    "Gaps Found",
    "Archival Blockers",
    "Next Safe Action"
  ]);
  assert.deepEqual(milestoneAuditContract.lockedMarkers, [
    "**Verdict:**",
    "**Evidence Dimensions:**"
  ]);
  assert.match(
    milestoneAuditContract.authoringTemplate,
    /\*\*Verdict:\*\* READY_TO_CLOSE\|FOLLOW_UP\|BLOCKED/
  );
  assert.match(milestoneAuditContract.authoringTemplate, /## Audit Verdict/);
  assert.match(milestoneAuditContract.authoringTemplate, /## Milestone Evidence Dimensions/);
  assert.match(milestoneAuditContract.authoringTemplate, /## Requirement Gaps/);
  assert.match(milestoneAuditContract.authoringTemplate, /## Integration Gaps/);
  assert.match(milestoneAuditContract.authoringTemplate, /## Flow Gaps/);
  assert.match(milestoneAuditContract.authoringTemplate, /## Optional Gaps/);
  assert.match(milestoneAuditContract.authoringTemplate, /\| Gap ID \| Surface \| Evidence \| Repair \|/);
  assert.match(
    milestoneAuditContract.notes.join("\n"),
    /concrete verdict and milestone-level evidence dimensions/i
  );
  assert.deepEqual(milestoneCompleteContract.requiredHeadings, [
    "Completion Decision",
    "Audit Report Used",
    "Milestone Evidence Ledger",
    "Residual Watch Items",
    "Next Safe Action"
  ]);
  assert.deepEqual(milestoneCompleteContract.lockedMarkers, [
    "**Decision:**",
    "**Audit Report Used:**",
    "**Evidence Ledger:**"
  ]);
  assert.match(milestoneCompleteContract.authoringTemplate, /## Milestone Evidence Ledger/);
  assert.match(milestoneCompleteContract.authoringTemplate, /\*\*Decision:\*\* READY_TO_CLOSE\|FOLLOW_UP\|BLOCKED/);
  assert.match(milestoneCompleteContract.authoringTemplate, /<saved milestone audit report path>/);
  assert.deepEqual(milestoneSummaryContract.requiredHeadings, [
    "Scope Summary",
    "Source Reports Used",
    "Milestone Evidence Ledger",
    "Shipped Outcomes",
    "Deferred Follow-Ups",
    "Recommended Carry-Forward Context",
    "Next Safe Action"
  ]);
  assert.deepEqual(milestoneSummaryContract.lockedMarkers, [
    "**Sources Reviewed:**",
    "**Evidence Ledger:**",
    "**Carry-Forward Context:**"
  ]);
  assert.match(milestoneSummaryContract.authoringTemplate, /## Milestone Evidence Ledger/);
  assert.match(
    milestoneSummaryContract.authoringTemplate,
    /<saved audit report, completion report, and roadmap evidence>/
  );
  assert.match(milestoneSummaryContract.authoringTemplate, /\/blu-new-milestone/);
  assert.match(uatContract.authoringTemplate, /\*\*Resume State:\*\* RESUMED\|NEW\|CONTINUED/);
  assert.match(uatContract.authoringTemplate, /\*\*Checkpoint:\*\* <saved checkpoint path or none>/);
  assert.match(uatContract.authoringTemplate, /## Session State/);
  assert.match(
    uatContract.authoringTemplate,
    /Resume source: <saved summary path, checkpoint, or none>/
  );
  assert.match(
    uatContract.authoringTemplate,
    /Continuity notes: <what must remain stable between sessions>/
  );
  assert.match(uatContract.notes.join("\n"), /resumable across sessions/i);
  assert.match(
    uatContract.notes.join("\n"),
    /saved summaries inside UAT Summary, Session State, or Observed Behavior/i
  );
  assert.deepEqual(reviewContract.requiredHeadings, [
    "Review Summary",
    "Scope Reviewed",
    "Evidence Reviewed",
    "Positive Signals",
    "Severity Summary",
    "Findings",
    "Follow-Ups",
    "Next Safe Action"
  ]);
  assert.deepEqual(securityContract.requiredHeadings, [
    "Security Summary",
    "Evidence Reviewed",
    "Threat Register",
    "Accepted Risks",
    "Findings",
    "Follow-Ups",
    "Security Audit Trail",
    "Next Safe Action"
  ]);
  assert.match(reviewContract.authoringTemplate, /\*\*Verdict:\*\* PASS\|FOLLOW_UP\|BLOCKED/);
  assert.match(reviewContract.authoringTemplate, /## Review Summary/);
  assert.match(reviewContract.authoringTemplate, /## Evidence Reviewed/);
  assert.match(reviewContract.authoringTemplate, /## Positive Signals/);
  assert.match(reviewContract.authoringTemplate, /## Severity Summary/);
  assert.match(securityContract.authoringTemplate, /\*\*Posture:\*\* PASS\|FOLLOW_UP\|BLOCKED/);
  assert.match(securityContract.authoringTemplate, /## Threat Register/);
  assert.match(securityContract.authoringTemplate, /## Accepted Risks/);
  assert.match(securityContract.authoringTemplate, /## Security Audit Trail/);
  assert.deepEqual(
    pauseContract.requiredHeadings,
    [
      "Current State",
      "Completed Work",
      "Remaining Work",
      "Decisions",
      "Blockers",
      "Human Actions Pending",
      "Modified Files",
      "Blueprint Snapshot",
      "Next Action",
      "Context Notes"
    ]
  );
});

test("canonical lifecycle contracts allow additional top-level headings without breaking validation", () => {
  const research = canonicalResearchContent(
    "One registry reduces retry loops.",
    "| R-1 | Centralize templates | Use one MCP-owned registry for authoring and validation. |\n"
  );
  const verification = `# Phase 03: Discovery - Verification

**Coverage:** Reviewed \`03-01-SUMMARY.md\` and related saved summaries.
**Gate State:** PASS
**Sign-off:** validation lead

## Validation Summary

- Validation coverage is sufficient for UAT.

## Requirement / Task Coverage

| Requirement | Task or Check | Evidence | Coverage State | Notes |
|-------------|---------------|----------|----------------|-------|
| VALID-01 | Confirm saved execution summaries exist | .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md | PASS | Summary-backed coverage is present. |

## Evidence Reviewed

- .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md

## Test Infrastructure / Evidence Metadata

- Harness: node:test
- Commands: npm test
- Evidence type: saved execution summary
- Test infrastructure status: available

## Manual-Only or Deferred Coverage

| Item | Why manual or deferred | Follow-Up | Status |
|------|------------------------|-----------|--------|
| none | none | none | NONE |

## Gate State

- Gate: PASS
- Sign-off: validation lead
- Readiness: ready for UAT

## Gap Classification

| Gap class | Scope | Evidence | Repair |
|-----------|-------|----------|--------|
| none | none | .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md | none |

## Gaps Found

- none

## Suggested Repairs

- none

## Next Safe Action

- /blu-verify-work 3

## Additional Context

- Extra validator notes are allowed here.
`;
  const uat = `# Phase 03: Discovery - UAT

**Status:** PASS
**Resume State:** RESUMED
**Checkpoint:** none

## UAT Summary

- The saved behavior matched the accepted summary evidence.

## Session State

- Resume source: saved summary evidence
- Current session step: Confirm the accepted behavior still holds after a pause.
- Continuity notes: Keep the same summary-backed outcome when the session resumes.

## Questions Asked

- none

## Observed Behavior

- The observed behavior matched .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md.

## Unresolved Gaps

- none

## Follow-Up Fixes

- none

## Next Safe Action

- /blu-progress

## Additional Context

- Extra UAT notes remain valid.
`;

  const researchValidation = validateResearchArtifactContent(research);
  const verificationValidation = validateVerificationArtifactContent(verification, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);
  const uatValidation = validateUatArtifactContent(uat, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);
  const invalidCheckpointUat = uat.replace("**Checkpoint:** none", "**Checkpoint:** pending");
  const invalidCheckpointValidation = validateUatArtifactContent(invalidCheckpointUat, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);

  assert.equal(researchValidation.valid, true, researchValidation.issues.join("\n"));
  assert.equal(verificationValidation.valid, true, verificationValidation.issues.join("\n"));
  assert.equal(uatValidation.valid, true, uatValidation.issues.join("\n"));
  assert.equal(invalidCheckpointValidation.valid, false, invalidCheckpointValidation.issues.join("\n"));
  assert.match(
    invalidCheckpointValidation.issues.join("\n"),
    /saved checkpoint path ending in `-DISCUSS-CHECKPOINT\.json` or `none`|`none` or a saved checkpoint path ending in `-DISCUSS-CHECKPOINT\.json`/
  );

  const contradictoryVerification = verification
    .replace("**Gate State:** PASS", "**Gate State:** PASS with follow-up")
    .replace("- Gate: PASS", "- Gate: BLOCKED")
    .replace("- Readiness: ready for UAT", "- Readiness: not ready for UAT");
  const contradictoryValidation = validateVerificationArtifactContent(contradictoryVerification, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);

  assert.equal(contradictoryValidation.valid, false, contradictoryValidation.issues.join("\n"));
  assert.match(
    contradictoryValidation.issues.join("\n"),
    /must declare \*\*Gate State:\*\* as PASS, PARTIAL, or BLOCKED|must keep the top \*\*Gate State:\*\* marker and the Gate section value consistent|must keep the Gate section Readiness value aligned with the Gate state/
  );
});

test("research contract rejects skeleton content that lacks substantive section detail", () => {
  const skeletalResearch = canonicalResearchContent("Keep registry updates aligned with MCP.", "");

  const validation = validateResearchArtifactContent(skeletalResearch);

  assert.equal(validation.valid, false, validation.issues.join("\n"));
  assert.match(
    validation.issues.join("\n"),
    /Phase Requirements must include at least one populated requirement row|substantive content/i
  );
});

test("review and report contracts validate canonical sections while keeping extra headings compatible", () => {
  const review = `# Phase 05: Security - Code Review

**Verdict:** FOLLOW_UP

## Review Summary

- Severity summary: critical 0, high 1, medium 0, low 0, unknown 0.

## Scope Reviewed

- src/mcp/tools/review.ts

## Evidence Reviewed

- .blueprint/phases/05-review-scope/05-01-PLAN.md
- .blueprint/phases/05-review-scope/05-01-SUMMARY.md

## Positive Signals

- Review scope stayed bounded to the saved plan outputs.

## Severity Summary

- critical: 0
- high: 1
- medium: 0
- low: 0
- unknown: 0

## Findings

- [high] Missing contract validation would let malformed review artifacts persist.

## Follow-Ups

- Add canonical review validation before persistence.

## Next Safe Action

- /blu-progress

## Additional Context

- Extra reviewer notes are allowed.
`;
  const thinReview = `# Phase 05: Security - Code Review

**Verdict:** FOLLOW_UP

## Scope Reviewed

- src/mcp/tools/review.ts

## Findings

- [high] Missing contract validation would let malformed review artifacts persist.

## Follow-Ups

- Add canonical review validation before persistence.

## Next Safe Action

- /blu-progress
`;
  const securityContract = readArtifactContract("review.security");
  const milestoneAuditContract = readArtifactContract("report.milestone-audit");
  const securityScaffoldValidation = validateReviewArtifactContent(
    securityContract.authoringTemplate,
    "security"
  );
  const thinSecurityReview = `# Phase 05: Security - Security Review

**Posture:** PASS

## Security Summary

- Saved evidence looks stable.

## Evidence Reviewed

- .blueprint/phases/05-review-scope/05-01-SUMMARY.md

## Findings

- none

## Follow-Ups

- none

## Next Safe Action

- /blu-progress
`;
  const thinSecurityValidation = validateReviewArtifactContent(thinSecurityReview, "security");
  const report = `# Debug Report

## Problem Statement

- Validation drift caused repeated MCP write retries.

## Evidence Collected

- Saved artifacts and repeated invalid write outcomes.

## Hypotheses

- Commands were drafting against stale inline templates.

## Actions Taken

- Introduced a canonical contract registry.

## Next Safe Action

- /blu-progress

## Additional Context

- Extra operational notes are allowed.
`;
  const thinAuditFixReport = `# Audit Fix Report: Phase 04

## Evidence Used

- .blueprint/phases/04-release-readiness/04-01-SUMMARY.md
`;
  const milestoneAuditReport = `# Milestone v2 - Audit

**Verdict:** READY_TO_CLOSE
**Evidence Dimensions:** roadmap, validation, UAT, carry-forward

## Audit Verdict

- Verdict: READY_TO_CLOSE
- Rationale: All milestone phases have validation and UAT evidence, so the milestone can close.
- Decision basis: ROADMAP, verification, UAT, and summary evidence remain aligned.

## Milestone Evidence Dimensions

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Roadmap intent | .blueprint/ROADMAP.md | PASS | The milestone intent and phase list are locked. |
| Validation evidence | .blueprint/phases/04-release-readiness/04-VERIFICATION.md | PASS | The release-readiness phase has durable validation evidence. |
| UAT evidence | .blueprint/phases/04-release-readiness/04-UAT.md | PASS | The UAT closeout evidence is saved. |
| Carry-forward evidence | .blueprint/phases/04-release-readiness/04-01-SUMMARY.md | PASS | The summary is ready to seed milestone completion. |

## Original Intent Snapshot

- Validate that milestone v2 outcomes match the planned roadmap intent.

## Roadmap And Phase Evidence

- .blueprint/ROADMAP.md
- .blueprint/phases/04-release-readiness/04-VERIFICATION.md
- .blueprint/phases/04-release-readiness/04-UAT.md

## Requirement Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Integration Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Flow Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Optional Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Gaps Found

- none

## Archival Blockers

- none

## Next Safe Action

- /blu-complete-milestone v2
`;
  const thinMilestoneAuditReport = `# Milestone v2 - Audit

## Original Intent Snapshot

- .blueprint/ROADMAP.md

## Roadmap And Phase Evidence

- .blueprint/phases/04-release-readiness/04-VERIFICATION.md

## Requirement Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Integration Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Flow Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Optional Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Gaps Found

- none

## Archival Blockers

- none

## Next Safe Action

- /blu-complete-milestone v2
`;
  const milestoneCompleteReport = `# Milestone v2 - Completion

**Decision:** READY_TO_CLOSE
**Audit Report Used:** .blueprint/reports/milestone-audit-v2.md
**Evidence Ledger:** roadmap, validation, UAT, carry-forward

## Completion Decision

- Decision: READY_TO_CLOSE
- Rationale: The saved roadmap, verification, UAT, and carry-forward evidence all support closing the milestone.
- Closeout basis: .blueprint/reports/milestone-audit-v2.md

## Audit Report Used

- .blueprint/reports/milestone-audit-v2.md

## Milestone Evidence Ledger

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Roadmap intent | .blueprint/ROADMAP.md | PASS | The roadmap intent and phase list are locked. |
| Validation evidence | .blueprint/phases/04-release-readiness/04-VERIFICATION.md | PASS | The verification evidence is durable. |
| UAT evidence | .blueprint/phases/04-release-readiness/04-UAT.md | PASS | The UAT evidence is durable. |
| Carry-forward evidence | .blueprint/phases/04-release-readiness/04-01-SUMMARY.md | PASS | The closeout evidence can seed the next milestone. |

## Residual Watch Items

- none

## Next Safe Action

- /blu-milestone-summary v2
`;
  const thinMilestoneCompleteReport = `# Milestone v2 - Completion

**Decision:** READY_TO_CLOSE
**Audit Report Used:** none
**Evidence Ledger:** roadmap, validation, UAT, carry-forward

## Completion Decision

- Decision: READY_TO_CLOSE

## Audit Report Used

- none

## Milestone Evidence Ledger

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Roadmap intent | .blueprint/ROADMAP.md | PASS | The roadmap intent and phase list are locked. |

## Residual Watch Items

- none

## Next Safe Action

- /blu-milestone-summary v2
`;
  const milestoneSummaryReport = `# Milestone v2 - Summary

**Sources Reviewed:** .blueprint/reports/milestone-audit-v2.md, .blueprint/reports/milestone-complete-v2.md, roadmap evidence
**Evidence Ledger:** audit, completion, roadmap, carry-forward
**Carry-Forward Context:** seed for /blu-new-milestone

## Scope Summary

- Milestone v2 closed with saved audit and completion evidence.

## Source Reports Used

- .blueprint/reports/milestone-audit-v2.md
- .blueprint/reports/milestone-complete-v2.md

## Milestone Evidence Ledger

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Audit report | .blueprint/reports/milestone-audit-v2.md | PASS | The audit report exists and supports closeout. |
| Completion report | .blueprint/reports/milestone-complete-v2.md | PASS | The completion report exists and supports handoff. |
| Roadmap context | .blueprint/ROADMAP.md | PASS | The roadmap context is still aligned. |
| Carry-forward context | .blueprint/phases/04-release-readiness/04-01-SUMMARY.md | PASS | The carry-forward context can seed the next milestone. |

## Shipped Outcomes

- Milestone closeout artifacts were saved for carry-forward planning.

## Deferred Follow-Ups

- none

## Recommended Carry-Forward Context

- Use the audit and completion reports to seed the next milestone.

## Next Safe Action

- /blu-new-milestone
`;
  const thinMilestoneSummaryReport = `# Milestone v2 - Summary

**Sources Reviewed:** .blueprint/reports/milestone-audit-v2.md
**Evidence Ledger:** audit, completion, roadmap, carry-forward
**Carry-Forward Context:** seed for /blu-new-milestone

## Scope Summary

- Milestone v2 is done.

## Source Reports Used

- .blueprint/reports/milestone-audit-v2.md

## Milestone Evidence Ledger

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Audit report | .blueprint/reports/milestone-audit-v2.md | PASS | The audit report exists. |

## Shipped Outcomes

- none

## Deferred Follow-Ups

- none

## Recommended Carry-Forward Context

- none

## Next Safe Action

- /blu-new-milestone
`;
  const invalidVerdictMilestoneAuditReport = `# Milestone v2 - Audit

**Verdict:** READY_TO_CLOSE
**Evidence Dimensions:** roadmap, validation, UAT, carry-forward

## Audit Verdict

- Rationale: The milestone needs one more pass before closeout.
- Decision basis: ROADMAP, verification, UAT, and summary evidence remain aligned.

## Milestone Evidence Dimensions

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Roadmap intent | .blueprint/ROADMAP.md | PASS | The milestone intent and phase list are locked. |
| Validation evidence | .blueprint/phases/04-release-readiness/04-VERIFICATION.md | PASS | The release-readiness phase has durable validation evidence. |
| UAT evidence | .blueprint/phases/04-release-readiness/04-UAT.md | PASS | The UAT closeout evidence is saved. |
| Carry-forward evidence | .blueprint/phases/04-release-readiness/04-01-SUMMARY.md | PASS | The summary is ready to seed milestone completion. |

## Original Intent Snapshot

- Validate that milestone v2 outcomes match the planned roadmap intent.

## Roadmap And Phase Evidence

- .blueprint/ROADMAP.md
- .blueprint/phases/04-release-readiness/04-VERIFICATION.md
- .blueprint/phases/04-release-readiness/04-UAT.md

## Requirement Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Integration Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Flow Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Optional Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Gaps Found

- none

## Archival Blockers

- none

## Next Safe Action

- /blu-complete-milestone v2
`;
  const customReport = `# Team Notes

- Non-contract report payloads stay permissive.
`;
  const reviewValidation = validateReviewArtifactContent(review, "code-review");
  const thinReviewValidation = validateReviewArtifactContent(thinReview, "code-review");
  const milestoneAuditScaffoldValidation = validateReportArtifactContent(
    milestoneAuditContract.authoringTemplate,
    "milestone-audit-v2"
  );
  const milestoneAuditValidation = validateReportArtifactContent(
    milestoneAuditReport,
    "milestone-audit-v2"
  );
  const legacyMilestoneAuditReport = `# Milestone v2 - Audit

**Verdict:** READY_TO_CLOSE
**Evidence Dimensions:** roadmap, validation, UAT, carry-forward

## Audit Verdict

- Verdict: READY_TO_CLOSE
- Rationale: The milestone is ready to close.
- Decision basis: ROADMAP, verification, UAT, and summary evidence remain aligned.

## Milestone Evidence Dimensions

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Roadmap intent | .blueprint/ROADMAP.md | PASS | The milestone intent and phase list are locked. |
| Validation evidence | .blueprint/phases/04-release-readiness/04-VERIFICATION.md | PASS | The release-readiness phase has durable validation evidence. |
| UAT evidence | .blueprint/phases/04-release-readiness/04-UAT.md | PASS | The UAT closeout evidence is saved. |
| Carry-forward evidence | .blueprint/phases/04-release-readiness/04-01-SUMMARY.md | PASS | The summary is ready to seed milestone completion. |

## Original Intent Snapshot

- Validate that milestone v2 outcomes match the planned roadmap intent.

## Roadmap And Phase Evidence

- .blueprint/ROADMAP.md
- .blueprint/phases/04-release-readiness/04-VERIFICATION.md
- .blueprint/phases/04-release-readiness/04-UAT.md

## Gaps Found

- none

## Archival Blockers

- none

## Next Safe Action

- /blu-complete-milestone v2
`;
  const invalidVerdictMilestoneAuditValidation = validateReportArtifactContent(
    invalidVerdictMilestoneAuditReport,
    "milestone-audit-v2"
  );
  const invalidStatusMilestoneAuditReport = milestoneAuditReport.replace(
    "| Roadmap intent | .blueprint/ROADMAP.md | PASS | The milestone intent and phase list are locked. |",
    "| Roadmap intent | .blueprint/ROADMAP.md | PASS|GAP|BLOCKED | The milestone intent and phase list are locked. |"
  );
  const invalidStatusMilestoneAuditValidation = validateReportArtifactContent(
    invalidStatusMilestoneAuditReport,
    "milestone-audit-v2"
  );
  const thinMilestoneAuditValidation = validateReportArtifactContent(
    thinMilestoneAuditReport,
    "milestone-audit-v2"
  );
  const milestoneCompleteValidation = validateReportArtifactContent(
    milestoneCompleteReport,
    "milestone-complete-v2"
  );
  const thinMilestoneCompleteValidation = validateReportArtifactContent(
    thinMilestoneCompleteReport,
    "milestone-complete-v2"
  );
  const milestoneSummaryValidation = validateReportArtifactContent(
    milestoneSummaryReport,
    "milestone-summary-v2"
  );
  const thinMilestoneSummaryValidation = validateReportArtifactContent(
    thinMilestoneSummaryReport,
    "milestone-summary-v2"
  );
  assert.match(
    securityContract.authoringTemplate,
    /\*\*Posture:\*\* PASS\|FOLLOW_UP\|BLOCKED/
  );
  assert.equal(securityScaffoldValidation.valid, false);
  assert.match(securityScaffoldValidation.issues.join("\n"), /placeholder scaffold text/i);
  assert.equal(milestoneAuditScaffoldValidation.valid, false);
  assert.match(milestoneAuditScaffoldValidation.issues.join("\n"), /placeholder scaffold text/i);
  assert.equal(thinSecurityValidation.valid, false);
  assert.match(thinSecurityValidation.issues.join("\n"), /Threat Register/);
  assert.match(thinSecurityValidation.issues.join("\n"), /Accepted Risks/);
  assert.match(thinSecurityValidation.issues.join("\n"), /Security Audit Trail/);
  const reportValidation = validateReportArtifactContent(report, "debug-latest");
  const thinAuditFixValidation = validateReportArtifactContent(thinAuditFixReport, "audit-fix-04");
  const customReportValidation = validateReportArtifactContent(customReport, "custom-team-notes");

  assert.equal(reviewValidation.valid, true, reviewValidation.issues.join("\n"));
  assert.equal(thinReviewValidation.valid, false);
  assert.match(thinReviewValidation.issues.join("\n"), /Review Summary/);
  assert.match(thinReviewValidation.issues.join("\n"), /Evidence Reviewed/);
  assert.match(thinReviewValidation.issues.join("\n"), /Positive Signals/);
  assert.match(thinReviewValidation.issues.join("\n"), /Severity Summary/);
  assert.equal(reportValidation.valid, true, reportValidation.issues.join("\n"));
  assert.equal(thinAuditFixValidation.valid, false);
  assert.match(thinAuditFixValidation.issues.join("\n"), /Fix Scope/);
  assert.match(thinAuditFixValidation.issues.join("\n"), /Changes Applied/);
  assert.match(thinAuditFixValidation.issues.join("\n"), /Remaining Gaps/);
  assert.match(thinAuditFixValidation.issues.join("\n"), /Next Safe Action/);
  assert.equal(milestoneAuditValidation.valid, true, milestoneAuditValidation.issues.join("\n"));
  assert.equal(
    validateReportArtifactContent(legacyMilestoneAuditReport, "milestone-audit-v2").valid,
    true
  );
  assert.equal(invalidVerdictMilestoneAuditValidation.valid, false);
  assert.match(
    invalidVerdictMilestoneAuditValidation.issues.join("\n"),
    /Verdict line/
  );
  assert.equal(invalidStatusMilestoneAuditValidation.valid, false);
  assert.match(
    invalidStatusMilestoneAuditValidation.issues.join("\n"),
    /keep each evidence row in the Dimension, Evidence, Status, and Notes columns/
  );
  assert.equal(thinMilestoneAuditValidation.valid, false);
  assert.match(thinMilestoneAuditValidation.issues.join("\n"), /Audit Verdict/);
  assert.match(thinMilestoneAuditValidation.issues.join("\n"), /Milestone Evidence Dimensions/);
  assert.equal(
    milestoneCompleteValidation.valid,
    true,
    milestoneCompleteValidation.issues.join("\n")
  );
  assert.equal(thinMilestoneCompleteValidation.valid, false);
  assert.match(thinMilestoneCompleteValidation.issues.join("\n"), /Audit Report Used/);
  assert.match(thinMilestoneCompleteValidation.issues.join("\n"), /Milestone Evidence Ledger/);
  assert.match(thinMilestoneCompleteValidation.issues.join("\n"), /must reference milestone-audit/i);
  assert.equal(
    milestoneSummaryValidation.valid,
    true,
    milestoneSummaryValidation.issues.join("\n")
  );
  assert.equal(thinMilestoneSummaryValidation.valid, false);
  assert.match(thinMilestoneSummaryValidation.issues.join("\n"), /Source Reports Used/);
  assert.match(thinMilestoneSummaryValidation.issues.join("\n"), /Milestone Evidence Ledger/);
  assert.match(thinMilestoneSummaryValidation.issues.join("\n"), /must reference milestone-complete/i);
  assert.equal(customReportValidation.valid, true, customReportValidation.issues.join("\n"));
});

test("verification and UAT contracts reject evidence that does not link to a valid summary", () => {
  const verification = `# Phase 03: Discovery - Verification

**Coverage:** Reviewed the saved execution evidence for the completed phase.

## Validation Summary

- Validation coverage is sufficient for UAT.

## Evidence Reviewed

- unrelated-note.md

## Gaps Found

- none

## Suggested Repairs

- none

## Next Safe Action

- /blu-verify-work 3
`;
  const uat = `# Phase 03: Discovery - UAT

**Status:** PASS

## UAT Summary

- The saved behavior matched the expected outcome.

## Questions Asked

- Did the observed behavior align with the completed execution evidence?

## Observed Behavior

- The observed behavior remained consistent with the reported outcome.

## Unresolved Gaps

- none

## Follow-Up Fixes

- none

## Next Safe Action

- /blu-progress
`;
  const verificationValidation = validateVerificationArtifactContent(verification, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);
  const uatValidation = validateUatArtifactContent(uat, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);

  assert.equal(verificationValidation.valid, false, verificationValidation.issues.join("\n"));
  assert.equal(uatValidation.valid, false, uatValidation.issues.join("\n"));
  assert.match(
    verificationValidation.issues.join("\n"),
    /must cite at least one saved execution summary path or filename/i
  );
  assert.match(
    uatValidation.issues.join("\n"),
    /must (?:cite|reference) at least one saved execution summary path or filename/i
  );
});

test("verification and UAT contracts reject headings that are not the first bytes in the file", () => {
  const prefacedVerification = `Preamble text that should fail.

# Phase 03: Discovery - Verification

**Coverage:** Reviewed the saved execution evidence for the completed phase.

## Validation Summary

- Validation coverage is sufficient for UAT.

## Evidence Reviewed

- .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md

## Gaps Found

- none

## Suggested Repairs

- none

## Next Safe Action

- /blu-verify-work 3
`;
  const prefacedUat = `Preamble text that should fail.

# Phase 03: Discovery - UAT

**Status:** PASS

## UAT Summary

- The saved behavior matched the expected outcome.

## Questions Asked

- Did the observed behavior align with the completed execution evidence?

## Observed Behavior

- The observed behavior matched .blueprint/phases/03-phase-discovery/03-01-SUMMARY.md.

## Unresolved Gaps

- none

## Follow-Up Fixes

- none

## Next Safe Action

- /blu-progress
`;
  const verificationValidation = validateVerificationArtifactContent(prefacedVerification, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);
  const uatValidation = validateUatArtifactContent(prefacedUat, [
    ".blueprint/phases/03-phase-discovery/03-01-SUMMARY.md"
  ]);

  assert.equal(verificationValidation.valid, false, verificationValidation.issues.join("\n"));
  assert.equal(uatValidation.valid, false, uatValidation.issues.join("\n"));
  assert.match(verificationValidation.issues.join("\n"), /must start with a '# \.\.\. - Verification' heading/i);
  assert.match(uatValidation.issues.join("\n"), /must start with a '# \.\.\. - UAT' heading/i);
});

test("contract registry remains listable through the direct helper", () => {
  const contracts = listArtifactContracts();

  assert.ok(contracts.some((contract) => contract.id === "phase.research"));
  assert.ok(contracts.some((contract) => contract.id === "review.security"));
  assert.ok(contracts.some((contract) => contract.id === "report.debug"));
});
