export type ArtifactContractScope = "bootstrap" | "codebase" | "phase" | "review" | "report";

export type ArtifactContractFreehandPolicy =
  | "additional-top-level-headings"
  | "locked-structure";

export type ArtifactContractId =
  | "bootstrap.project"
  | "bootstrap.requirements"
  | "bootstrap.roadmap"
  | "codebase.stack"
  | "codebase.architecture"
  | "codebase.structure"
  | "codebase.conventions"
  | "codebase.testing"
  | "codebase.integrations"
  | "codebase.concerns"
  | "phase.context"
  | "phase.discussion-log"
  | "phase.research"
  | "phase.ui-spec"
  | "phase.plan"
  | "phase.summary"
  | "phase.verification"
  | "phase.uat"
  | "review.code-review"
  | "review.review-fix"
  | "review.peer-review"
  | "review.security"
  | "review.ui-review"
  | "report.pause-work"
  | "report.milestone-audit"
  | "report.milestone-complete"
  | "report.milestone-summary"
  | "report.debug"
  | "report.quick-run"
  | "report.docs-update"
  | "report.pr-branch"
  | "report.ship"
  | "report.undo"
  | "report.cleanup"
  | "report.add-tests"
  | "report.audit-fix"
  | "report.impact";

export type ArtifactTemplateContext = {
  phaseLabel?: string;
  phasePrefix?: string;
  phaseName?: string;
  phaseDir?: string;
  planId?: string;
  domain?: string;
  summaryFile?: string;
  summaryPath?: string;
  reportName?: string;
  milestone?: string;
  currentPhase?: string;
  activeCommand?: string;
};

export type ArtifactContractDefinition = {
  id: ArtifactContractId;
  scope: ArtifactContractScope;
  ownerTool: string;
  pathOwner: string;
  canonicalName: string;
  canonicalFilePattern: string;
  freehandPolicy: ArtifactContractFreehandPolicy;
  requiredHeadings: string[];
  lockedMarkers: string[];
  placeholderSignals: string[];
  notes: string[];
  renderScaffoldTemplate: (context?: ArtifactTemplateContext) => string;
  renderAuthoringTemplate: (context?: ArtifactTemplateContext) => string;
};

export type ArtifactContractReadResult = Omit<
  ArtifactContractDefinition,
  "renderScaffoldTemplate" | "renderAuthoringTemplate"
> & {
  scaffoldTemplate: string;
  authoringTemplate: string;
};

function phaseLabel(context?: ArtifactTemplateContext): string {
  return context?.phaseLabel?.trim() || "Phase XX: <Phase Name>";
}

function phasePrefix(context?: ArtifactTemplateContext): string {
  return context?.phasePrefix?.trim() || "XX";
}

function planId(context?: ArtifactTemplateContext): string {
  return context?.planId?.trim() || "YY";
}

function reportName(context: ArtifactTemplateContext | undefined, fallback: string): string {
  return context?.reportName?.trim() || fallback;
}

function summaryFile(context?: ArtifactTemplateContext): string {
  return context?.summaryFile?.trim() || `${phasePrefix(context)}-${planId(context)}-SUMMARY.md`;
}

function summaryPath(context?: ArtifactTemplateContext): string {
  return (
    context?.summaryPath?.trim() ||
    `.blueprint/phases/<phase-dir>/${summaryFile(context)}`
  );
}

function phaseDir(context?: ArtifactTemplateContext): string {
  return context?.phaseDir?.trim() || "<phase-dir>";
}

function milestone(context?: ArtifactTemplateContext): string {
  return context?.milestone?.trim() || "<milestone-version>";
}

function currentPhase(context?: ArtifactTemplateContext): string {
  return context?.currentPhase?.trim() || "none";
}

function activeCommand(context?: ArtifactTemplateContext): string {
  return context?.activeCommand?.trim() || "/blu-pause-work";
}

function domain(context?: ArtifactTemplateContext): string {
  return context?.domain?.trim() || "<research domain>";
}

function withScaffoldFooter(content: string): string {
  return `${content}\n\n---\n*Generated by \`blueprint_artifact_scaffold\`*\n`;
}

function renderBootstrapProjectTemplate(): string {
  return `# <project name>

## Vision

- <project vision>

## Audience

- Primary: <primary audience>
- Secondary: <secondary audience>

## Constraints

- <constraint>

## Current Milestone

<current milestone>

## Bootstrap Shape

- Repository shape: greenfield|scaffold-only|brownfield
- Codebase mapping: ready|pending
- Bootstrap posture: <bootstrap posture>

## Scope Posture

- Committed v1: <requirement ids or none>
- Deferred: <requirement ids or none>
- Out-of-scope: <requirement ids or none>

## Non-Goals

- <non-goal>

## Assumptions

- <assumption>`;
}

function renderBootstrapRequirementsTemplate(): string {
  return `# Requirements: <project name>

## Requirements Table

| ID | Requirement | Status | Notes |
|----|-------------|--------|-------|
| REQ-01 | <requirement> | Pending | <notes> |

## Scope Summary

- Committed v1: REQ-01
- Deferred: none
- Out-of-scope: none

## Committed V1 Scope

### <group>

- \`REQ-01\`: <requirement>
  - Status: Pending
  - Notes: <notes>

## Deferred Scope

### <group>

- \`REQ-02\`: <requirement>
  - Status: Pending
  - Notes: <notes>

## Out-of-Scope Cuts

### <group>

- \`REQ-03\`: <requirement>
  - Status: Pending
  - Notes: <notes>

## Traceability Notes

- Keep every requirement ID referenced from \`.blueprint/ROADMAP.md\` before execution planning begins.
- Preserve requirement IDs across later phase artifacts instead of silently renumbering them.

## Open Questions

- <open question>`;
}

function renderBootstrapRoadmapTemplate(): string {
  return `# Roadmap: <project name>

## Milestone

- Active milestone: <milestone>

## Bootstrap Status

- Repository shape: greenfield|scaffold-only|brownfield
- Codebase mapping: ready|pending
- Roadmap confidence: ready for progress review|provisional until /blu-map-codebase

## Requirement Coverage

- Committed v1: REQ-01
- Deferred: none
- Out-of-scope: none

## Phases

- [ ] Phase 1: <phase title> (Requirements: REQ-01)
  - Objective: <phase objective>
  - Success Criteria:
    - <success criterion>

## Notes

- <bootstrap assumption>`;
}

type CodebaseTemplateSection = {
  heading: string;
  bullets: string[];
};

function renderCodebaseTemplate(
  title: string,
  sections: CodebaseTemplateSection[],
  options: { footer?: boolean } = {}
): string {
  const body = [
    `# ${title}`,
    "",
    "## Purpose",
    "",
    "- Capture the mapped repo evidence for this codebase area.",
    "",
    ...sections.flatMap((section) => [
      `## ${section.heading}`,
      "",
      ...section.bullets.map((bullet) => `- ${bullet}`),
      ""
    ])
  ];

  const content = body.join("\n").trimEnd();

  if (!options.footer) {
    return `${content}\n`;
  }

  return `${withScaffoldFooter(content)}`;
}

function renderCodebaseStackTemplate(
  _context?: ArtifactTemplateContext,
  options: { footer?: boolean } = {}
): string {
  return renderCodebaseTemplate(
    "Stack",
    [
      {
        heading: "Runtime",
        bullets: [
          "Primary language or runtime: <runtime>",
          "Module system or platform: <module system>",
          "Package manager or build entrypoint: <package manager>"
        ]
      },
      {
        heading: "Tooling",
        bullets: [
          "Build command: <build command>",
          "Test command: <test command>",
          "Lint or format command: <lint or format command>"
        ]
      },
      {
        heading: "Dependencies",
        bullets: [
          "Core dependencies: <core dependencies>",
          "Notable dev dependencies: <dev dependencies>",
          "Generated or vendored tooling: <tooling notes>"
        ]
      },
      {
        heading: "Notes",
        bullets: ["<stack note>"]
      }
    ],
    options
  );
}

function renderCodebaseArchitectureTemplate(
  _context?: ArtifactTemplateContext,
  options: { footer?: boolean } = {}
): string {
  return renderCodebaseTemplate(
    "Architecture",
    [
      {
        heading: "Overview",
        bullets: [
          "Map the primary execution model and top-level application shape: <overview>",
          "Describe the main repo boundary or runtime surface: <boundary note>"
        ]
      },
      {
        heading: "Boundaries",
        bullets: [
          "Primary subsystems or layers: <boundary>",
          "Cross-cutting concerns or shared services: <boundary>"
        ]
      },
      {
        heading: "Flow",
        bullets: [
          "Entry points and request path: <entry points>",
          "Data flow or orchestration path: <flow summary>"
        ]
      },
      {
        heading: "Notes",
        bullets: ["<architecture note>"]
      }
    ],
    options
  );
}

function renderCodebaseStructureTemplate(
  _context?: ArtifactTemplateContext,
  options: { footer?: boolean } = {}
): string {
  return renderCodebaseTemplate(
    "Structure",
    [
      {
        heading: "Directory Map",
        bullets: [
          "`<directory>`: <purpose>",
          "`<directory>`: <purpose>"
        ]
      },
      {
        heading: "Key Files",
        bullets: [
          "`<file path>`: <purpose>",
          "`<file path>`: <purpose>"
        ]
      },
      {
        heading: "Seams",
        bullets: [
          "Important refactor or ownership seam: <seam>",
          "Additional seam or boundary: <seam>"
        ]
      },
      {
        heading: "Notes",
        bullets: ["<structure note>"]
      }
    ],
    options
  );
}

function renderCodebaseConventionsTemplate(
  _context?: ArtifactTemplateContext,
  options: { footer?: boolean } = {}
): string {
  return renderCodebaseTemplate(
    "Conventions",
    [
      {
        heading: "Naming",
        bullets: [
          "File, type, and module naming conventions: <naming convention>",
          "Repo-specific vocabulary or prefixes: <naming detail>"
        ]
      },
      {
        heading: "Module Boundaries",
        bullets: [
          "Import/export or package boundary rules: <boundary rule>",
          "Directory ownership or layering rule: <boundary rule>"
        ]
      },
      {
        heading: "Error Handling",
        bullets: [
          "Error and logging pattern: <error handling pattern>",
          "Retry, guard, or failure conventions: <error handling detail>"
        ]
      },
      {
        heading: "Documentation",
        bullets: [
          "Commenting or README style: <documentation convention>",
          "Where durable notes should live: <documentation location>"
        ]
      },
      {
        heading: "Notes",
        bullets: ["<convention note>"]
      }
    ],
    options
  );
}

function renderCodebaseTestingTemplate(
  _context?: ArtifactTemplateContext,
  options: { footer?: boolean } = {}
): string {
  return renderCodebaseTemplate(
    "Testing",
    [
      {
        heading: "Framework",
        bullets: [
          "Primary test runner: <runner>",
          "Assertion or mocking stack: <assertion stack>"
        ]
      },
      {
        heading: "Commands",
        bullets: [
          "Full test command: <test command>",
          "Focused or watch command: <focused command>"
        ]
      },
      {
        heading: "Coverage",
        bullets: [
          "Key coverage signal: <coverage signal>",
          "Gap or limitation that still needs attention: <coverage gap>"
        ]
      },
      {
        heading: "Notes",
        bullets: ["<testing note>"]
      }
    ],
    options
  );
}

function renderCodebaseIntegrationsTemplate(
  _context?: ArtifactTemplateContext,
  options: { footer?: boolean } = {}
): string {
  return renderCodebaseTemplate(
    "Integrations",
    [
      {
        heading: "External Systems",
        bullets: [
          "Service, provider, or backend dependency: <system>",
          "Additional external surface: <system>"
        ]
      },
      {
        heading: "SDKs And APIs",
        bullets: [
          "SDK or API surface: <sdk or api>",
          "Integration entrypoint or client wrapper: <integration detail>"
        ]
      },
      {
        heading: "Authentication And Secrets",
        bullets: [
          "Auth flow, credentials, or secrets handling: <auth detail>",
          "Operational boundary or environment note: <auth detail>"
        ]
      },
      {
        heading: "Notes",
        bullets: ["<integration note>"]
      }
    ],
    options
  );
}

function renderCodebaseConcernsTemplate(
  _context?: ArtifactTemplateContext,
  options: { footer?: boolean } = {}
): string {
  return renderCodebaseTemplate(
    "Concerns",
    [
      {
        heading: "Risks",
        bullets: [
          "Current risk that could slow mapping or delivery: <risk>",
          "Additional risk or unknown: <risk>"
        ]
      },
      {
        heading: "Gaps",
        bullets: [
          "Thin area, missing evidence, or unknown: <gap>",
          "Follow-up evidence still needed: <gap>"
        ]
      },
      {
        heading: "Follow-Ups",
        bullets: [
          "Next concrete follow-up: <follow-up>",
          "Later revisit item: <follow-up>"
        ]
      },
      {
        heading: "Questions",
        bullets: [
          "Open question that still needs an answer: <question>",
          "Additional question or assumption to verify: <question>"
        ]
      },
      {
        heading: "Notes",
        bullets: ["<concern note>"]
      }
    ],
    options
  );
}

function renderContextTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Context

## Phase Boundary

- Goal:
- In scope:
- Out of scope:
- Success criteria:

## Discovery Grounding

- Project brief:
- Requirements grounding:
- Workflow posture:
- Confirmed decisions:

## Implementation Decisions

- Implementation decision 1: <implementation decision 1>
- Tradeoffs or constraints: <tradeoff or constraint>

## Specific Ideas

- Specific idea 1: <specific idea 1>
- Specific idea 2: <specific idea 2>
- Later follow-up: <later follow-up>

## Existing Code Insights

- Existing code insight 1: <existing code insight 1>
- Reusable pattern: <reusable pattern>
- Known gap or caution: <gap or caution>

## Dependencies

- Prior phase artifacts: <prior phase artifacts>
- External constraints: <external constraints>
- Required follow-up reads: <required follow-up reads>

## Open Questions

- Question 1: <open question 1>

## Deferred Ideas

- Scope creep or later follow-up: <deferred idea>
- Ideas to revisit after this phase: <deferred idea>

## Canonical References

- Source 1: <source 1>`;
}

function renderDiscussionLogTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Discussion Log

## Summary

- Record the major discussion outcomes and unresolved questions here.

## Notes

- Timestamped notes:

## Follow-Ups

- Follow-up 1:`;
}

function renderResearchTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Research

**Researched:** <YYYY-MM-DD>
**Domain:** ${domain(context)}
**Confidence:** LOW|MEDIUM|HIGH

## Phase Requirements

| ID | Description | Research Support |
|----|-------------|------------------|
| <requirement-id> | <phase requirement> | <evidence-backed guidance> |

## Summary

- <key conclusion>

## Locked Decisions From Context

- <phase decision preserved from context>

## User Constraints

- <repo, product, or workflow constraint>

## Standard Stack

- <runtime, library, or shared repo pattern>

## Installation And Setup

- <installation or setup guidance>

## Alternatives Considered

- <alternative considered and tradeoff>

## Architecture Patterns

- <durable implementation pattern>

## Don't Hand-Roll

- <existing tool, helper, or platform feature>

## Anti-Patterns

- <anti-pattern detail or implementation to avoid>

## State Of The Art

- <current ecosystem or repo update with source date YYYY-MM-DD, or say not externally checked>

## Common Pitfalls

- <failure mode or regression risk>

## Open Questions

- <open question that still needs an answer>

## Confidence Breakdown

| Topic | Confidence | Why |
|-------|------------|-----|
| <topic> | LOW|MEDIUM|HIGH | <evidence-backed confidence explanation> |

## Code Examples

\`\`\`text
<short code or pseudocode example>
\`\`\`

## Recommendations

- <prescriptive recommendation with tradeoffs>

## Sources

- <repo path, URL, or cited file reference> - why it matters`;
}

function renderUiSpecTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - UI Spec

## Outcome Mode

- Choose one: UI contract or explicit skip rationale.

## Rationale

- For Explicit skip rationale, explain why UI work is out of scope, note any safety-gate implications, and name a revisit trigger. Delete this section for UI contract mode.

## User Experience Goals

- Goal 1: <primary UX objective for this phase>
- Primary user outcome: <the user-facing outcome this phase must improve>
- Evidence sources: <requirements, context, research, roadmap, or codebase paths used>

## Visual Design Decisions

- Design-system evidence: <existing components, tokens, styles, or \`none\`, with repo paths when known>
- Spacing and layout: <grid, rhythm, or layout constraints>
- Typography: <type scale, emphasis, or readability decisions>
- Color and contrast: <palette, semantic color, and contrast rules>
- Motion and feedback: <loading, hover, or transition guidance>
- Copy and content: <voice, terminology, and label constraints>
- Typography limits: <3-4 sizes, no more than 2 weights, and line-height rules>
- Color hierarchy: <60/30/10 role split or repo-derived equivalent plus accent reserved-for list>
- Copywriting contract: <primary CTA, empty state, error state, destructive confirmation>

## Screens And States

- Screen/state 1: <named screen or state in scope>
- Loading, empty, error, and success states: <required state behavior>
- Responsive behavior: <desktop, tablet, and mobile expectations>
- Visual hierarchy and focal point: <what draws attention first and why>

## Components And Constraints

- Component 1: <component, pattern, or surface in scope>
- Existing design-system or registry primitives to reuse: <existing primitives or \`none\`>
- New component or token justification: <new primitives needed or \`none\`>
- Density and interaction constraints: <layout density, touch targets, or gesture rules>
- Component inventory evidence: <repo paths, registry entries, or \`none\`>

## Accessibility And Content

- Accessibility note 1: <keyboard, focus, contrast, or assistive-tech guidance>
- Content hierarchy and empty-state guidance: <content hierarchy and empty-state behavior>
- Localization or content safety notes: <localization, moderation, or terminology notes>

## Registry And Design-System Safety

- Registry and design-system safety: <how the draft avoids forking the registry or design system>
- Token and theming compatibility: <token, theme, or brand-system compatibility notes>
- Revisit trigger if the scope changes: <when this contract must be revisited>
- Third-party registry safety evidence: <view passed, developer-approved after review, blocked, or not applicable>

## Checker Review

- Copywriting: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>
- Visual hierarchy: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>
- Color: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>
- Typography: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>
- Spacing: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>
- Registry and design-system safety: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>

## Next Safe Action

- /blu-plan-phase ${phasePrefix(context)}`;
}

function renderPlanTemplate(context?: ArtifactTemplateContext): string {
  return `---
phase: ${phasePrefix(context)}
plan_id: "${planId(context)}"
title: "${phaseLabel(context)} plan ${planId(context)}"
wave: 1
# Optional: gap_closure: true
status: planned
objective: "Replace with a concrete, execution-ready goal."
depends_on: []
requirements:
  - Replace with the exact requirement IDs this plan addresses.
files_modified:
  - Replace with the real repo paths the executor must touch.
read_first:
  - Replace with the files the executor must inspect before editing.
acceptance_criteria:
  - Replace with grep/test-verifiable acceptance criteria.
autonomous: true
---

# ${phaseLabel(context)} - Plan ${planId(context)}

## Goal

Replace with a concrete, execution-ready goal.

## Scope

- Replace with the exact work this plan owns.

## Tasks

### Task 1: Replace with a concrete task name

#### Read First

- Replace with the files the executor must inspect before editing.

#### Action

- Replace with concrete code, config, or artifact changes.

#### Acceptance Criteria

- Replace with grep/test-verifiable acceptance criteria.

## Verification

- Replace with the exact checks that prove this plan is complete.

## Must Haves

- Replace with the goal-backward must-haves this plan cannot drop.`;
}

function renderSummaryTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Summary ${planId(context)}

**Plan:** \`${phasePrefix(context)}-${planId(context)}-PLAN.md\`
**Status:** COMPLETED|PARTIAL|BLOCKED

## Outcome

- Concise delivery summary grounded in the completed work.

## Changes Made

- Explicit code, config, or artifact changes completed for this plan.

## Verification

- Command, test, or evidence that supports the reported outcome.

## Follow-Ups

- Remaining gap, handoff, or \`none\`.

## Evidence

- \`${summaryPath(context)}\` or other saved repo evidence if helpful.`;
}

function renderVerificationTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Verification

**Coverage:** Reviewed \`${summaryFile(context)}\` and any other saved phase summaries for validation evidence.
**Gate State:** PASS|PARTIAL|BLOCKED
**Sign-off:** verified|pending|blocked

## Validation Summary

- Concise readiness result grounded in the saved summaries.

## Requirement / Task Coverage

| Requirement | Task or Check | Evidence | Coverage State | Notes |
|-------------|---------------|----------|----------------|-------|
| <requirement-id> | <task or check> | <summary path, command, or saved evidence> | PASS|MANUAL|DEFERRED|BLOCKED | <coverage note> |

## Evidence Reviewed

- \`${summaryPath(context)}\`

## Test Infrastructure / Evidence Metadata

- Harness:
- Commands:
- Evidence type:
- Test infrastructure status:

## Manual-Only or Deferred Coverage

| Item | Why manual or deferred | Follow-Up | Status |
|------|------------------------|-----------|--------|
| <manual-only item> | <reason> | <follow-up> | MANUAL|DEFERRED|NONE |

## Gate State

- Gate: PASS|PARTIAL|BLOCKED
- Sign-off: <name or pending>
- Readiness: <ready for UAT or not ready>

## Gap Classification

| Gap class | Scope | Evidence | Repair |
|-----------|-------|----------|--------|
| <coverage gap class> | <scope> | <evidence> | <repair> |

## Gaps Found

- Explicit blocker, follow-up, or \`none\`.

## Suggested Repairs

- Explicit next repair, follow-up, or \`none\`.

## Next Safe Action

- <implemented next action: /blu-verify-work ${phasePrefix(context)} only for PASS and ready for UAT, /blu-add-tests ${phasePrefix(context)} for test-generation gaps, or /blu-audit-fix ${phasePrefix(context)} for implementation gaps>`;
}

function renderUatTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - UAT

**Status:** PASS|FAIL|PARTIAL
**Resume State:** RESUMED|NEW|CONTINUED
**Checkpoint:** <current checkpoint label or none>

## UAT Summary

- Concise user-facing result grounded in the saved summaries and verification artifact.

## Session State

- Resume source: <saved summary path, in-artifact checkpoint, or none>
- Current session step: <what is being resumed now>
- Continuity notes: <what must remain stable between sessions>

## Current Test

- Number: <active test number or testing complete>
- Name: <active user-observable test name or none>
- Expected: <what the user should observe>
- Awaiting: <explicit user response, checkpoint review choice, or none>

## Test Matrix

| # | Test | Expected Behavior | Evidence | Result | Notes |
|---|------|-------------------|----------|--------|-------|
| 1 | <test name> | <observable expected behavior> | ${summaryFile(context)} | pending|pass|issue|skipped|blocked | <note> |

## Result Summary

- Total: <N>
- Passed: <N>
- Issues: <N>
- Pending: <N>
- Skipped: <N>
- Blocked: <N>

## Questions Asked

- Question asked during the UAT pass, or \`none\`.

## Observed Behavior

- User-reported observed behavior tied to saved summary evidence such as \`${summaryFile(context)}\`.

## Unresolved Gaps

- Explicit blocker, follow-up, or \`none\`.

## Structured Gaps

| Test | Truth | Status | Severity | Reason | Follow-Up |
|------|-------|--------|----------|--------|-----------|
| <test number or none> | <expected behavior> | failed|partial|blocked|none | blocker|major|minor|cosmetic|none | <verbatim report or blocked reason> | <repair or confirmation path> |

## Follow-Up Fixes

- Explicit follow-up fix, acceptance note, or \`none\`.

## Next Safe Action

- <implemented next action such as /blu-verify-work ${phasePrefix(context)} while checkpointed, or /blu-progress when completed>`;
}

function renderCodeReviewTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Code Review

**Verdict:** PASS|FOLLOW_UP|BLOCKED

## Review Summary

- Phase, effective depth, scope source, file count, verdict rationale, and severity counts.

## Scope Reviewed

- Repo-relative file path reviewed, one per bullet or table row.

## Evidence Reviewed

- Saved summaries, plans, validation, UAT, security, existing review, or repo-file evidence that influenced the result.

## Positive Signals

- Concrete pass evidence, safeguards, tests, or coverage strengths; use \`none\` only when no positive signal was checked.

## Severity Summary

- critical: 0
- high: 0
- medium: 0
- low: 0
- unknown: 0

## Findings

- [high][follow-up] \`path/to/file.ts:42\` - Evidence, impact, and concrete fix or verification guidance.

## Follow-Ups

- Actionable fix, test gap, validation step, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderReviewFixTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Review Fix

**Status:** APPLIED|PARTIAL|SKIPPED

## Findings Addressed

- Finding id or summary addressed in this remediation pass.

## Changes Made

- Concrete remediation completed.

## Verification

- Validation or test evidence for the applied fix, or \`none\`.

## Follow-Ups

- Remaining work, deferred item, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderPeerReviewTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Peer Reviews

**Reviewers:** <reviewer-cli-1>, <reviewer-cli-2>

## Review Summary

- Concise synthesis of the saved reviewer outputs.

## Reviewer Results

- Reviewer name: main conclusions.

## Disagreements

- Explicit reviewer disagreement, or \`none\`.

## Follow-Ups

- Plan revision, execution change, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderSecurityTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Security

**Posture:** PASS|FOLLOW_UP|BLOCKED

## Security Summary

- Concise security posture grounded in saved evidence.

## Evidence Reviewed

- Saved phase artifacts, repo paths, or cited references reviewed.

## Threat Register

| Threat ID | Category | Component | Disposition | Mitigation | Status | Evidence / Note |
|-----------|----------|-----------|-------------|------------|--------|-----------------|
| T-01 | STRIDE category | component or boundary | mitigate / accept / transfer | declared control or risk decision | closed / accepted / open | File, artifact, or rationale reference. |

## Accepted Risks

- Accepted threat reference plus rationale, or \`none\`.

## Findings

- Open threat, missing control, or risk decision that needs explicit attention, or \`none\`.

## Follow-Ups

- Explicit hardening step, validation gap, or \`none\`.

## Security Audit Trail

- Audit date, threat counts, and verifier note.

## Next Safe Action

- /blu-progress`;
}

function renderUiReviewTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - UI Review

**Verdict:** PASS|FOLLOW_UP|BLOCKED

## UI Review Summary

- Phase, reviewed UI surface, baseline, overall score out of 24, visual-evidence posture, execution mode, and concise verdict rationale.

## Evidence Reviewed

- Saved summaries, UI spec, plans or context when available, validation or UAT evidence, screenshots or visual observations when available, repo paths, and unavailable evidence that limits confidence.

## Pillar Scores

| Pillar | Score | Evidence | Key Finding |
|---|---:|---|---|
| Copywriting | 1-4/4 | Saved artifact or repo path. | One-line finding or pass signal. |
| Visual Hierarchy | 1-4/4 | Saved artifact, screenshot, or repo path. | One-line finding or pass signal. |
| Color | 1-4/4 | Saved artifact, screenshot, or repo path. | One-line finding or pass signal. |
| Typography | 1-4/4 | Saved artifact, screenshot, or repo path. | One-line finding or pass signal. |
| Spacing | 1-4/4 | Saved artifact, screenshot, or repo path. | One-line finding or pass signal. |
| Experience Design | 1-4/4 | Saved artifact, screenshot, or repo path. | One-line finding or pass signal. |

## Priority Fixes

1. Specific issue - user impact - concrete repair, or \`none\`.

## Findings

- Pillar-scoped UI issue, score impact, evidence, user impact, and fix or verification guidance, or \`none\`.

## Follow-Ups

- Explicit UI repair, validation step, or \`none\`.

## Audit Trail

- Audit date, existing-review posture, screenshot or visual-runtime evidence status, auditor/fallback path, and score consistency note.

## Next Safe Action

- /blu-progress`;
}

function renderPauseWorkTemplate(context?: ArtifactTemplateContext): string {
  return `---
report_type: pause-work
schema_version: 1
status: paused
timestamp: <ISO-8601 timestamp>
project_status: <project-status>
current_milestone: ${milestone(context)}
current_phase: ${currentPhase(context)}
active_command: ${activeCommand(context)}
---

# Pause Work Handoff

## Current State

<current state paragraph>

## Completed Work

- none

## Remaining Work

- none

## Decisions

- none

## Blockers

- none

## Human Actions Pending

- none

## Modified Files

- none

## Blueprint Snapshot

- Core artifacts: none
- Phase artifacts: none
- Existing reports: none
- Missing artifacts: none

## Next Action

<next safe action>

## Context Notes

<context notes>`;
}

function renderMilestoneAuditTemplate(context?: ArtifactTemplateContext): string {
  return `# Milestone ${milestone(context)} - Audit

**Verdict:** READY_TO_CLOSE|FOLLOW_UP|BLOCKED
**Evidence Dimensions:** roadmap, validation, UAT, carry-forward

## Audit Verdict

- Verdict: READY_TO_CLOSE|FOLLOW_UP|BLOCKED
- Rationale: <why the milestone can or cannot close>
- Decision basis: <which evidence determined the verdict>

## Milestone Evidence Dimensions

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Roadmap intent | <roadmap evidence> | PASS|GAP|BLOCKED | <what the roadmap evidence proves> |
| Validation evidence | <validation evidence> | PASS|GAP|BLOCKED | <what the verification evidence proves> |
| UAT evidence | <uat evidence> | PASS|GAP|BLOCKED | <what the UAT evidence proves> |
| Carry-forward evidence | <carry-forward evidence> | PASS|GAP|BLOCKED | <what the closeout evidence proves> |

## Original Intent Snapshot

- Locked milestone intent and source evidence.

## Roadmap And Phase Evidence

- Completed phase evidence reviewed for this milestone.

## Requirement Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Integration Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Flow Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Optional Gaps

| Gap ID | Surface | Evidence | Repair |
|--------|---------|----------|--------|
| none | none | none | none |

## Gaps Found

- Requirement gaps: none
- Integration gaps: none
- Flow gaps: none
- Optional gaps: none

## Archival Blockers

- Explicit blocker or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderMilestoneCompleteTemplate(context?: ArtifactTemplateContext): string {
  return `# Milestone ${milestone(context)} - Completion

**Decision:** READY_TO_CLOSE|FOLLOW_UP|BLOCKED
**Audit Report Used:** <saved milestone audit report path>
**Evidence Ledger:** <roadmap, validation, UAT, carry-forward evidence ledger>

## Completion Decision

- Decision: READY_TO_CLOSE|FOLLOW_UP|BLOCKED
- Rationale: <why the milestone can or cannot close>
- Closeout basis: <which saved evidence determined the decision>

## Audit Report Used

- <saved milestone audit report path>

## Milestone Evidence Ledger

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Roadmap intent | <roadmap evidence> | PASS|GAP|BLOCKED | <what the roadmap evidence proves> |
| Validation evidence | <validation evidence> | PASS|GAP|BLOCKED | <what the verification evidence proves> |
| UAT evidence | <uat evidence> | PASS|GAP|BLOCKED | <what the UAT evidence proves> |
| Carry-forward evidence | <carry-forward evidence> | PASS|GAP|BLOCKED | <what the closeout evidence proves> |

## Residual Watch Items

- <remaining watch item or none>

## Next Safe Action

- /blu-milestone-summary`;
}

function renderMilestoneSummaryTemplate(context?: ArtifactTemplateContext): string {
  return `# Milestone ${milestone(context)} - Summary

**Sources Reviewed:** <saved audit report, completion report, and roadmap evidence>
**Evidence Ledger:** <audit, completion, roadmap, carry-forward evidence ledger>
**Carry-Forward Context:** <seed context for /blu-new-milestone>

## Scope Summary

- Concise milestone scope and outcome summary grounded in saved reports.

## Source Reports Used

- <saved milestone audit report path>
- <saved milestone completion report path>

## Milestone Evidence Ledger

| Dimension | Evidence | Status | Notes |
|-----------|----------|--------|-------|
| Audit report | <audit report evidence> | PASS|GAP|BLOCKED | <what the audit report proves> |
| Completion report | <completion report evidence> | PASS|GAP|BLOCKED | <what the completion report proves> |
| Roadmap context | <roadmap evidence> | PASS|GAP|BLOCKED | <what the roadmap evidence proves> |
| Carry-forward context | <carry-forward evidence> | PASS|GAP|BLOCKED | <what the carry-forward evidence proves> |

## Shipped Outcomes

- <major delivered outcome>

## Deferred Follow-Ups

- <deferred item or none>

## Recommended Carry-Forward Context

- <context that should seed the next milestone>

## Next Safe Action

- /blu-new-milestone`;
}

function renderDebugTemplate(): string {
  return `# Debug Report

## Problem Statement

- What broke, where it appears, and why it matters.

## Evidence Collected

- Logs, traces, artifacts, or cited repo evidence.

## Hypotheses

- Ranked explanation or \`none\`.

## Actions Taken

- Investigation or fix attempt performed.

## Next Safe Action

- /blu-progress`;
}

function renderQuickRunTemplate(): string {
  return `# Quick Run Report

## Task Summary

- Why the task qualified as a bounded quick run.

## Changes Made

- Concrete repo or Blueprint changes completed.

## Verification

- Checks run or evidence gathered, or \`none\`.

## Follow-Ups

- Remaining work or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderDocsUpdateTemplate(): string {
  return `# Docs Update Report

## Requested Docs Scope

- Requested docs surface and why it was selected.

## Changes Made

- Docs created or updated.

## Verification

- Validation performed against code or repo evidence, or \`none\`.

## Follow-Ups

- Remaining docs task or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderPrBranchTemplate(): string {
  return `# PR Branch Report

## Source Branch

- Base branch: <base branch>
- Source branch: <source branch>
- Source HEAD: <commit sha>
- Config used: git.base_branch=<value>; git.branching_strategy=<value>; planning.commit_docs=<true|false>

## Review Branch

- Candidate branch: <candidate review branch>
- Created branch: <created review branch or not created>
- Current branch after run: <current branch after validation>
- Execution mode: <preview-only|confirmed-replay|blocked>
- Git commands approved: <commands or none>

## Filtered Scope

- .blueprint policy: <excluded|included> because <reason>
- Digest inputs used: <inputsUsed from blueprint_artifact_summary_digest>
- Included paths: <repo-relative paths or none>
- Excluded paths: <repo-relative paths or none>

| Commit | Subject | Classification | Action | Filtered paths | Reason |
|---|---|---|---|---|---|
| <sha> | <subject> | <code-only|blueprint-only|mixed|empty-after-filter> | <include|exclude|skip> | <paths or none> | <reason> |

## Verification

- Clean review branch status: <command and result>
- Excluded .blueprint file count in review diff: <count>
- Total files in review diff: <count>
- Review branch commits ahead of base: <count>
- Recovery or blocker: <none or blocker>

## Next Safe Action

- <manual push/PR guidance or /blu-progress>`;
}

function renderShipTemplate(): string {
  return `# Ship Report

## Selected Scope

- Branch, commits, or review scope selected for shipping.

## Branch Plan

- Push or PR plan that was attempted.

## Push Or PR Outcome

- Actual push or PR outcome, or \`none\`.

## Manual Fallback Guidance

- Manual next step when remote shipping did not complete.

## Next Safe Action

- /blu-progress`;
}

function renderUndoTemplate(): string {
  return `# Undo Report

## Requested Scope

- Approved undo target and why it was selected.

## Candidate Revert Set

- Commits, files, or artifacts that are part of the undo scope.

## Dependency Impact

- Dependency or follow-on risk from the undo.

## Mutation Outcome

- Result of the undo operation or \`pending\`.

## Next Safe Action

- /blu-progress`;
}

function renderCleanupTemplate(): string {
  return `# Cleanup Report

## Selected Phase Directories

- Phase directories selected for cleanup.

## Protected Exclusions

- Protected files or exclusions that were preserved.

## Archive Destination

- Archive path or destination used.

## Mutation Outcome

- Actual cleanup result or \`pending\`.

## Next Safe Action

- /blu-progress`;
}

function renderAddTestsTemplate(context?: ArtifactTemplateContext): string {
  return `# Add Tests Report

## Coverage Goal

- Phase ${phasePrefix(context)} coverage gap selected for this pass.
- Approved test scope and why it is the narrowest safe scope.

## Evidence Used

- Saved summaries reviewed.
- Verification or UAT artifacts reviewed.
- Existing test conventions, nearby coverage, and target command discovered.

## Classification And Test Plan

| Surface | Classification | Reason | Planned Test |
|---------|----------------|--------|--------------|
| <repo-relative path or behavior> | <Unit / TDD, Integration / API, E2E / UI, or Skip> | <why this classification fits> | <test case, scenario, or skip rationale> |

- Approval status: <approved, adjusted, inferred from explicit user scope, or blocked>.

## Tests Added Or Updated

- Test files or suites changed.
- Targeted command: <command run or blocked prerequisite>.
- Result counts: generated <N>, passing <N>, failing <N>, blocked <N>.
- Bugs or blockers discovered: <implementation bug, test-authoring issue repaired, blocked prerequisite, or none>.

## Remaining Gaps

- Explicit remaining coverage gap, deferred/manual-only area, failed generated test, blocked prerequisite, or \`none\`.
- Verification write status: <created, updated, reused, invalid, or blocked>.
- Report write status: <created, updated, reused, invalid, or blocked>.

## Next Safe Action

- /blu-progress`;
}

function renderAuditFixTemplate(context?: ArtifactTemplateContext): string {
  return `# Audit Fix Report

## Evidence Used

- Saved review, verification, UAT, or security artifacts selected for phase ${phasePrefix(context)}.
- Scoped repo files reviewed: <repo-relative files or none>.
- Pre-fix HEAD: <sha or unknown>.

## Fix Scope

- Source/severity/max/dry-run settings.
- Classification table with finding id, evidence source, severity, classification, reason, implicated files, and narrow verification.

## Changes Applied

- Applied fixes, failed attempts, dry-run-only plans, verification checks, commit SHA(s), rollback status, or \`none\`.

## Remaining Gaps

- Manual-only findings, skipped findings, unattempted candidates, stale evidence, todo decisions, stop reason, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderImpactTemplate(context?: ArtifactTemplateContext): string {
  const name = reportName(context, "impact-<scope-fingerprint>");

  return `# Impact Report: ${name}

## Summary

- Status, risk, confidence, and one concise evidence-backed outcome.
- Impact drivers, impact reducers, and confidence factors.

## Change Scope

- Scope kind, source, fingerprint, description, and repo-relative changed files.
- Explain non-file-backed scope limitations when applicable.

## Top Impacted Areas

- Area summaries with file counts and file paths.

## Required Reviewers

- Reviewers derived from ownership evidence or an explicit reason no reviewer was derived.

## Required Tests

- Tests derived from test obligations or an explicit reason no test obligation was derived.

## Blocking Findings

- BLOCK findings with severity, evidence refs, and required actions, or an explicit reason none were found.

## Warnings

- WARN findings and non-blocking obligations with evidence refs, or an explicit reason none were found.

## Contract And Compatibility Impact

- Command, MCP, artifact-contract, skill, agent, extension, hook, or runtime-reference impact, or an explicit reason none was detected.

## Database, Config, Infra, And Deployment Impact

- Database, migration, config, infra, package, build, deployment, environment, and secret-sensitive impact, or an explicit reason none was detected.

## Unknowns And Missing Metadata

- Unknown ids with category, severity, why it matters, resolution, and evidence refs, or an explicit reason none remain.

## Evidence

- Evidence ids with kind, source, summary, paths, and relevant metadata.

## Suggested Next Actions

- Follow-up actions derived from findings, obligations, and unknowns, or an explicit reason no action remains.`;
}

const ARTIFACT_CONTRACTS: Record<ArtifactContractId, ArtifactContractDefinition> = {
  "bootstrap.project": {
    id: "bootstrap.project",
    scope: "bootstrap",
    ownerTool: "blueprint_project_init",
    pathOwner: "blueprint_project_init",
    canonicalName: "Project Bootstrap",
    canonicalFilePattern: ".blueprint/PROJECT.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Vision",
      "Audience",
      "Constraints",
      "Current Milestone",
      "Bootstrap Shape",
      "Scope Posture",
      "Non-Goals",
      "Assumptions"
    ],
    lockedMarkers: [],
    placeholderSignals: [
      "<project name>",
      "<project vision>",
      "<primary audience>",
      "<secondary audience>",
      "<constraint>",
      "<current milestone>",
      "<bootstrap posture>",
      "<requirement ids or none>",
      "<non-goal>",
      "<assumption>"
    ],
    notes: [
      "Project bootstrap should capture the product direction, milestone framing, and durable scope posture before later lifecycle commands run.",
      "Validation expects substantive content in the audience, constraints, scope posture, non-goals, and assumptions sections."
    ],
    renderScaffoldTemplate: renderBootstrapProjectTemplate,
    renderAuthoringTemplate: renderBootstrapProjectTemplate
  },
  "bootstrap.requirements": {
    id: "bootstrap.requirements",
    scope: "bootstrap",
    ownerTool: "blueprint_project_init",
    pathOwner: "blueprint_project_init",
    canonicalName: "Requirements Bootstrap",
    canonicalFilePattern: ".blueprint/REQUIREMENTS.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Requirements Table",
      "Scope Summary",
      "Committed V1 Scope",
      "Deferred Scope",
      "Out-of-Scope Cuts",
      "Traceability Notes",
      "Open Questions"
    ],
    lockedMarkers: [],
    placeholderSignals: [
      "<project name>",
      "<requirement-id>",
      "<requirement>",
      "<notes>",
      "<group>",
      "<open question>"
    ],
    notes: [
      "Requirements bootstrap should keep requirement IDs durable, grouped, and traceable into the roadmap.",
      "Validation expects a populated requirements table plus substantive committed, deferred, and out-of-scope sections."
    ],
    renderScaffoldTemplate: renderBootstrapRequirementsTemplate,
    renderAuthoringTemplate: renderBootstrapRequirementsTemplate
  },
  "bootstrap.roadmap": {
    id: "bootstrap.roadmap",
    scope: "bootstrap",
    ownerTool: "blueprint_project_init",
    pathOwner: "blueprint_project_init",
    canonicalName: "Roadmap Bootstrap",
    canonicalFilePattern: ".blueprint/ROADMAP.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Milestone",
      "Bootstrap Status",
      "Requirement Coverage",
      "Phases",
      "Notes"
    ],
    lockedMarkers: [],
    placeholderSignals: [
      "<project name>",
      "<milestone>",
      "<phase title>",
      "<phase objective>",
      "<success criterion>",
      "<bootstrap assumption>"
    ],
    notes: [
      "Roadmap bootstrap should keep phase ordering, requirement coverage, and confidence posture visible.",
      "Validation expects at least one concrete phase entry with objective, requirement mapping, and success criteria."
    ],
    renderScaffoldTemplate: renderBootstrapRoadmapTemplate,
    renderAuthoringTemplate: renderBootstrapRoadmapTemplate
  },
  "codebase.stack": {
    id: "codebase.stack",
    scope: "codebase",
    ownerTool: "blueprint_codebase_artifact_write",
    pathOwner: "blueprint_codebase_artifact_write",
    canonicalName: "Codebase Stack",
    canonicalFilePattern: ".blueprint/codebase/STACK.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Purpose", "Runtime", "Tooling", "Dependencies", "Notes"],
    lockedMarkers: [],
    placeholderSignals: [
      "<runtime>",
      "<module system>",
      "<package manager>",
      "<build command>",
      "<test command>",
      "<lint or format command>",
      "<core dependencies>",
      "<dev dependencies>",
      "<tooling notes>",
      "<stack note>",
      "Generated by `blueprint_artifact_scaffold`",
      "Generated by `/blu-map-codebase`"
    ],
    notes: [
      "Stack mapping should record the runtime, package manager, build/test commands, and dependency profile confirmed by repo evidence.",
      "The scaffold template is intentionally placeholder-heavy so scaffold-only output never counts as a completed mapping."
    ],
    renderScaffoldTemplate: () => renderCodebaseStackTemplate(undefined, { footer: true }),
    renderAuthoringTemplate: renderCodebaseStackTemplate
  },
  "codebase.architecture": {
    id: "codebase.architecture",
    scope: "codebase",
    ownerTool: "blueprint_codebase_artifact_write",
    pathOwner: "blueprint_codebase_artifact_write",
    canonicalName: "Codebase Architecture",
    canonicalFilePattern: ".blueprint/codebase/ARCHITECTURE.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Purpose", "Overview", "Boundaries", "Flow", "Notes"],
    lockedMarkers: [],
    placeholderSignals: [
      "<overview>",
      "<boundary note>",
      "<boundary>",
      "<entry points>",
      "<flow summary>",
      "<architecture note>",
      "Generated by `blueprint_artifact_scaffold`",
      "Generated by `/blu-map-codebase`"
    ],
    notes: [
      "Architecture mapping should capture the execution model, subsystem boundaries, and high-level data flow.",
      "The scaffold template should remain obviously incomplete until the content is replaced with real repo evidence."
    ],
    renderScaffoldTemplate: () => renderCodebaseArchitectureTemplate(undefined, { footer: true }),
    renderAuthoringTemplate: renderCodebaseArchitectureTemplate
  },
  "codebase.structure": {
    id: "codebase.structure",
    scope: "codebase",
    ownerTool: "blueprint_codebase_artifact_write",
    pathOwner: "blueprint_codebase_artifact_write",
    canonicalName: "Codebase Structure",
    canonicalFilePattern: ".blueprint/codebase/STRUCTURE.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Purpose", "Directory Map", "Key Files", "Seams", "Notes"],
    lockedMarkers: [],
    placeholderSignals: [
      "<directory>",
      "<purpose>",
      "<file path>",
      "<seam>",
      "<structure note>",
      "Generated by `blueprint_artifact_scaffold`",
      "Generated by `/blu-map-codebase`"
    ],
    notes: [
      "Structure mapping should make the repo layout and important file seams easy to navigate.",
      "Populate the directory map and key files with repo-specific evidence instead of generic placeholders."
    ],
    renderScaffoldTemplate: () => renderCodebaseStructureTemplate(undefined, { footer: true }),
    renderAuthoringTemplate: renderCodebaseStructureTemplate
  },
  "codebase.conventions": {
    id: "codebase.conventions",
    scope: "codebase",
    ownerTool: "blueprint_codebase_artifact_write",
    pathOwner: "blueprint_codebase_artifact_write",
    canonicalName: "Codebase Conventions",
    canonicalFilePattern: ".blueprint/codebase/CONVENTIONS.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Purpose", "Naming", "Module Boundaries", "Error Handling", "Documentation", "Notes"],
    lockedMarkers: [],
    placeholderSignals: [
      "<naming convention>",
      "<naming detail>",
      "<boundary rule>",
      "<error handling pattern>",
      "<error handling detail>",
      "<documentation convention>",
      "<documentation location>",
      "<convention note>",
      "Generated by `blueprint_artifact_scaffold`",
      "Generated by `/blu-map-codebase`"
    ],
    notes: [
      "Conventions mapping should describe durable naming, module boundary, error handling, and documentation practices.",
      "The contract favors repo-specific conventions over generic style guidance."
    ],
    renderScaffoldTemplate: () => renderCodebaseConventionsTemplate(undefined, { footer: true }),
    renderAuthoringTemplate: renderCodebaseConventionsTemplate
  },
  "codebase.testing": {
    id: "codebase.testing",
    scope: "codebase",
    ownerTool: "blueprint_codebase_artifact_write",
    pathOwner: "blueprint_codebase_artifact_write",
    canonicalName: "Codebase Testing",
    canonicalFilePattern: ".blueprint/codebase/TESTING.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Purpose", "Framework", "Commands", "Coverage", "Notes"],
    lockedMarkers: [],
    placeholderSignals: [
      "<runner>",
      "<assertion stack>",
      "<test command>",
      "<focused command>",
      "<coverage signal>",
      "<coverage gap>",
      "<testing note>",
      "Generated by `blueprint_artifact_scaffold`",
      "Generated by `/blu-map-codebase`"
    ],
    notes: [
      "Testing mapping should capture the runnable test surface and any coverage gaps that still need attention.",
      "Preserve the actual commands and framework signals that were confirmed in the repo."
    ],
    renderScaffoldTemplate: () => renderCodebaseTestingTemplate(undefined, { footer: true }),
    renderAuthoringTemplate: renderCodebaseTestingTemplate
  },
  "codebase.integrations": {
    id: "codebase.integrations",
    scope: "codebase",
    ownerTool: "blueprint_codebase_artifact_write",
    pathOwner: "blueprint_codebase_artifact_write",
    canonicalName: "Codebase Integrations",
    canonicalFilePattern: ".blueprint/codebase/INTEGRATIONS.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Purpose", "External Systems", "SDKs And APIs", "Authentication And Secrets", "Notes"],
    lockedMarkers: [],
    placeholderSignals: [
      "<system>",
      "<sdk or api>",
      "<integration detail>",
      "<auth detail>",
      "<integration note>",
      "Generated by `blueprint_artifact_scaffold`",
      "Generated by `/blu-map-codebase`"
    ],
    notes: [
      "Integrations mapping should call out third-party systems, SDKs, APIs, and secret-handling assumptions.",
      "The file should stay grounded in observed repo evidence, not guessed integrations."
    ],
    renderScaffoldTemplate: () => renderCodebaseIntegrationsTemplate(undefined, { footer: true }),
    renderAuthoringTemplate: renderCodebaseIntegrationsTemplate
  },
  "codebase.concerns": {
    id: "codebase.concerns",
    scope: "codebase",
    ownerTool: "blueprint_codebase_artifact_write",
    pathOwner: "blueprint_codebase_artifact_write",
    canonicalName: "Codebase Concerns",
    canonicalFilePattern: ".blueprint/codebase/CONCERNS.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Purpose", "Risks", "Gaps", "Follow-Ups", "Questions", "Notes"],
    lockedMarkers: [],
    placeholderSignals: [
      "<risk>",
      "<gap>",
      "<follow-up>",
      "<question>",
      "<concern note>",
      "Generated by `blueprint_artifact_scaffold`",
      "Generated by `/blu-map-codebase`"
    ],
    notes: [
      "Concerns mapping should preserve unresolved risks, thin areas, and the follow-up questions that matter for future work.",
      "Do not treat a placeholder-only concerns file as a completed brownfield mapping artifact."
    ],
    renderScaffoldTemplate: () => renderCodebaseConcernsTemplate(undefined, { footer: true }),
    renderAuthoringTemplate: renderCodebaseConcernsTemplate
  },
  "phase.context": {
    id: "phase.context",
    scope: "phase",
    ownerTool: "blueprint_phase_artifact_write",
    pathOwner: "blueprint_phase_artifact_write",
    canonicalName: "Phase Context",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-CONTEXT.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Phase Boundary",
      "Discovery Grounding",
      "Implementation Decisions",
      "Specific Ideas",
      "Existing Code Insights",
      "Dependencies",
      "Open Questions",
      "Deferred Ideas",
      "Canonical References"
    ],
    lockedMarkers: [],
    placeholderSignals: [
      "Goal:",
      "In scope:",
      "Out of scope:",
      "Success criteria:",
      "Project brief:",
      "Requirements grounding:",
      "Workflow posture:",
      "Confirmed decisions:",
      "<implementation decision 1>",
      "<tradeoff or constraint>",
      "<specific idea 1>",
      "<specific idea 2>",
      "<later follow-up>",
      "<existing code insight 1>",
      "<reusable pattern>",
      "<gap or caution>",
      "<prior phase artifacts>",
      "<external constraints>",
      "<required follow-up reads>",
      "<open question 1>",
      "<deferred idea>",
      "<source 1>"
    ],
    notes: [
      "Discovery context is phase-scoped and MCP-owned.",
      "Write validation requires an H1 title, removal of scaffold placeholders, and the richer discuss-phase context sections that feed downstream planning."
    ],
    renderScaffoldTemplate: renderContextTemplate,
    renderAuthoringTemplate: renderContextTemplate
  },
  "phase.discussion-log": {
    id: "phase.discussion-log",
    scope: "phase",
    ownerTool: "blueprint_phase_artifact_write",
    pathOwner: "blueprint_phase_artifact_write",
    canonicalName: "Phase Discussion Log",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-DISCUSSION-LOG.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Summary", "Notes", "Follow-Ups"],
    lockedMarkers: [],
    placeholderSignals: [
      "Record the major discussion outcomes and unresolved questions here.",
      "Timestamped notes:",
      "Follow-up 1:"
    ],
    notes: [
      "Discussion logs are optional supporting artifacts.",
      "Write validation requires an H1 title, removal of scaffold placeholders, and at least one populated contract section."
    ],
    renderScaffoldTemplate: renderDiscussionLogTemplate,
    renderAuthoringTemplate: renderDiscussionLogTemplate
  },
  "phase.research": {
    id: "phase.research",
    scope: "phase",
    ownerTool: "blueprint_phase_artifact_write",
    pathOwner: "blueprint_phase_artifact_write",
    canonicalName: "Phase Research",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-RESEARCH.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Phase Requirements",
      "Summary",
      "Locked Decisions From Context",
      "User Constraints",
      "Standard Stack",
      "Installation And Setup",
      "Alternatives Considered",
      "Architecture Patterns",
      "Don't Hand-Roll",
      "Anti-Patterns",
      "State Of The Art",
      "Common Pitfalls",
      "Open Questions",
      "Confidence Breakdown",
      "Code Examples",
      "Recommendations",
      "Sources"
    ],
    lockedMarkers: ["**Confidence:**"],
    placeholderSignals: [
      "Phase XX:",
      "<Phase Name>",
      "<YYYY-MM-DD>",
      "<research domain>",
      "<requirement-id>",
      "<phase requirement>",
      "<evidence-backed guidance>",
      "<key conclusion>",
      "<phase decision preserved from context>",
      "<repo, product, or workflow constraint>",
      "<runtime, library, or shared repo pattern>",
      "<installation or setup guidance>",
      "<alternative considered and tradeoff>",
      "<durable implementation pattern>",
      "<existing tool, helper, or platform feature>",
      "<anti-pattern detail or implementation to avoid>",
      "<current ecosystem or repo update with source date YYYY-MM-DD, or say not externally checked>",
      "<failure mode or regression risk>",
      "<open question that still needs an answer>",
      "<topic>",
      "<evidence-backed confidence explanation>",
      "<short code or pseudocode example>",
      "<prescriptive recommendation with tradeoffs>",
      "<repo path, URL, or cited file reference>"
    ],
    notes: [
      "Research writes validate in strict mode by default.",
      "Additional top-level headings are allowed, but required headings and the confidence marker stay locked.",
      "Drafting should use the canonical authoring template from blueprint_artifact_contract_read before any rewrite or persistence step.",
      "Research should preserve planner-grade evidence density: mapped requirements, prescriptive recommendations, repo-versus-external provenance, confidence by topic, and explicit open questions when evidence is incomplete.",
      "State Of The Art should cite explicit source dates for freshness-sensitive claims, or say that external currency was not checked."
    ],
    renderScaffoldTemplate: (context) => withScaffoldFooter(renderResearchTemplate(context)),
    renderAuthoringTemplate: renderResearchTemplate
  },
  "phase.ui-spec": {
    id: "phase.ui-spec",
    scope: "phase",
    ownerTool: "blueprint_phase_artifact_write",
    pathOwner: "blueprint_phase_artifact_write",
    canonicalName: "Phase UI Spec",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-UI-SPEC.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Outcome Mode",
      "User Experience Goals",
      "Visual Design Decisions",
      "Screens And States",
      "Components And Constraints",
      "Accessibility And Content",
      "Registry And Design-System Safety",
      "Next Safe Action"
    ],
    lockedMarkers: [],
    placeholderSignals: [
      "Choose one: UI contract or explicit skip rationale.",
      "- For Explicit skip rationale, explain why UI work is out of scope, note any safety-gate implications, and name a revisit trigger. Delete this section for UI contract mode.",
      "Goal 1: <primary UX objective for this phase>",
      "Primary user outcome: <the user-facing outcome this phase must improve>",
      "Evidence sources: <requirements, context, research, roadmap, or codebase paths used>",
      "Design-system evidence: <existing components, tokens, styles, or `none`, with repo paths when known>",
      "Spacing and layout: <grid, rhythm, or layout constraints>",
      "Typography: <type scale, emphasis, or readability decisions>",
      "Color and contrast: <palette, semantic color, and contrast rules>",
      "Motion and feedback: <loading, hover, or transition guidance>",
      "Copy and content: <voice, terminology, and label constraints>",
      "Typography limits: <3-4 sizes, no more than 2 weights, and line-height rules>",
      "Color hierarchy: <60/30/10 role split or repo-derived equivalent plus accent reserved-for list>",
      "Copywriting contract: <primary CTA, empty state, error state, destructive confirmation>",
      "Screen/state 1: <named screen or state in scope>",
      "Loading, empty, error, and success states: <required state behavior>",
      "Responsive behavior: <desktop, tablet, and mobile expectations>",
      "Visual hierarchy and focal point: <what draws attention first and why>",
      "Component 1: <component, pattern, or surface in scope>",
      "Existing design-system or registry primitives to reuse: <existing primitives or `none`>",
      "New component or token justification: <new primitives needed or `none`>",
      "Density and interaction constraints: <layout density, touch targets, or gesture rules>",
      "Component inventory evidence: <repo paths, registry entries, or `none`>",
      "Accessibility note 1: <keyboard, focus, contrast, or assistive-tech guidance>",
      "Content hierarchy and empty-state guidance: <content hierarchy and empty-state behavior>",
      "Localization or content safety notes: <localization, moderation, or terminology notes>",
      "Registry and design-system safety: <how the draft avoids forking the registry or design system>",
      "Token and theming compatibility: <token, theme, or brand-system compatibility notes>",
      "Revisit trigger if the scope changes: <when this contract must be revisited>",
      "Third-party registry safety evidence: <view passed, developer-approved after review, blocked, or not applicable>",
      "Copywriting: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>",
      "Visual hierarchy: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>",
      "Color: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>",
      "Typography: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>",
      "Spacing: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>",
      "Registry and design-system safety: <PASS, FLAG, BLOCK, or not yet reviewed, with evidence>"
    ],
    notes: [
      "The same durable artifact covers both a real UI contract and an explicit skip rationale.",
      "Write validation requires an H1 title and Outcome Mode; explicit skip rationale may use a populated `## Rationale` section instead of the full UI contract.",
      "The canonical authoring template includes an optional `## Rationale` branch for skip mode; remove it when the artifact stays in full UI-contract mode.",
      "A real UI contract must lock concrete visual and UX decisions before planning, including spacing, typography, color, copy/content, state behavior, and registry or design-system safety.",
      "The authoring template is the heading authority; `skills/blueprint-phase-discovery/references/ui-phase-runtime-contract.md` is the richness, evidence, fallback, and retry authority.",
      "Checker review should cover the six UI dimensions: copywriting, visual hierarchy, color, typography, spacing, and registry or design-system safety."
    ],
    renderScaffoldTemplate: (context) => withScaffoldFooter(renderUiSpecTemplate(context)),
    renderAuthoringTemplate: renderUiSpecTemplate
  },
  "phase.plan": {
    id: "phase.plan",
    scope: "phase",
    ownerTool: "blueprint_phase_plan_write",
    pathOwner: "blueprint_phase_plan_write",
    canonicalName: "Phase Plan",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-YY-PLAN.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Goal", "Scope", "Tasks", "Verification", "Must Haves"],
    lockedMarkers: [
      "phase:",
      "plan_id:",
      "title:",
      "wave:",
      "status:",
      "objective:",
      "depends_on:",
      "requirements:",
      "files_modified:",
      "read_first:",
      "acceptance_criteria:",
      "autonomous:"
    ],
    placeholderSignals: [
      "Replace with a concrete, execution-ready goal.",
      "Replace with the exact requirement IDs this plan addresses.",
      "Replace with the real repo paths the executor must touch.",
      "Replace with grep/test-verifiable acceptance criteria."
    ],
    notes: [
      "Plan frontmatter keys and task subsections are locked for MCP parsing.",
      "Optional `gap_closure: true` frontmatter marks an explicit gap-closure plan for `--gaps-only` execution targeting.",
      "Additional top-level headings are allowed, but required plan sections must remain unchanged.",
      "Plan authoring should stay execution-ready: exact repo-relative `Read First` paths, concrete target-state `Action` text, grep/test/CLI/file-read-verifiable `Acceptance Criteria`, and goal-backward must-haves with observable truths, required artifacts, and key links.",
      "Use concrete repo-relative paths in `files_modified`, `read_first`, and task `Read First`; keep endpoint routes, command globs, and code snippets in `Action` or `Acceptance Criteria` rather than path-list positions.",
      "Do not silently reduce locked context decisions with `v1`, placeholder, static-for-now, future-wiring, or stub language; split or block when full fidelity does not fit."
    ],
    renderScaffoldTemplate: (context) => withScaffoldFooter(renderPlanTemplate(context)),
    renderAuthoringTemplate: renderPlanTemplate
  },
  "phase.summary": {
    id: "phase.summary",
    scope: "phase",
    ownerTool: "blueprint_phase_summary_write",
    pathOwner: "blueprint_phase_summary_write",
    canonicalName: "Phase Summary",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-YY-SUMMARY.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Outcome", "Changes Made", "Verification", "Follow-Ups", "Evidence"],
    lockedMarkers: ["**Plan:**", "**Status:**"],
    placeholderSignals: [
      "COMPLETED|PARTIAL|BLOCKED",
      "Concise delivery summary grounded in the completed work.",
      "Explicit code, config, or artifact changes completed for this plan.",
      "Command, test, or evidence that supports the reported outcome.",
      "Remaining gap, handoff, or `none`.",
      "or other saved repo evidence if helpful."
    ],
    notes: [
      "Summary artifacts stay linked to a saved plan and should remain grounded in completed work.",
      "The locked `Plan` and `Status` markers remain required, but scaffold placeholder values are rejected by write validation.",
      "`COMPLETED` is the only status that closes execution debt; `PARTIAL` and `BLOCKED` are truthful carry-forward evidence and remain pending.",
      "Untouched scaffold prose in Changes Made, Verification, Follow-Ups, and Evidence is also rejected."
    ],
    renderScaffoldTemplate: renderSummaryTemplate,
    renderAuthoringTemplate: renderSummaryTemplate
  },
  "phase.verification": {
    id: "phase.verification",
    scope: "phase",
    ownerTool: "blueprint_phase_validation_write",
    pathOwner: "blueprint_phase_validation_write",
    canonicalName: "Phase Verification",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-VERIFICATION.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Validation Summary",
      "Requirement / Task Coverage",
      "Evidence Reviewed",
      "Test Infrastructure / Evidence Metadata",
      "Manual-Only or Deferred Coverage",
      "Gate State",
      "Gap Classification",
      "Gaps Found",
      "Suggested Repairs",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Coverage:**", "**Gate State:**", "**Sign-off:**"],
    placeholderSignals: [
      "PASS|PARTIAL|BLOCKED",
      "verified|pending|blocked",
      "PASS|MANUAL|DEFERRED|BLOCKED",
      "MANUAL|DEFERRED|NONE",
      "<implemented next action",
      "Concise readiness result grounded in the saved summaries."
    ],
    notes: [
      "Verification artifacts must stay grounded in saved execution summaries and preserve durable coverage state.",
      "Requirement-to-task mapping, evidence metadata, manual or deferred coverage, and gap classification should remain visible in the saved artifact.",
      "Additional top-level headings are allowed, but evidence reviewed should still cite saved summaries."
    ],
    renderScaffoldTemplate: renderVerificationTemplate,
    renderAuthoringTemplate: renderVerificationTemplate
  },
  "phase.uat": {
    id: "phase.uat",
    scope: "phase",
    ownerTool: "blueprint_phase_validation_write",
    pathOwner: "blueprint_phase_validation_write",
    canonicalName: "Phase UAT",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-UAT.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "UAT Summary",
      "Session State",
      "Current Test",
      "Test Matrix",
      "Result Summary",
      "Questions Asked",
      "Observed Behavior",
      "Unresolved Gaps",
      "Structured Gaps",
      "Follow-Up Fixes",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Status:**", "**Resume State:**", "**Checkpoint:**"],
    placeholderSignals: [
      "PASS|FAIL|PARTIAL",
      "RESUMED|NEW|CONTINUED",
      "<saved checkpoint path or none>",
      "<saved summary path, checkpoint, or none>",
      "<what is being resumed now>",
      "<what must remain stable between sessions>",
      "<active test number or testing complete>",
      "<active user-observable test name or none>",
      "<what the user should observe>",
      "<user response, next checkpoint, or none>",
      "<test name>",
      "<observable expected behavior>",
      "pending|pass|issue|skipped|blocked",
      "<note>",
      "<N>",
      "<test number or none>",
      "<expected behavior>",
      "failed|partial|blocked|none",
      "blocker|major|minor|cosmetic|none",
      "<verbatim report or blocked reason>",
      "<repair or confirmation path>"
    ],
    notes: [
      "UAT artifacts stay resumable across sessions and must reference saved summaries inside UAT Summary, Session State, or Observed Behavior.",
      "Write validation keeps the resume checkpoint and current session state explicit so the artifact can be safely continued after a pause.",
      "Saved UAT must include the richer current-test, test-matrix, result-summary, and structured-gap sections before it can count as completion evidence."
    ],
    renderScaffoldTemplate: renderUatTemplate,
    renderAuthoringTemplate: renderUatTemplate
  },
  "review.code-review": {
    id: "review.code-review",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "Code Review",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-REVIEW.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Review Summary",
      "Scope Reviewed",
      "Evidence Reviewed",
      "Positive Signals",
      "Severity Summary",
      "Findings",
      "Follow-Ups",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Verdict:**"],
    placeholderSignals: [
      "PASS|FOLLOW_UP|BLOCKED",
      "Phase, effective depth, scope source, file count, verdict rationale, and severity counts.",
      "Repo-relative file path reviewed, one per bullet or table row.",
      "path/to/file.ts:42"
    ],
    notes: [
      "Read the canonical review contract through `blueprint_artifact_contract_read` before drafting or updating review artifacts.",
      "Findings, evidence reviewed, positive signals, and severity counts must remain machine-extractable.",
      "Scope Reviewed must list every repo-relative file in the resolved review scope before the artifact can persist.",
      "Each material finding should include severity, disposition, repo-relative file:line evidence, impact, and concrete fix or verification guidance.",
      "Severity Summary counts must match the persisted Findings section."
    ],
    renderScaffoldTemplate: renderCodeReviewTemplate,
    renderAuthoringTemplate: renderCodeReviewTemplate
  },
  "review.review-fix": {
    id: "review.review-fix",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "Review Fix",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-REVIEW-FIX.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Findings Addressed", "Changes Made", "Verification", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: ["**Status:**"],
    placeholderSignals: ["APPLIED|PARTIAL|SKIPPED"],
    notes: ["Review-fix artifacts summarize bounded remediation only."],
    renderScaffoldTemplate: renderReviewFixTemplate,
    renderAuthoringTemplate: renderReviewFixTemplate
  },
  "review.peer-review": {
    id: "review.peer-review",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "Peer Review",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-REVIEWS.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Review Summary", "Reviewer Results", "Disagreements", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: ["**Reviewers:**"],
    placeholderSignals: ["<reviewer-cli-1>", "<reviewer-cli-2>"],
    notes: ["Preserve reviewer disagreement honestly instead of flattening it."],
    renderScaffoldTemplate: renderPeerReviewTemplate,
    renderAuthoringTemplate: renderPeerReviewTemplate
  },
  "review.security": {
    id: "review.security",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "Security Review",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-SECURITY.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Security Summary",
      "Evidence Reviewed",
      "Threat Register",
      "Accepted Risks",
      "Findings",
      "Follow-Ups",
      "Security Audit Trail",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Posture:**"],
    placeholderSignals: [
      "PASS|FOLLOW_UP|BLOCKED",
      "Concise security posture grounded in saved evidence.",
      "Saved phase artifacts, repo paths, or cited references reviewed.",
      "| T-01 | STRIDE category | component or boundary | mitigate / accept / transfer | declared control or risk decision | closed / accepted / open | File, artifact, or rationale reference. |",
      "Accepted threat reference plus rationale, or `none`.",
      "Open threat, missing control, or risk decision that needs explicit attention, or `none`.",
      "Explicit hardening step, validation gap, or `none`.",
      "Audit date, threat counts, and verifier note."
    ],
    notes: [
      "Security artifacts should distinguish confirmed mitigations from missing controls, keep threat-register dispositions explicit, require threat id/category/component/mitigation/status/evidence coverage, keep accepted-risk and audit-trail context visible, and reject scaffold-only placeholder markers."
    ],
    renderScaffoldTemplate: renderSecurityTemplate,
    renderAuthoringTemplate: renderSecurityTemplate
  },
  "review.ui-review": {
    id: "review.ui-review",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "UI Review",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-UI-REVIEW.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["UI Review Summary", "Evidence Reviewed", "Findings", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: ["**Verdict:**"],
    placeholderSignals: ["PASS|FOLLOW_UP|BLOCKED"],
    notes: [
      "UI review artifacts stay phase-scoped and evidence-backed. Authoring should include scored six-pillar evidence, overall /24 score, priority fixes or explicit pass evidence, visual-evidence limitations, and an audit trail before persistence."
    ],
    renderScaffoldTemplate: renderUiReviewTemplate,
    renderAuthoringTemplate: renderUiReviewTemplate
  },
  "report.impact": {
    id: "report.impact",
    scope: "report",
    ownerTool: "blueprint_impact_report_write",
    pathOwner: "blueprint_impact_report_write",
    canonicalName: "Impact Report",
    canonicalFilePattern: ".blueprint/impact/<impact-id>/IMPACT.md",
    freehandPolicy: "locked-structure",
    requiredHeadings: [
      "Summary",
      "Change Scope",
      "Top Impacted Areas",
      "Required Reviewers",
      "Required Tests",
      "Blocking Findings",
      "Warnings",
      "Contract And Compatibility Impact",
      "Database, Config, Infra, And Deployment Impact",
      "Unknowns And Missing Metadata",
      "Evidence",
      "Suggested Next Actions"
    ],
    lockedMarkers: ["# Impact Report:"],
    placeholderSignals: [
      "<impact-id>",
      "<scope-fingerprint>",
      "<owner>",
      "<test command>",
      "TBD",
      "TODO",
      "N/A"
    ],
    notes: [
      "Impact reports are bounded bundles under .blueprint/impact/<impact-id>/ and are written only through blueprint_impact_report_write.",
      "The writer validates the structured report payload plus rendered Markdown quality before persistence.",
      "/blu-impact is implemented as an advisory command; report writes stay bounded to the impact bundle and do not mutate source, roadmap, PR, deployment, command-catalog, or installed-extension state."
    ],
    renderScaffoldTemplate: renderImpactTemplate,
    renderAuthoringTemplate: renderImpactTemplate
  },
  "report.pause-work": {
    id: "report.pause-work",
    scope: "report",
    ownerTool: "blueprint_pause_handoff_write",
    pathOwner: "blueprint_pause_handoff_write",
    canonicalName: "Pause Work Handoff",
    canonicalFilePattern: ".blueprint/reports/pause-work-latest.md",
    freehandPolicy: "locked-structure",
    requiredHeadings: [
      "Current State",
      "Completed Work",
      "Remaining Work",
      "Decisions",
      "Blockers",
      "Human Actions Pending",
      "Modified Files",
      "Blueprint Snapshot",
      "Next Action",
      "Context Notes"
    ],
    lockedMarkers: [
      "report_type:",
      "schema_version:",
      "status:",
      "timestamp:",
      "project_status:",
      "current_milestone:",
      "current_phase:",
      "active_command:"
    ],
    placeholderSignals: ["<ISO-8601 timestamp>", "<current state paragraph>", "<context notes>"],
    notes: [
      "Pause handoff is machine-parsed and keeps a locked frontmatter plus section contract."
    ],
    renderScaffoldTemplate: renderPauseWorkTemplate,
    renderAuthoringTemplate: renderPauseWorkTemplate
  },
  "report.milestone-audit": {
    id: "report.milestone-audit",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Milestone Audit Report",
    canonicalFilePattern: `.blueprint/reports/${reportName(undefined, "milestone-audit-<milestone>")}.md`,
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Audit Verdict",
      "Milestone Evidence Dimensions",
      "Original Intent Snapshot",
      "Roadmap And Phase Evidence",
      "Requirement Gaps",
      "Integration Gaps",
      "Flow Gaps",
      "Optional Gaps",
      "Gaps Found",
      "Archival Blockers",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Verdict:**", "**Evidence Dimensions:**"],
    placeholderSignals: [
      "<milestone-version>",
      "READY_TO_CLOSE|FOLLOW_UP|BLOCKED",
      "<roadmap evidence>",
      "<validation evidence>",
      "<uat evidence>",
      "<carry-forward evidence>"
    ],
    notes: [
      "Audit-milestone owns this report through blueprint_artifact_report_write.",
      "The audit contract captures a concrete verdict and milestone-level evidence dimensions."
    ],
    renderScaffoldTemplate: renderMilestoneAuditTemplate,
    renderAuthoringTemplate: renderMilestoneAuditTemplate
  },
  "report.milestone-complete": {
    id: "report.milestone-complete",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Milestone Completion Report",
    canonicalFilePattern: ".blueprint/reports/milestone-complete-<milestone>.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Completion Decision",
      "Audit Report Used",
      "Milestone Evidence Ledger",
      "Residual Watch Items",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Decision:**", "**Audit Report Used:**", "**Evidence Ledger:**"],
    placeholderSignals: [
      "<milestone-version>",
      "READY_TO_CLOSE|FOLLOW_UP|BLOCKED",
      "<saved milestone audit report path>",
      "<roadmap, validation, UAT, carry-forward evidence ledger>",
      "<roadmap evidence>",
      "<validation evidence>",
      "<uat evidence>",
      "<carry-forward evidence>"
    ],
    notes: [
      "Complete-milestone owns this report through blueprint_artifact_report_write.",
      "The completion contract captures a closeout decision and an evidence ledger backed by saved reports."
    ],
    renderScaffoldTemplate: renderMilestoneCompleteTemplate,
    renderAuthoringTemplate: renderMilestoneCompleteTemplate
  },
  "report.milestone-summary": {
    id: "report.milestone-summary",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Milestone Summary Report",
    canonicalFilePattern: ".blueprint/reports/milestone-summary-<milestone>.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Scope Summary",
      "Source Reports Used",
      "Milestone Evidence Ledger",
      "Shipped Outcomes",
      "Deferred Follow-Ups",
      "Recommended Carry-Forward Context",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Sources Reviewed:**", "**Evidence Ledger:**", "**Carry-Forward Context:**"],
    placeholderSignals: [
      "<milestone-version>",
      "<saved audit report, completion report, and roadmap evidence>",
      "<audit, completion, roadmap, carry-forward evidence ledger>",
      "<seed context for /blu-new-milestone>",
      "<saved milestone audit report path>",
      "<saved milestone completion report path>",
      "<audit report evidence>",
      "<completion report evidence>",
      "<roadmap evidence>",
      "<carry-forward evidence>"
    ],
    notes: [
      "New-milestone uses this report as the default carry-forward seed.",
      "The summary contract captures the saved milestone sources, evidence ledger, and next milestone handoff context."
    ],
    renderScaffoldTemplate: renderMilestoneSummaryTemplate,
    renderAuthoringTemplate: renderMilestoneSummaryTemplate
  },
  "report.debug": {
    id: "report.debug",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Debug Report",
    canonicalFilePattern: ".blueprint/reports/debug-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Problem Statement", "Evidence Collected", "Hypotheses", "Actions Taken", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Debug reports keep investigative evidence explicit and resumable."],
    renderScaffoldTemplate: renderDebugTemplate,
    renderAuthoringTemplate: renderDebugTemplate
  },
  "report.quick-run": {
    id: "report.quick-run",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Quick Run Report",
    canonicalFilePattern: ".blueprint/reports/quick-run-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Task Summary", "Changes Made", "Verification", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Quick reports capture bounded execution without impersonating saved plans."],
    renderScaffoldTemplate: renderQuickRunTemplate,
    renderAuthoringTemplate: renderQuickRunTemplate
  },
  "report.docs-update": {
    id: "report.docs-update",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Docs Update Report",
    canonicalFilePattern: ".blueprint/reports/docs-update-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Requested Docs Scope", "Changes Made", "Verification", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Docs-update uses this report to capture repo and verification outcomes."],
    renderScaffoldTemplate: renderDocsUpdateTemplate,
    renderAuthoringTemplate: renderDocsUpdateTemplate
  },
  "report.pr-branch": {
    id: "report.pr-branch",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "PR Branch Report",
    canonicalFilePattern: ".blueprint/reports/pr-branch-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Source Branch", "Review Branch", "Filtered Scope", "Verification", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [
      "<base branch>",
      "<source branch>",
      "<commit sha>",
      "<value>",
      "<true|false>",
      "<candidate review branch>",
      "<created review branch or not created>",
      "<current branch after validation>",
      "<preview-only|confirmed-replay|blocked>",
      "<commands or none>",
      "<excluded|included>",
      "<reason>",
      "<inputsUsed from blueprint_artifact_summary_digest>",
      "<repo-relative paths or none>",
      "<sha>",
      "<subject>",
      "<code-only|blueprint-only|mixed|empty-after-filter>",
      "<include|exclude|skip>",
      "<paths or none>",
      "<command and result>",
      "<count>",
      "<none or blocker>",
      "<manual push/PR guidance or /blu-progress>"
    ],
    notes: [
      "Pr-branch should preserve the source branch while recording the review branch.",
      "The report should include a commit classification ledger, digest inputs, included/excluded paths, and post-create verification counts."
    ],
    renderScaffoldTemplate: renderPrBranchTemplate,
    renderAuthoringTemplate: renderPrBranchTemplate
  },
  "report.ship": {
    id: "report.ship",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Ship Report",
    canonicalFilePattern: ".blueprint/reports/ship-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Selected Scope", "Branch Plan", "Push Or PR Outcome", "Manual Fallback Guidance", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Ship reports keep manual fallback guidance explicit when remote shipping does not complete."],
    renderScaffoldTemplate: renderShipTemplate,
    renderAuthoringTemplate: renderShipTemplate
  },
  "report.undo": {
    id: "report.undo",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Undo Report",
    canonicalFilePattern: ".blueprint/reports/undo-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Requested Scope", "Candidate Revert Set", "Dependency Impact", "Mutation Outcome", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Undo reports capture approved scope before mutation begins."],
    renderScaffoldTemplate: renderUndoTemplate,
    renderAuthoringTemplate: renderUndoTemplate
  },
  "report.cleanup": {
    id: "report.cleanup",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Cleanup Report",
    canonicalFilePattern: ".blueprint/reports/cleanup-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Selected Phase Directories", "Protected Exclusions", "Archive Destination", "Mutation Outcome", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Cleanup reports record filesystem intent and actual outcomes."],
    renderScaffoldTemplate: renderCleanupTemplate,
    renderAuthoringTemplate: renderCleanupTemplate
  },
  "report.add-tests": {
    id: "report.add-tests",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Add Tests Report",
    canonicalFilePattern: ".blueprint/reports/add-tests-<phase>.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Coverage Goal", "Evidence Used", "Tests Added Or Updated", "Remaining Gaps", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: [
      "Add-tests reports stay phase-scoped even though they live under reports/.",
      "Authoring guidance expects the approved classification, test plan, targeted command result, generated/passing/failing/blocked counts, bugs or blockers, verification write status, and report write status to stay visible under the canonical headings."
    ],
    renderScaffoldTemplate: renderAddTestsTemplate,
    renderAuthoringTemplate: renderAddTestsTemplate
  },
  "report.audit-fix": {
    id: "report.audit-fix",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Audit Fix Report",
    canonicalFilePattern: ".blueprint/reports/audit-fix-<phase>.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Evidence Used", "Fix Scope", "Changes Applied", "Remaining Gaps", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Audit-fix reports capture dry-run or applied remediation without creating a review-fix artifact."],
    renderScaffoldTemplate: renderAuditFixTemplate,
    renderAuthoringTemplate: renderAuditFixTemplate
  }
};

export const artifactContractIds = Object.keys(
  ARTIFACT_CONTRACTS
) as ArtifactContractId[];

export function getArtifactContract(
  contractId: ArtifactContractId
): ArtifactContractDefinition {
  return ARTIFACT_CONTRACTS[contractId];
}

export function readArtifactContract(
  contractId: ArtifactContractId,
  context?: ArtifactTemplateContext
): ArtifactContractReadResult {
  const contract = getArtifactContract(contractId);

  return {
    id: contract.id,
    scope: contract.scope,
    ownerTool: contract.ownerTool,
    pathOwner: contract.pathOwner,
    canonicalName: contract.canonicalName,
    canonicalFilePattern: contract.canonicalFilePattern,
    freehandPolicy: contract.freehandPolicy,
    requiredHeadings: [...contract.requiredHeadings],
    lockedMarkers: [...contract.lockedMarkers],
    placeholderSignals: [...contract.placeholderSignals],
    notes: [...contract.notes],
    scaffoldTemplate: contract.renderScaffoldTemplate(context),
    authoringTemplate: contract.renderAuthoringTemplate(context)
  };
}

export function listArtifactContracts(): ArtifactContractReadResult[] {
  return artifactContractIds.map((contractId) => readArtifactContract(contractId));
}

export function renderArtifactAuthoringTemplate(
  contractId: ArtifactContractId,
  context?: ArtifactTemplateContext
): string {
  return getArtifactContract(contractId).renderAuthoringTemplate(context);
}

export function renderArtifactScaffoldTemplate(
  contractId: ArtifactContractId,
  context?: ArtifactTemplateContext
): string {
  return getArtifactContract(contractId).renderScaffoldTemplate(context);
}

export function resolvePhaseArtifactContractId(
  artifact: "context" | "discussion-log" | "research" | "ui-spec"
): ArtifactContractId {
  switch (artifact) {
    case "context":
      return "phase.context";
    case "discussion-log":
      return "phase.discussion-log";
    case "research":
      return "phase.research";
    case "ui-spec":
      return "phase.ui-spec";
  }
}

export function resolveValidationArtifactContractId(
  artifact: "verification" | "uat"
): ArtifactContractId {
  return artifact === "verification" ? "phase.verification" : "phase.uat";
}

export function resolveReviewArtifactContractId(
  artifact: "code-review" | "peer-review" | "review-fix" | "security" | "ui-review"
): ArtifactContractId {
  switch (artifact) {
    case "code-review":
      return "review.code-review";
    case "peer-review":
      return "review.peer-review";
    case "review-fix":
      return "review.review-fix";
    case "security":
      return "review.security";
    case "ui-review":
      return "review.ui-review";
  }
}

export function resolveCodebaseArtifactContractId(
  artifact:
    | "stack"
    | "architecture"
    | "structure"
    | "conventions"
    | "testing"
    | "integrations"
    | "concerns"
): ArtifactContractId {
  switch (artifact) {
    case "stack":
      return "codebase.stack";
    case "architecture":
      return "codebase.architecture";
    case "structure":
      return "codebase.structure";
    case "conventions":
      return "codebase.conventions";
    case "testing":
      return "codebase.testing";
    case "integrations":
      return "codebase.integrations";
    case "concerns":
      return "codebase.concerns";
  }
}

export function resolveReportContractId(
  name: string
): ArtifactContractId | null {
  const normalized = name.trim().toLowerCase();

  if (normalized === "pause-work-latest" || normalized === "pause-work") {
    return "report.pause-work";
  }

  if (normalized.startsWith("milestone-audit-")) {
    return "report.milestone-audit";
  }

  if (normalized.startsWith("milestone-complete-")) {
    return "report.milestone-complete";
  }

  if (normalized.startsWith("milestone-summary-")) {
    return "report.milestone-summary";
  }

  if (normalized === "debug-latest") {
    return "report.debug";
  }

  if (normalized === "quick-run-latest") {
    return "report.quick-run";
  }

  if (normalized === "docs-update-latest") {
    return "report.docs-update";
  }

  if (normalized === "pr-branch-latest") {
    return "report.pr-branch";
  }

  if (normalized === "ship-latest") {
    return "report.ship";
  }

  if (normalized === "undo-latest") {
    return "report.undo";
  }

  if (normalized === "cleanup-latest") {
    return "report.cleanup";
  }

  if (normalized.startsWith("add-tests-")) {
    return "report.add-tests";
  }

  if (normalized.startsWith("audit-fix-")) {
    return "report.audit-fix";
  }

  return null;
}
