export type ArtifactContractScope = "phase" | "review" | "report";

export type ArtifactContractFreehandPolicy =
  | "additional-top-level-headings"
  | "locked-structure";

export type ArtifactContractId =
  | "phase.context"
  | "phase.discussion-log"
  | "phase.research"
  | "phase.ui-spec"
  | "phase.plan"
  | "phase.summary"
  | "phase.verification"
  | "phase.uat"
  | "review.code-review"
  | "review.review-fix"
  | "review.peer-review"
  | "review.security"
  | "review.ui-review"
  | "report.pause-work"
  | "report.milestone-audit"
  | "report.milestone-complete"
  | "report.milestone-summary"
  | "report.debug"
  | "report.quick-run"
  | "report.docs-update"
  | "report.pr-branch"
  | "report.ship"
  | "report.undo"
  | "report.cleanup"
  | "report.add-tests"
  | "report.audit-fix";

export type ArtifactTemplateContext = {
  phaseLabel?: string;
  phasePrefix?: string;
  phaseName?: string;
  phaseDir?: string;
  planId?: string;
  domain?: string;
  summaryFile?: string;
  summaryPath?: string;
  reportName?: string;
  milestone?: string;
  currentPhase?: string;
  activeCommand?: string;
};

export type ArtifactContractDefinition = {
  id: ArtifactContractId;
  scope: ArtifactContractScope;
  ownerTool: string;
  pathOwner: string;
  canonicalName: string;
  canonicalFilePattern: string;
  freehandPolicy: ArtifactContractFreehandPolicy;
  requiredHeadings: string[];
  lockedMarkers: string[];
  placeholderSignals: string[];
  notes: string[];
  renderScaffoldTemplate: (context?: ArtifactTemplateContext) => string;
  renderAuthoringTemplate: (context?: ArtifactTemplateContext) => string;
};

export type ArtifactContractReadResult = Omit<
  ArtifactContractDefinition,
  "renderScaffoldTemplate" | "renderAuthoringTemplate"
> & {
  scaffoldTemplate: string;
  authoringTemplate: string;
};

function phaseLabel(context?: ArtifactTemplateContext): string {
  return context?.phaseLabel?.trim() || "Phase XX: <Phase Name>";
}

function phasePrefix(context?: ArtifactTemplateContext): string {
  return context?.phasePrefix?.trim() || "XX";
}

function planId(context?: ArtifactTemplateContext): string {
  return context?.planId?.trim() || "YY";
}

function reportName(context: ArtifactTemplateContext | undefined, fallback: string): string {
  return context?.reportName?.trim() || fallback;
}

function summaryFile(context?: ArtifactTemplateContext): string {
  return context?.summaryFile?.trim() || `${phasePrefix(context)}-${planId(context)}-SUMMARY.md`;
}

function summaryPath(context?: ArtifactTemplateContext): string {
  return (
    context?.summaryPath?.trim() ||
    `.blueprint/phases/<phase-dir>/${summaryFile(context)}`
  );
}

function phaseDir(context?: ArtifactTemplateContext): string {
  return context?.phaseDir?.trim() || "<phase-dir>";
}

function milestone(context?: ArtifactTemplateContext): string {
  return context?.milestone?.trim() || "<milestone-version>";
}

function currentPhase(context?: ArtifactTemplateContext): string {
  return context?.currentPhase?.trim() || "none";
}

function activeCommand(context?: ArtifactTemplateContext): string {
  return context?.activeCommand?.trim() || "/blu-pause-work";
}

function domain(context?: ArtifactTemplateContext): string {
  return context?.domain?.trim() || "<research domain>";
}

function withScaffoldFooter(content: string): string {
  return `${content}\n\n---\n*Generated by \`blueprint_artifact_scaffold\`*\n`;
}

function renderContextTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Context

## Phase Boundary

- Goal:
- In scope:
- Out of scope:

## Decisions

- Capture the confirmed choices for this phase here.

## Dependencies

- Prior phase artifacts:
- External constraints:

## Open Questions

- Question 1:`;
}

function renderDiscussionLogTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Discussion Log

## Summary

- Record the major discussion outcomes and unresolved questions here.

## Notes

- Timestamped notes:

## Follow-Ups

- Follow-up 1:`;
}

function renderResearchTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Research

**Researched:** <YYYY-MM-DD>
**Domain:** ${domain(context)}
**Confidence:** LOW|MEDIUM|HIGH

## Phase Requirements

| ID | Description | Research Support |
|----|-------------|------------------|
| <requirement-id> | <phase requirement> | <evidence-backed guidance> |

## Summary

- <key conclusion>

## Locked Decisions From Context

- <phase decision preserved from context>

## User Constraints

- <repo, product, or workflow constraint>

## Standard Stack

- <runtime, library, or shared repo pattern>

## Installation And Setup

- <installation or setup guidance>

## Alternatives Considered

- <alternative considered and tradeoff>

## Architecture Patterns

- <durable implementation pattern>

## Don't Hand-Roll

- <existing tool, helper, or platform feature>

## Anti-Patterns

- <anti-pattern detail or implementation to avoid>

## State Of The Art

- <current ecosystem or repo update>

## Common Pitfalls

- <failure mode or regression risk>

## Open Questions

- <open question that still needs an answer>

## Confidence Breakdown

| Topic | Confidence | Why |
|-------|------------|-----|
| <topic> | LOW|MEDIUM|HIGH | <evidence-backed confidence explanation> |

## Code Examples

\`\`\`text
<short code or pseudocode example>
\`\`\`

## Recommendations

- <prescriptive recommendation with tradeoffs>

## Sources

- <repo path, URL, or cited file reference> - why it matters`;
}

function renderUiSpecTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - UI Spec

## Outcome Mode

- Choose one: UI contract or explicit skip rationale.

## Rationale

- For Explicit skip rationale, explain why UI work is out of scope, note any safety-gate implications, and name a revisit trigger. Delete this section for UI contract mode.

## User Experience Goals

- Goal 1: <primary UX objective for this phase>
- Primary user outcome: <the user-facing outcome this phase must improve>

## Visual Design Decisions

- Spacing and layout: <grid, rhythm, or layout constraints>
- Typography: <type scale, emphasis, or readability decisions>
- Color and contrast: <palette, semantic color, and contrast rules>
- Motion and feedback: <loading, hover, or transition guidance>
- Copy and content: <voice, terminology, and label constraints>

## Screens And States

- Screen/state 1: <named screen or state in scope>
- Loading, empty, error, and success states: <required state behavior>
- Responsive behavior: <desktop, tablet, and mobile expectations>

## Components And Constraints

- Component 1: <component, pattern, or surface in scope>
- Existing design-system or registry primitives to reuse: <existing primitives or \`none\`>
- New component or token justification: <new primitives needed or \`none\`>
- Density and interaction constraints: <layout density, touch targets, or gesture rules>

## Accessibility And Content

- Accessibility note 1: <keyboard, focus, contrast, or assistive-tech guidance>
- Content hierarchy and empty-state guidance: <content hierarchy and empty-state behavior>
- Localization or content safety notes: <localization, moderation, or terminology notes>

## Registry And Design-System Safety

- Registry and design-system safety: <how the draft avoids forking the registry or design system>
- Token and theming compatibility: <token, theme, or brand-system compatibility notes>
- Revisit trigger if the scope changes: <when this contract must be revisited>

## Next Safe Action

- /blu-plan-phase ${phasePrefix(context)}`;
}

function renderPlanTemplate(context?: ArtifactTemplateContext): string {
  return `---
phase: ${phasePrefix(context)}
plan_id: "${planId(context)}"
title: "${phaseLabel(context)} plan ${planId(context)}"
wave: 1
status: planned
objective: "Replace with a concrete, execution-ready goal."
depends_on: []
requirements:
  - Replace with the exact requirement IDs this plan addresses.
files_modified:
  - Replace with the real repo paths the executor must touch.
read_first:
  - Replace with the files the executor must inspect before editing.
acceptance_criteria:
  - Replace with grep/test-verifiable acceptance criteria.
autonomous: true
---

# ${phaseLabel(context)} - Plan ${planId(context)}

## Goal

Replace with a concrete, execution-ready goal.

## Scope

- Replace with the exact work this plan owns.

## Tasks

### Task 1: Replace with a concrete task name

#### Read First

- Replace with the files the executor must inspect before editing.

#### Action

- Replace with concrete code, config, or artifact changes.

#### Acceptance Criteria

- Replace with grep/test-verifiable acceptance criteria.

## Verification

- Replace with the exact checks that prove this plan is complete.

## Must Haves

- Replace with the goal-backward must-haves this plan cannot drop.`;
}

function renderSummaryTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Summary ${planId(context)}

**Plan:** \`${phasePrefix(context)}-${planId(context)}-PLAN.md\`
**Status:** COMPLETED|PARTIAL|BLOCKED

## Outcome

- Concise delivery summary grounded in the completed work.

## Changes Made

- Explicit code, config, or artifact changes completed for this plan.

## Verification

- Command, test, or evidence that supports the reported outcome.

## Follow-Ups

- Remaining gap, handoff, or \`none\`.

## Evidence

- \`${summaryPath(context)}\` or other saved repo evidence if helpful.`;
}

function renderVerificationTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Verification

**Coverage:** Reviewed \`${summaryFile(context)}\` and any other saved phase summaries for validation evidence.

## Validation Summary

- Concise readiness result grounded in the saved summaries.

## Evidence Reviewed

- \`${summaryPath(context)}\`

## Gaps Found

- Explicit blocker, follow-up, or \`none\`.

## Suggested Repairs

- Explicit next repair, follow-up, or \`none\`.

## Next Safe Action

- /blu-verify-work ${phasePrefix(context)}`;
}

function renderUatTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - UAT

**Status:** PASS|FAIL|PARTIAL

## UAT Summary

- Concise user-facing result grounded in the saved summaries and verification artifact.

## Questions Asked

- Question asked during the UAT pass, or \`none\`.

## Observed Behavior

- Observed behavior tied to saved summary evidence such as \`${summaryFile(context)}\`.

## Unresolved Gaps

- Explicit blocker, follow-up, or \`none\`.

## Follow-Up Fixes

- Explicit follow-up fix, acceptance note, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderCodeReviewTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Code Review

**Verdict:** PASS|FOLLOW_UP|BLOCKED

## Review Summary

- Concise synthesis of the review outcome, including a severity summary such as critical/high/medium/low/unknown counts.

## Scope Reviewed

- Repo-relative file path or saved plan-derived scope.

## Evidence Reviewed

- Saved phase artifacts, repo files, or cited references reviewed.

## Positive Signals

- Confirmed passes, mitigations, or coverage strengths.

## Severity Summary

- critical: 0
- high: 0
- medium: 0
- low: 0
- unknown: 0

## Findings

- [high] Example issue with evidence and impact.

## Follow-Ups

- Explicit next fix, validation step, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderReviewFixTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Review Fix

**Status:** APPLIED|PARTIAL|SKIPPED

## Findings Addressed

- Finding id or summary addressed in this remediation pass.

## Changes Made

- Concrete remediation completed.

## Verification

- Validation or test evidence for the applied fix, or \`none\`.

## Follow-Ups

- Remaining work, deferred item, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderPeerReviewTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Peer Reviews

**Reviewers:** <reviewer-cli-1>, <reviewer-cli-2>

## Review Summary

- Concise synthesis of the saved reviewer outputs.

## Reviewer Results

- Reviewer name: main conclusions.

## Disagreements

- Explicit reviewer disagreement, or \`none\`.

## Follow-Ups

- Plan revision, execution change, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderSecurityTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - Security

**Posture:** PASS|FOLLOW_UP|BLOCKED

## Security Summary

- Concise security posture grounded in saved evidence.

## Evidence Reviewed

- Saved phase artifacts, repo paths, or cited references reviewed.

## Threat Register

| Threat ID | Disposition | Status | Evidence / Note |
|-----------|-------------|--------|-----------------|
| T-01 | mitigate / accept / transfer | closed / accepted / open | File, artifact, or rationale reference. |

## Accepted Risks

- Accepted threat reference plus rationale, or \`none\`.

## Findings

- Open threat, missing control, or risk decision that needs explicit attention, or \`none\`.

## Follow-Ups

- Explicit hardening step, validation gap, or \`none\`.

## Security Audit Trail

- Audit date, threat counts, and verifier note.

## Next Safe Action

- /blu-progress`;
}

function renderUiReviewTemplate(context?: ArtifactTemplateContext): string {
  return `# ${phaseLabel(context)} - UI Review

**Verdict:** PASS|FOLLOW_UP|BLOCKED

## UI Review Summary

- Concise UI quality result grounded in saved evidence and the actual surface.

## Evidence Reviewed

- Saved summaries, UI spec, screenshots, or repo references reviewed.

## Findings

- Six-pillar UI issue, improvement, or \`none\`.

## Follow-Ups

- Explicit UI repair, validation step, or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderPauseWorkTemplate(context?: ArtifactTemplateContext): string {
  return `---
report_type: pause-work
schema_version: 1
status: paused
timestamp: <ISO-8601 timestamp>
project_status: <project-status>
current_milestone: ${milestone(context)}
current_phase: ${currentPhase(context)}
active_command: ${activeCommand(context)}
---

# Pause Work Handoff

## Current State

<current state paragraph>

## Completed Work

- none

## Remaining Work

- none

## Decisions

- none

## Blockers

- none

## Human Actions Pending

- none

## Modified Files

- none

## Blueprint Snapshot

- Core artifacts: none
- Phase artifacts: none
- Existing reports: none
- Missing artifacts: none

## Next Action

<next safe action>

## Context Notes

<context notes>`;
}

function renderMilestoneAuditTemplate(context?: ArtifactTemplateContext): string {
  return `# Milestone ${milestone(context)} - Audit

## Original Intent Snapshot

- Locked milestone intent and source evidence.

## Roadmap And Phase Evidence

- Completed phase evidence reviewed for this milestone.

## Gaps Found

- Archival gap, stale assumption, or \`none\`.

## Archival Blockers

- Explicit blocker or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderMilestoneCompleteTemplate(context?: ArtifactTemplateContext): string {
  return `# Milestone ${milestone(context)} - Completion

## Completion Decision

- Whether the milestone is ready to close and why.

## Audit Report Used

- Saved milestone audit report path or \`none\`.

## Completion Rationale

- Concise closeout rationale grounded in saved evidence.

## Residual Watch Items

- Remaining watch item or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderMilestoneSummaryTemplate(context?: ArtifactTemplateContext): string {
  return `# Milestone ${milestone(context)} - Summary

## Scope Summary

- Concise milestone scope and outcome summary.

## Source Reports Used

- Saved milestone reports and supporting artifacts reviewed.

## Shipped Outcomes

- Major delivered outcomes.

## Deferred Follow-Ups

- Deferred item or \`none\`.

## Recommended Carry-Forward Context

- Context that should seed the next milestone.`;
}

function renderDebugTemplate(): string {
  return `# Debug Report

## Problem Statement

- What broke, where it appears, and why it matters.

## Evidence Collected

- Logs, traces, artifacts, or cited repo evidence.

## Hypotheses

- Ranked explanation or \`none\`.

## Actions Taken

- Investigation or fix attempt performed.

## Next Safe Action

- /blu-progress`;
}

function renderQuickRunTemplate(): string {
  return `# Quick Run Report

## Task Summary

- Why the task qualified as a bounded quick run.

## Changes Made

- Concrete repo or Blueprint changes completed.

## Verification

- Checks run or evidence gathered, or \`none\`.

## Follow-Ups

- Remaining work or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderDocsUpdateTemplate(): string {
  return `# Docs Update Report

## Requested Docs Scope

- Requested docs surface and why it was selected.

## Changes Made

- Docs created or updated.

## Verification

- Validation performed against code or repo evidence, or \`none\`.

## Follow-Ups

- Remaining docs task or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderPrBranchTemplate(): string {
  return `# PR Branch Report

## Source Branch

- Original working branch and status.

## Review Branch

- Created review branch and resulting branch name.

## Filtered Scope

- Scope retained for review or \`none\`.

## Verification

- Commands or checks used to confirm the branch state.

## Next Safe Action

- /blu-progress`;
}

function renderShipTemplate(): string {
  return `# Ship Report

## Selected Scope

- Branch, commits, or review scope selected for shipping.

## Branch Plan

- Push or PR plan that was attempted.

## Push Or PR Outcome

- Actual push or PR outcome, or \`none\`.

## Manual Fallback Guidance

- Manual next step when remote shipping did not complete.

## Next Safe Action

- /blu-progress`;
}

function renderUndoTemplate(): string {
  return `# Undo Report

## Requested Scope

- Approved undo target and why it was selected.

## Candidate Revert Set

- Commits, files, or artifacts that are part of the undo scope.

## Dependency Impact

- Dependency or follow-on risk from the undo.

## Mutation Outcome

- Result of the undo operation or \`pending\`.

## Next Safe Action

- /blu-progress`;
}

function renderCleanupTemplate(): string {
  return `# Cleanup Report

## Selected Phase Directories

- Phase directories selected for cleanup.

## Protected Exclusions

- Protected files or exclusions that were preserved.

## Archive Destination

- Archive path or destination used.

## Mutation Outcome

- Actual cleanup result or \`pending\`.

## Next Safe Action

- /blu-progress`;
}

function renderAddTestsTemplate(context?: ArtifactTemplateContext): string {
  return `# Add Tests Report

## Coverage Goal

- Coverage gap selected for this pass in phase ${phasePrefix(context)}.

## Evidence Used

- Saved summaries, verification, or UAT evidence reviewed.

## Tests Added Or Updated

- Test files or suites changed.

## Remaining Gaps

- Explicit remaining gap or \`none\`.

## Next Safe Action

- /blu-progress`;
}

function renderAuditFixTemplate(context?: ArtifactTemplateContext): string {
  return `# Audit Fix Report

## Evidence Used

- Saved review, verification, UAT, or security evidence reviewed for phase ${phasePrefix(context)}.

## Fix Scope

- Repo files or findings selected for remediation.

## Changes Applied

- Fixes applied or \`none\`.

## Remaining Gaps

- Remaining high-confidence gap or \`none\`.

## Next Safe Action

- /blu-progress`;
}

const ARTIFACT_CONTRACTS: Record<ArtifactContractId, ArtifactContractDefinition> = {
  "phase.context": {
    id: "phase.context",
    scope: "phase",
    ownerTool: "blueprint_phase_artifact_write",
    pathOwner: "blueprint_phase_artifact_write",
    canonicalName: "Phase Context",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-CONTEXT.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Phase Boundary", "Decisions", "Dependencies", "Open Questions"],
    lockedMarkers: [],
    placeholderSignals: [
      "Goal:",
      "In scope:",
      "Out of scope:",
      "Question 1:",
      "Capture the confirmed choices for this phase here."
    ],
    notes: [
      "Discovery context is phase-scoped and MCP-owned.",
      "Write validation requires an H1 title, removal of scaffold placeholders, and at least one populated contract section."
    ],
    renderScaffoldTemplate: renderContextTemplate,
    renderAuthoringTemplate: renderContextTemplate
  },
  "phase.discussion-log": {
    id: "phase.discussion-log",
    scope: "phase",
    ownerTool: "blueprint_phase_artifact_write",
    pathOwner: "blueprint_phase_artifact_write",
    canonicalName: "Phase Discussion Log",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-DISCUSSION-LOG.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Summary", "Notes", "Follow-Ups"],
    lockedMarkers: [],
    placeholderSignals: [
      "Record the major discussion outcomes and unresolved questions here.",
      "Timestamped notes:",
      "Follow-up 1:"
    ],
    notes: [
      "Discussion logs are optional supporting artifacts.",
      "Write validation requires an H1 title, removal of scaffold placeholders, and at least one populated contract section."
    ],
    renderScaffoldTemplate: renderDiscussionLogTemplate,
    renderAuthoringTemplate: renderDiscussionLogTemplate
  },
  "phase.research": {
    id: "phase.research",
    scope: "phase",
    ownerTool: "blueprint_phase_artifact_write",
    pathOwner: "blueprint_phase_artifact_write",
    canonicalName: "Phase Research",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-RESEARCH.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Phase Requirements",
      "Summary",
      "Locked Decisions From Context",
      "User Constraints",
      "Standard Stack",
      "Installation And Setup",
      "Alternatives Considered",
      "Architecture Patterns",
      "Don't Hand-Roll",
      "Anti-Patterns",
      "State Of The Art",
      "Common Pitfalls",
      "Open Questions",
      "Confidence Breakdown",
      "Code Examples",
      "Recommendations",
      "Sources"
    ],
    lockedMarkers: ["**Confidence:**"],
    placeholderSignals: [
      "Phase XX:",
      "<Phase Name>",
      "<YYYY-MM-DD>",
      "<research domain>",
      "<requirement-id>",
      "<phase requirement>",
      "<evidence-backed guidance>",
      "<key conclusion>",
      "<phase decision preserved from context>",
      "<repo, product, or workflow constraint>",
      "<runtime, library, or shared repo pattern>",
      "<installation or setup guidance>",
      "<alternative considered and tradeoff>",
      "<durable implementation pattern>",
      "<existing tool, helper, or platform feature>",
      "<anti-pattern detail or implementation to avoid>",
      "<current ecosystem or repo update>",
      "<failure mode or regression risk>",
      "<open question that still needs an answer>",
      "<topic>",
      "<evidence-backed confidence explanation>",
      "<short code or pseudocode example>",
      "<prescriptive recommendation with tradeoffs>",
      "<repo path, URL, or cited file reference>"
    ],
    notes: [
      "Research writes validate in strict mode by default.",
      "Additional top-level headings are allowed, but required headings and the confidence marker stay locked.",
      "Drafting should use the canonical authoring template from blueprint_artifact_contract_read before any rewrite or persistence step."
    ],
    renderScaffoldTemplate: (context) => withScaffoldFooter(renderResearchTemplate(context)),
    renderAuthoringTemplate: renderResearchTemplate
  },
  "phase.ui-spec": {
    id: "phase.ui-spec",
    scope: "phase",
    ownerTool: "blueprint_phase_artifact_write",
    pathOwner: "blueprint_phase_artifact_write",
    canonicalName: "Phase UI Spec",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-UI-SPEC.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Outcome Mode",
      "User Experience Goals",
      "Visual Design Decisions",
      "Screens And States",
      "Components And Constraints",
      "Accessibility And Content",
      "Registry And Design-System Safety",
      "Next Safe Action"
    ],
    lockedMarkers: [],
    placeholderSignals: [
      "Choose one: UI contract or explicit skip rationale.",
      "- For Explicit skip rationale, explain why UI work is out of scope, note any safety-gate implications, and name a revisit trigger. Delete this section for UI contract mode.",
      "Goal 1: <primary UX objective for this phase>",
      "Primary user outcome: <the user-facing outcome this phase must improve>",
      "Spacing and layout: <grid, rhythm, or layout constraints>",
      "Typography: <type scale, emphasis, or readability decisions>",
      "Color and contrast: <palette, semantic color, and contrast rules>",
      "Motion and feedback: <loading, hover, or transition guidance>",
      "Copy and content: <voice, terminology, and label constraints>",
      "Screen/state 1: <named screen or state in scope>",
      "Loading, empty, error, and success states: <required state behavior>",
      "Responsive behavior: <desktop, tablet, and mobile expectations>",
      "Component 1: <component, pattern, or surface in scope>",
      "Existing design-system or registry primitives to reuse: <existing primitives or `none`>",
      "New component or token justification: <new primitives needed or `none`>",
      "Density and interaction constraints: <layout density, touch targets, or gesture rules>",
      "Accessibility note 1: <keyboard, focus, contrast, or assistive-tech guidance>",
      "Content hierarchy and empty-state guidance: <content hierarchy and empty-state behavior>",
      "Localization or content safety notes: <localization, moderation, or terminology notes>",
      "Registry and design-system safety: <how the draft avoids forking the registry or design system>",
      "Token and theming compatibility: <token, theme, or brand-system compatibility notes>",
      "Revisit trigger if the scope changes: <when this contract must be revisited>"
    ],
    notes: [
      "The same durable artifact covers both a real UI contract and an explicit skip rationale.",
      "Write validation requires an H1 title and Outcome Mode; explicit skip rationale may use a populated `## Rationale` section instead of the full UI contract.",
      "The canonical authoring template includes an optional `## Rationale` branch for skip mode; remove it when the artifact stays in full UI-contract mode.",
      "A real UI contract must lock concrete visual and UX decisions before planning, including spacing, typography, color, copy/content, state behavior, and registry or design-system safety."
    ],
    renderScaffoldTemplate: (context) => withScaffoldFooter(renderUiSpecTemplate(context)),
    renderAuthoringTemplate: renderUiSpecTemplate
  },
  "phase.plan": {
    id: "phase.plan",
    scope: "phase",
    ownerTool: "blueprint_phase_plan_write",
    pathOwner: "blueprint_phase_plan_write",
    canonicalName: "Phase Plan",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-YY-PLAN.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Goal", "Scope", "Tasks", "Verification", "Must Haves"],
    lockedMarkers: [
      "phase:",
      "plan_id:",
      "title:",
      "wave:",
      "status:",
      "objective:",
      "depends_on:",
      "requirements:",
      "files_modified:",
      "read_first:",
      "acceptance_criteria:",
      "autonomous:"
    ],
    placeholderSignals: [
      "Replace with a concrete, execution-ready goal.",
      "Replace with the exact requirement IDs this plan addresses.",
      "Replace with the real repo paths the executor must touch.",
      "Replace with grep/test-verifiable acceptance criteria."
    ],
    notes: [
      "Plan frontmatter keys and task subsections are locked for MCP parsing.",
      "Additional top-level headings are allowed, but required plan sections must remain unchanged."
    ],
    renderScaffoldTemplate: (context) => withScaffoldFooter(renderPlanTemplate(context)),
    renderAuthoringTemplate: renderPlanTemplate
  },
  "phase.summary": {
    id: "phase.summary",
    scope: "phase",
    ownerTool: "blueprint_phase_summary_write",
    pathOwner: "blueprint_phase_summary_write",
    canonicalName: "Phase Summary",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-YY-SUMMARY.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Outcome", "Changes Made", "Verification", "Follow-Ups", "Evidence"],
    lockedMarkers: ["**Plan:**", "**Status:**"],
    placeholderSignals: [
      "COMPLETED|PARTIAL|BLOCKED",
      "Concise delivery summary grounded in the completed work."
    ],
    notes: [
      "Summary artifacts stay linked to a saved plan and should remain grounded in completed work."
    ],
    renderScaffoldTemplate: renderSummaryTemplate,
    renderAuthoringTemplate: renderSummaryTemplate
  },
  "phase.verification": {
    id: "phase.verification",
    scope: "phase",
    ownerTool: "blueprint_phase_validation_write",
    pathOwner: "blueprint_phase_validation_write",
    canonicalName: "Phase Verification",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-VERIFICATION.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Validation Summary",
      "Evidence Reviewed",
      "Gaps Found",
      "Suggested Repairs",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Coverage:**"],
    placeholderSignals: [
      "Reviewed",
      "Concise readiness result grounded in the saved summaries."
    ],
    notes: [
      "Verification artifacts must stay grounded in saved execution summaries.",
      "Additional top-level headings are allowed, but evidence reviewed should still cite saved summaries."
    ],
    renderScaffoldTemplate: renderVerificationTemplate,
    renderAuthoringTemplate: renderVerificationTemplate
  },
  "phase.uat": {
    id: "phase.uat",
    scope: "phase",
    ownerTool: "blueprint_phase_validation_write",
    pathOwner: "blueprint_phase_validation_write",
    canonicalName: "Phase UAT",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-UAT.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "UAT Summary",
      "Questions Asked",
      "Observed Behavior",
      "Unresolved Gaps",
      "Follow-Up Fixes",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Status:**"],
    placeholderSignals: ["PASS|FAIL|PARTIAL"],
    notes: [
      "UAT artifacts stay resumable and must reference saved summaries inside UAT Summary or Observed Behavior."
    ],
    renderScaffoldTemplate: renderUatTemplate,
    renderAuthoringTemplate: renderUatTemplate
  },
  "review.code-review": {
    id: "review.code-review",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "Code Review",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-REVIEW.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Review Summary",
      "Scope Reviewed",
      "Evidence Reviewed",
      "Positive Signals",
      "Severity Summary",
      "Findings",
      "Follow-Ups",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Verdict:**"],
    placeholderSignals: ["PASS|FOLLOW_UP|BLOCKED"],
    notes: [
      "Read the canonical review contract through `blueprint_artifact_contract_read` before drafting or updating review artifacts.",
      "Findings, evidence reviewed, positive signals, and severity counts must remain machine-extractable."
    ],
    renderScaffoldTemplate: renderCodeReviewTemplate,
    renderAuthoringTemplate: renderCodeReviewTemplate
  },
  "review.review-fix": {
    id: "review.review-fix",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "Review Fix",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-REVIEW-FIX.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Findings Addressed", "Changes Made", "Verification", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: ["**Status:**"],
    placeholderSignals: ["APPLIED|PARTIAL|SKIPPED"],
    notes: ["Review-fix artifacts summarize bounded remediation only."],
    renderScaffoldTemplate: renderReviewFixTemplate,
    renderAuthoringTemplate: renderReviewFixTemplate
  },
  "review.peer-review": {
    id: "review.peer-review",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "Peer Review",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-REVIEWS.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Review Summary", "Reviewer Results", "Disagreements", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: ["**Reviewers:**"],
    placeholderSignals: ["<reviewer-cli-1>", "<reviewer-cli-2>"],
    notes: ["Preserve reviewer disagreement honestly instead of flattening it."],
    renderScaffoldTemplate: renderPeerReviewTemplate,
    renderAuthoringTemplate: renderPeerReviewTemplate
  },
  "review.security": {
    id: "review.security",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "Security Review",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-SECURITY.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: [
      "Security Summary",
      "Evidence Reviewed",
      "Threat Register",
      "Accepted Risks",
      "Findings",
      "Follow-Ups",
      "Security Audit Trail",
      "Next Safe Action"
    ],
    lockedMarkers: ["**Posture:**"],
    placeholderSignals: [
      "PASS|FOLLOW_UP|BLOCKED",
      "Concise security posture grounded in saved evidence.",
      "Saved phase artifacts, repo paths, or cited references reviewed.",
      "| T-01 | mitigate / accept / transfer | closed / accepted / open | File, artifact, or rationale reference. |",
      "Accepted threat reference plus rationale, or `none`.",
      "Open threat, missing control, or risk decision that needs explicit attention, or `none`.",
      "Explicit hardening step, validation gap, or `none`.",
      "Audit date, threat counts, and verifier note."
    ],
    notes: [
      "Security artifacts should distinguish confirmed mitigations from missing controls, keep threat-register dispositions explicit, keep accepted-risk and audit-trail context visible, and reject scaffold-only placeholder markers."
    ],
    renderScaffoldTemplate: renderSecurityTemplate,
    renderAuthoringTemplate: renderSecurityTemplate
  },
  "review.ui-review": {
    id: "review.ui-review",
    scope: "review",
    ownerTool: "blueprint_review_record",
    pathOwner: "blueprint_review_record",
    canonicalName: "UI Review",
    canonicalFilePattern: ".blueprint/phases/<phase-slug>/XX-UI-REVIEW.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["UI Review Summary", "Evidence Reviewed", "Findings", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: ["**Verdict:**"],
    placeholderSignals: ["PASS|FOLLOW_UP|BLOCKED"],
    notes: ["UI review artifacts stay phase-scoped and evidence-backed."],
    renderScaffoldTemplate: renderUiReviewTemplate,
    renderAuthoringTemplate: renderUiReviewTemplate
  },
  "report.pause-work": {
    id: "report.pause-work",
    scope: "report",
    ownerTool: "blueprint_pause_handoff_write",
    pathOwner: "blueprint_pause_handoff_write",
    canonicalName: "Pause Work Handoff",
    canonicalFilePattern: ".blueprint/reports/pause-work-latest.md",
    freehandPolicy: "locked-structure",
    requiredHeadings: [
      "Current State",
      "Completed Work",
      "Remaining Work",
      "Decisions",
      "Blockers",
      "Human Actions Pending",
      "Modified Files",
      "Blueprint Snapshot",
      "Next Action",
      "Context Notes"
    ],
    lockedMarkers: [
      "report_type:",
      "schema_version:",
      "status:",
      "timestamp:",
      "project_status:",
      "current_milestone:",
      "current_phase:",
      "active_command:"
    ],
    placeholderSignals: ["<ISO-8601 timestamp>", "<current state paragraph>", "<context notes>"],
    notes: [
      "Pause handoff is machine-parsed and keeps a locked frontmatter plus section contract."
    ],
    renderScaffoldTemplate: renderPauseWorkTemplate,
    renderAuthoringTemplate: renderPauseWorkTemplate
  },
  "report.milestone-audit": {
    id: "report.milestone-audit",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Milestone Audit Report",
    canonicalFilePattern: `.blueprint/reports/${reportName(undefined, "milestone-audit-<milestone>")}.md`,
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Original Intent Snapshot", "Roadmap And Phase Evidence", "Gaps Found", "Archival Blockers", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: ["<milestone-version>"],
    notes: ["Audit-milestone owns this report through blueprint_artifact_report_write."],
    renderScaffoldTemplate: renderMilestoneAuditTemplate,
    renderAuthoringTemplate: renderMilestoneAuditTemplate
  },
  "report.milestone-complete": {
    id: "report.milestone-complete",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Milestone Completion Report",
    canonicalFilePattern: ".blueprint/reports/milestone-complete-<milestone>.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Completion Decision", "Audit Report Used", "Completion Rationale", "Residual Watch Items", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: ["<milestone-version>"],
    notes: ["Complete-milestone owns this report through blueprint_artifact_report_write."],
    renderScaffoldTemplate: renderMilestoneCompleteTemplate,
    renderAuthoringTemplate: renderMilestoneCompleteTemplate
  },
  "report.milestone-summary": {
    id: "report.milestone-summary",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Milestone Summary Report",
    canonicalFilePattern: ".blueprint/reports/milestone-summary-<milestone>.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Scope Summary", "Source Reports Used", "Shipped Outcomes", "Deferred Follow-Ups", "Recommended Carry-Forward Context"],
    lockedMarkers: [],
    placeholderSignals: ["<milestone-version>"],
    notes: ["New-milestone uses this report as the default carry-forward seed."],
    renderScaffoldTemplate: renderMilestoneSummaryTemplate,
    renderAuthoringTemplate: renderMilestoneSummaryTemplate
  },
  "report.debug": {
    id: "report.debug",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Debug Report",
    canonicalFilePattern: ".blueprint/reports/debug-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Problem Statement", "Evidence Collected", "Hypotheses", "Actions Taken", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Debug reports keep investigative evidence explicit and resumable."],
    renderScaffoldTemplate: renderDebugTemplate,
    renderAuthoringTemplate: renderDebugTemplate
  },
  "report.quick-run": {
    id: "report.quick-run",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Quick Run Report",
    canonicalFilePattern: ".blueprint/reports/quick-run-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Task Summary", "Changes Made", "Verification", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Quick reports capture bounded execution without impersonating saved plans."],
    renderScaffoldTemplate: renderQuickRunTemplate,
    renderAuthoringTemplate: renderQuickRunTemplate
  },
  "report.docs-update": {
    id: "report.docs-update",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Docs Update Report",
    canonicalFilePattern: ".blueprint/reports/docs-update-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Requested Docs Scope", "Changes Made", "Verification", "Follow-Ups", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Docs-update uses this report to capture repo and verification outcomes."],
    renderScaffoldTemplate: renderDocsUpdateTemplate,
    renderAuthoringTemplate: renderDocsUpdateTemplate
  },
  "report.pr-branch": {
    id: "report.pr-branch",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "PR Branch Report",
    canonicalFilePattern: ".blueprint/reports/pr-branch-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Source Branch", "Review Branch", "Filtered Scope", "Verification", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Pr-branch should preserve the source branch while recording the review branch."],
    renderScaffoldTemplate: renderPrBranchTemplate,
    renderAuthoringTemplate: renderPrBranchTemplate
  },
  "report.ship": {
    id: "report.ship",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Ship Report",
    canonicalFilePattern: ".blueprint/reports/ship-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Selected Scope", "Branch Plan", "Push Or PR Outcome", "Manual Fallback Guidance", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Ship reports keep manual fallback guidance explicit when remote shipping does not complete."],
    renderScaffoldTemplate: renderShipTemplate,
    renderAuthoringTemplate: renderShipTemplate
  },
  "report.undo": {
    id: "report.undo",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Undo Report",
    canonicalFilePattern: ".blueprint/reports/undo-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Requested Scope", "Candidate Revert Set", "Dependency Impact", "Mutation Outcome", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Undo reports capture approved scope before mutation begins."],
    renderScaffoldTemplate: renderUndoTemplate,
    renderAuthoringTemplate: renderUndoTemplate
  },
  "report.cleanup": {
    id: "report.cleanup",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Cleanup Report",
    canonicalFilePattern: ".blueprint/reports/cleanup-latest.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Selected Phase Directories", "Protected Exclusions", "Archive Destination", "Mutation Outcome", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Cleanup reports record filesystem intent and actual outcomes."],
    renderScaffoldTemplate: renderCleanupTemplate,
    renderAuthoringTemplate: renderCleanupTemplate
  },
  "report.add-tests": {
    id: "report.add-tests",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Add Tests Report",
    canonicalFilePattern: ".blueprint/reports/add-tests-<phase>.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Coverage Goal", "Evidence Used", "Tests Added Or Updated", "Remaining Gaps", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Add-tests reports stay phase-scoped even though they live under reports/."],
    renderScaffoldTemplate: renderAddTestsTemplate,
    renderAuthoringTemplate: renderAddTestsTemplate
  },
  "report.audit-fix": {
    id: "report.audit-fix",
    scope: "report",
    ownerTool: "blueprint_artifact_report_write",
    pathOwner: "blueprint_artifact_report_write",
    canonicalName: "Audit Fix Report",
    canonicalFilePattern: ".blueprint/reports/audit-fix-<phase>.md",
    freehandPolicy: "additional-top-level-headings",
    requiredHeadings: ["Evidence Used", "Fix Scope", "Changes Applied", "Remaining Gaps", "Next Safe Action"],
    lockedMarkers: [],
    placeholderSignals: [],
    notes: ["Audit-fix reports capture dry-run or applied remediation without creating a review-fix artifact."],
    renderScaffoldTemplate: renderAuditFixTemplate,
    renderAuthoringTemplate: renderAuditFixTemplate
  }
};

export const artifactContractIds = Object.keys(
  ARTIFACT_CONTRACTS
) as ArtifactContractId[];

export function getArtifactContract(
  contractId: ArtifactContractId
): ArtifactContractDefinition {
  return ARTIFACT_CONTRACTS[contractId];
}

export function readArtifactContract(
  contractId: ArtifactContractId,
  context?: ArtifactTemplateContext
): ArtifactContractReadResult {
  const contract = getArtifactContract(contractId);

  return {
    id: contract.id,
    scope: contract.scope,
    ownerTool: contract.ownerTool,
    pathOwner: contract.pathOwner,
    canonicalName: contract.canonicalName,
    canonicalFilePattern: contract.canonicalFilePattern,
    freehandPolicy: contract.freehandPolicy,
    requiredHeadings: [...contract.requiredHeadings],
    lockedMarkers: [...contract.lockedMarkers],
    placeholderSignals: [...contract.placeholderSignals],
    notes: [...contract.notes],
    scaffoldTemplate: contract.renderScaffoldTemplate(context),
    authoringTemplate: contract.renderAuthoringTemplate(context)
  };
}

export function listArtifactContracts(): ArtifactContractReadResult[] {
  return artifactContractIds.map((contractId) => readArtifactContract(contractId));
}

export function renderArtifactAuthoringTemplate(
  contractId: ArtifactContractId,
  context?: ArtifactTemplateContext
): string {
  return getArtifactContract(contractId).renderAuthoringTemplate(context);
}

export function renderArtifactScaffoldTemplate(
  contractId: ArtifactContractId,
  context?: ArtifactTemplateContext
): string {
  return getArtifactContract(contractId).renderScaffoldTemplate(context);
}

export function resolvePhaseArtifactContractId(
  artifact: "context" | "discussion-log" | "research" | "ui-spec"
): ArtifactContractId {
  switch (artifact) {
    case "context":
      return "phase.context";
    case "discussion-log":
      return "phase.discussion-log";
    case "research":
      return "phase.research";
    case "ui-spec":
      return "phase.ui-spec";
  }
}

export function resolveValidationArtifactContractId(
  artifact: "verification" | "uat"
): ArtifactContractId {
  return artifact === "verification" ? "phase.verification" : "phase.uat";
}

export function resolveReviewArtifactContractId(
  artifact: "code-review" | "peer-review" | "review-fix" | "security" | "ui-review"
): ArtifactContractId {
  switch (artifact) {
    case "code-review":
      return "review.code-review";
    case "peer-review":
      return "review.peer-review";
    case "review-fix":
      return "review.review-fix";
    case "security":
      return "review.security";
    case "ui-review":
      return "review.ui-review";
  }
}

export function resolveReportContractId(
  name: string
): ArtifactContractId | null {
  const normalized = name.trim().toLowerCase();

  if (normalized === "pause-work-latest" || normalized === "pause-work") {
    return "report.pause-work";
  }

  if (normalized.startsWith("milestone-audit-")) {
    return "report.milestone-audit";
  }

  if (normalized.startsWith("milestone-complete-")) {
    return "report.milestone-complete";
  }

  if (normalized.startsWith("milestone-summary-")) {
    return "report.milestone-summary";
  }

  if (normalized === "debug-latest") {
    return "report.debug";
  }

  if (normalized === "quick-run-latest") {
    return "report.quick-run";
  }

  if (normalized === "docs-update-latest") {
    return "report.docs-update";
  }

  if (normalized === "pr-branch-latest") {
    return "report.pr-branch";
  }

  if (normalized === "ship-latest") {
    return "report.ship";
  }

  if (normalized === "undo-latest") {
    return "report.undo";
  }

  if (normalized === "cleanup-latest") {
    return "report.cleanup";
  }

  if (normalized.startsWith("add-tests-")) {
    return "report.add-tests";
  }

  if (normalized.startsWith("audit-fix-")) {
    return "report.audit-fix";
  }

  return null;
}
