import * as z from "zod/v4";
import { readArtifactContract, type ArtifactContractId } from "./artifact-contracts/index.js";

export const CODEBASE_DOCUMENT_IDS = [
  "stack", "architecture", "structure", "conventions", "testing", "integrations", "concerns"
] as const;
export type CodebaseDocumentId = (typeof CODEBASE_DOCUMENT_IDS)[number];
export type CodebaseDocumentContractId = `codebase.${CodebaseDocumentId}`;

const normalizeText = (value: string): string => value.replace(/\r\n?/g, "\n").trim();
const normalizeHeading = (value: string): string => value.trim()
  .replace(/^#{1,6}\s+/, "").replace(/\s+#+$/, "").replace(/\s+/g, " ");
const headingKey = (value: string): string => normalizeHeading(value).toLocaleLowerCase("en-US");
const placeholderValues = new Set(CODEBASE_DOCUMENT_IDS.flatMap(id =>
  readArtifactContract(`codebase.${id}`).placeholderSignals.filter(value => value.startsWith("<"))
).map(value => value.toLocaleLowerCase("en-US")));
const scaffoldValueLines = new Set(CODEBASE_DOCUMENT_IDS.flatMap(id =>
  readArtifactContract(`codebase.${id}`).scaffoldTemplate.split("\n")
    .map(line => line.trim().replace(/^[-*+]\s+/, "").toLocaleLowerCase("en-US"))
    .filter(line => placeholderValues.has(line.slice(line.lastIndexOf(":") + 1).trim()))
));
const scaffoldMarkers = new Set([
  "Generated by `blueprint_artifact_scaffold`", "Generated by `/blu-map-codebase`"
]);

type MarkdownLine = { text: string; code: boolean; fence: boolean; heading?: { level: number; title: string } };

/** A heading inside a fenced example is evidence, never document structure. */
function markdownLines(content: string): MarkdownLine[] {
  let fence: { character: string; length: number } | undefined;
  return content.replace(/\r\n?/g, "\n").split("\n").map(text => {
    if (fence) {
      const closing = text.match(/^ {0,3}(`{3,}|~{3,})\s*$/);
      if (closing && closing[1]![0] === fence.character && closing[1]!.length >= fence.length) {
        fence = undefined;
        return { text, code: false, fence: true };
      }
      return { text, code: true, fence: false };
    }
    const opening = text.match(/^ {0,3}(`{3,}|~{3,})(.*)$/);
    if (opening && !(opening[1]![0] === "`" && opening[2]!.includes("`"))) {
      fence = { character: opening[1]![0]!, length: opening[1]!.length };
      return { text, code: false, fence: true };
    }
    const heading = text.match(/^ {0,3}(#{1,6})[ \t]+(.+?)\s*$/);
    return {
      text, code: false, fence: false,
      ...(heading ? { heading: { level: heading[1]!.length, title: normalizeHeading(heading[2]!) } } : {})
    };
  });
}

function isPlaceholderLine(line: MarkdownLine): boolean {
  if (line.code || line.fence || /^\s*>/.test(line.text)) return false;
  const text = line.text.trim().replace(/^[-*+]\s+/, "").replace(/^\d+[.)]\s+/, "");
  const withoutEmphasis = text.replace(/^\*{1,2}(.*?)\*{1,2}$/, "$1");
  if (scaffoldMarkers.has(withoutEmphasis)) return true;
  // Only whole values are placeholders. Quoted examples, code and mentions in prose are valid.
  const value = withoutEmphasis.toLocaleLowerCase("en-US");
  return placeholderValues.has(value) || scaffoldValueLines.has(value) || /^(?:todo|tbd|placeholder|\.\.\.)[.!]?$/.test(value);
}

function hasSubstantiveContent(content: string, ignoreEvidence = false): boolean {
  let evidenceSection = false;
  let comment = false;
  return markdownLines(content).some(line => {
    if (line.heading) {
      if (line.heading.level <= 2) evidenceSection = headingKey(line.heading.title) === "evidence";
      return false;
    }
    if (line.fence || (ignoreEvidence && evidenceSection) || isPlaceholderLine(line)) return false;
    let value = line.text;
    if (!line.code) {
      if (comment) {
        const end = value.indexOf("-->");
        if (end < 0) return false;
        value = value.slice(end + 3);
        comment = false;
      }
      value = value.replace(/<!--[\s\S]*?-->/g, "");
      const start = value.indexOf("<!--");
      if (start >= 0) {
        value = value.slice(0, start);
        comment = true;
      }
    }
    return /[\p{L}\p{N}]/u.test(value);
  });
}

const authoredText = z.string().refine(value =>
  !markdownLines(value).some(isPlaceholderLine), "Replace unfilled scaffold values with observed repository findings."
);

/** The model supplies findings and observed paths; the runtime owns Markdown structure. */
export const codebaseDocumentModelSchema = z.strictObject({
  summary: authoredText.refine(hasSubstantiveContent, "Provide a substantive summary of this codebase area.")
    .describe("Required repository findings. Multiline Markdown, Unicode and fenced code are supported. No unfilled scaffold values."),
  sections: z.array(z.strictObject({
    heading: z.string().describe("Optional topic name. Case and whitespace are normalized. Purpose and Evidence are runtime-owned."),
    content: authoredText.describe("Findings for this topic. Empty sections are omitted; honest short answers such as None are valid.")
  })).optional().describe("Include only useful topics. Omit or use [] when the summary is sufficient. Conflicting duplicate headings are invalid."),
  evidencePaths: z.array(z.string().trim().min(1).refine(value => !/[\r\n]/.test(value), "Evidence paths must occupy one line."))
    .min(1).describe("At least one observed repository-relative path from the preparation packet. The runtime renders literal paths.")
}).superRefine((model, ctx) => {
  const sections = new Map<string, string>();
  for (const [index, section] of (model.sections ?? []).entries()) {
    const content = normalizeText(section.content);
    if (!content) continue;
    const key = headingKey(section.heading);
    if (!key || key === "purpose" || key === "evidence") {
      ctx.addIssue({ code: "custom", path: ["sections", index, "heading"], message: "Populated sections require a topic name other than Purpose or Evidence." });
    }
    const previous = sections.get(key);
    if (previous !== undefined && previous !== content) {
      ctx.addIssue({ code: "custom", path: ["sections", index, "heading"], message: "Sections with the same normalized heading must not contain conflicting content." });
    }
    sections.set(key, content);
  }
});
export type CodebaseDocumentModel = z.infer<typeof codebaseDocumentModelSchema>;

export const codebaseMapModelSchema = z.strictObject({
  stack: codebaseDocumentModelSchema.optional(),
  architecture: codebaseDocumentModelSchema.optional(),
  structure: codebaseDocumentModelSchema.optional(),
  conventions: codebaseDocumentModelSchema.optional(),
  testing: codebaseDocumentModelSchema.optional(),
  integrations: codebaseDocumentModelSchema.optional(),
  concerns: codebaseDocumentModelSchema.optional()
});
export type CodebaseMapModel = z.infer<typeof codebaseMapModelSchema>;

function nestedMarkdown(content: string): string {
  const parsed = markdownLines(normalizeText(content));
  const lines = parsed.map(line => {
    // Keep authored headings below runtime-owned H1/H2 without changing code examples.
    if (line.heading && line.heading.level < 3) {
      return `${"#".repeat(line.heading.level + 2)} ${line.heading.title}`;
    }
    return line.text;
  });
  const fences = parsed.filter(line => line.fence);
  if (fences.length % 2 !== 0) {
    // A missing closing fence must not swallow runtime-owned sections or evidence.
    lines.push(fences.at(-1)!.text.match(/^ {0,3}(`{3,}|~{3,})/)![1]!);
  }
  // Close an unfinished HTML comment so it cannot hide subsequent runtime
  // headings. Ignore fenced and inline code where comment syntax is literal.
  let commentOpen = false;
  for (const line of parsed) {
    if (line.code || line.fence) continue;
    const visible = line.text.replace(/(`+).*?\1/g, "");
    let position = 0;
    while (position < visible.length) {
      const marker = commentOpen ? "-->" : "<!--";
      const found = visible.indexOf(marker, position);
      if (found < 0) break;
      commentOpen = !commentOpen;
      position = found + marker.length;
    }
  }
  if (commentOpen) lines.push("-->");
  return lines.join("\n");
}

function literalPath(value: string): string {
  const longest = Math.max(0, ...(value.match(/`+/g) ?? []).map(run => run.length));
  const fence = "`".repeat(longest + 1);
  const padding = value.startsWith("`") || value.endsWith("`") ? " " : "";
  return `${fence}${padding}${value}${padding}${fence}`;
}

export function compileCodebaseDocument(
  artifactId: CodebaseDocumentId | CodebaseDocumentContractId,
  input: unknown
): string {
  const id = artifactId.startsWith("codebase.") ? artifactId as CodebaseDocumentContractId : `codebase.${artifactId}` as CodebaseDocumentContractId;
  const contract = readArtifactContract(id);
  const model = codebaseDocumentModelSchema.parse(input);
  const lines = [`# ${contract.canonicalName.replace(/^Codebase /, "")}`, "", "## Purpose", "", nestedMarkdown(model.summary)];
  const seen = new Set<string>();
  for (const section of model.sections ?? []) {
    const key = headingKey(section.heading);
    if (!normalizeText(section.content) || seen.has(key)) continue;
    seen.add(key);
    lines.push("", `## ${normalizeHeading(section.heading)}`, "", nestedMarkdown(section.content));
  }
  lines.push("", "## Evidence", "", ...[...new Set(model.evidencePaths)].map(value => `- ${literalPath(value)}`));
  return `${lines.join("\n")}\n`;
}

export function compileCodebaseMap(input: unknown): Partial<Record<CodebaseDocumentId, string>> {
  const model = codebaseMapModelSchema.parse(input);
  return Object.fromEntries(CODEBASE_DOCUMENT_IDS.filter(id => model[id] !== undefined)
    .map(id => [id, compileCodebaseDocument(id, model[id])]));
}

/** Shared by canonical publication and legacy inspection; optional headings are never gates. */
export function validateCodebaseContent(content: string, artifactId: ArtifactContractId): {
  valid: boolean; issues: string[]; warnings: string[];
} {
  const contract = readArtifactContract(artifactId);
  const lines = markdownLines(content);
  const issues: string[] = [];
  const warnings: string[] = [];
  const first = lines.find(line => line.text.trim().length > 0);
  if (!first?.heading || first.heading.level !== 1 || !first.heading.title.trim()) {
    issues.push(`${contract.canonicalName} artifact must start with a markdown H1 title.`);
  }
  if (lines.some(isPlaceholderLine)) {
    issues.push(`${contract.canonicalName} artifact still contains placeholder scaffold text.`);
  }
  if (lines.filter(line => line.fence).length % 2 !== 0) {
    issues.push(`${contract.canonicalName} artifact contains an unclosed fenced code block.`);
  }
  if (!hasSubstantiveContent(content, true)) {
    issues.push(`${contract.canonicalName} artifact must contain substantive mapped prose or repository evidence beyond its headings and path list.`);
  }
  if (!lines.some(line => line.heading?.level === 2 && headingKey(line.heading.title) === "purpose")) {
    warnings.push(`${contract.canonicalName} artifact uses a legacy concise format without the canonical Purpose heading.`);
  }
  return { valid: issues.length === 0, issues, warnings };
}
